import type { ComponentType } from 'react';
import type { PikaIconProps } from '@xyne/icons';

export {
  Activity,
  AlertTriangle,
  AtMark,
  ArrowRight,
  BarchartDefault as BarChart3,
  Ai02 as Brain,
  Notebook as BookOpenCheck,
  Notebook as BookOpenText,
  CalendarRange,
  ChatChatting,
  ChatDefault,
  CheckTickSingle as Check,
  CheckTickDouble as CheckDouble,
  CheckTickCircle as CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ClockDefault as Clock,
  ContactsBook as Contact,
  ContactsBook,
  Database,
  FileSearch,
  FileText,
  File02Default,
  GraphTrendLineUpward as Flame,
  FolderDefault as FolderOpen,
  FolderDefault,
  GitBranch,
  GraduationHat as GraduationCap,
  GraduationHat,
  UserAi as Fingerprint,
  FilterLines as Filter,
  Ai02 as FlaskConical,
  ReminderAnticlockwise as History,
  InformationCircle as Info,
  LayerThree as Layers3,
  ListDefault as List,
  Spinner as Loader2,
  LockClose as LockKeyhole,
  ChatChatting as MessageSquareText,
  ThreeDotsMenuHorizontal as MoreHorizontal,
  GitBranch as Network,
  PauseSmall as Pause,
  PencilEdit as Pencil,
  PencilEdit,
  PlaySmall as Play,
  PlusDefault as Plus,
  PhoneDefault,
  Refresh as RefreshCw,
  FileCheck as Save,
  SearchBig as Search,
  Settings01 as Settings,
  ShieldCheck,
  FilterHorizontal as SlidersHorizontal,
  SparkleAi01 as Sparkles,
  DeleteDustbin01 as Trash2,
  UploadUp as Upload,
  UturnLeft,
  UserThree as Users,
  UserThree,
  Tools as Wrench,
  MultipleCrossCancelDefault as X,
  MultipleCrossCancelCircle as XCircle,
} from '@xyne/icons';

export type DigitalTwinIcon = ComponentType<PikaIconProps>;
