/**
 * v1 operation map: SDK operation id -> catalog operation or route.
 *
 * This is the file that absorbs backend change. When a Zero query is renamed,
 * re-keyed or superseded by a V2, the entry here moves and every already-shipped
 * client keeps working — which is the point of versioning the surface rather than
 * publishing the catalog.
 *
 * The rules for editing it:
 *
 *   - An operation id, once shipped in a released SDK, never changes meaning.
 *     Retargeting it to a *different* Zero operation is fine; making it mean a
 *     different thing to the caller is not. That is what v2 is for.
 *   - Never delete an id that a released SDK calls. If the catalog operation is
 *     gone, point the id at its replacement, or leave it to fail loudly.
 *   - Argument shaping belongs in `parser.ts`, not here.
 *
 * Sections mirror the SDK's resources one-to-one, so `sdk.projects.update` is
 * found under `projects`.
 */

import type { V1Target } from './types';

export const V1_MAPPER: Readonly<Record<string, V1Target>> = {
  // ----- activities -----
  'activities.list': { kind: 'query', name: 'userActivitiesV2' },
  'activities.listPaginated': { kind: 'query', name: 'userActivitiesPaginatedV2' },
  'activities.listUnread': { kind: 'query', name: 'userUnreadActivities' },
  'activities.listUnreadThreads': { kind: 'query', name: 'userUnreadThreadActivities' },
  'activities.listMissedCalls': { kind: 'query', name: 'userMissedCalls' },
  'activities.listBookmarks': { kind: 'query', name: 'userBookmarks' },
  'activities.markAsRead': { kind: 'mutator', name: 'activities.markAsRead' },
  'activities.markAsUnread': { kind: 'mutator', name: 'activities.markAsUnread' },
  'activities.markThreadAsRead': { kind: 'mutator', name: 'activities.markThreadActivitiesAsReadV2' },
  'activities.markMissedCallsAsRead': { kind: 'mutator', name: 'activities.markMissedCallsAsRead' },
  'activities.markSeenByMessage': { kind: 'mutator', name: 'activities.markActivitiesSeenByMessageId' },
  'activities.dismissNudge': { kind: 'mutator', name: 'nudges.dismiss' },
  'activities.actOnNudge': { kind: 'mutator', name: 'nudges.act' },
  'activities.markAsReadByFilter': { kind: 'mutator', name: 'activities.markAsReadByFilter' },

  // ----- admin -----
  'admin.getWorkspace': { kind: 'query', name: 'getWorkspaceById' },
  'admin.listWorkspaceOrgs': { kind: 'query', name: 'workspaceOrganizations' },
  'admin.listAvailableOrgs': { kind: 'query', name: 'availableOrganizations' },
  'admin.updateWorkspace': { kind: 'mutator', name: 'workspace.update' },
  'admin.createOrg': { kind: 'mutator', name: 'org.create' },
  'admin.addOrgToWorkspace': { kind: 'mutator', name: 'workspaceOrg.add' },
  'admin.removeOrgFromWorkspace': { kind: 'mutator', name: 'workspaceOrg.remove' },
  'admin.listOrgMembers': { kind: 'query', name: 'getOrgMembers' },
  'admin.getOrgMember': { kind: 'query', name: 'getOrgMemberById' },
  'admin.addOrgMember': { kind: 'mutator', name: 'orgMember.add' },
  'admin.updateOrgMemberRole': { kind: 'mutator', name: 'orgMember.updateRole' },
  'admin.removeOrgMember': { kind: 'mutator', name: 'orgMember.remove' },
  'admin.updateUserRole': { kind: 'mutator', name: 'users.updateRole' },
  'admin.removeUser': { kind: 'mutator', name: 'users.remove' },
  'admin.listInvitations': { kind: 'query', name: 'getAllInvitations' },
  'admin.revokeInvitation': { kind: 'mutator', name: 'invitation.revoke' },
  'admin.listRoles': { kind: 'query', name: 'roles' },
  'admin.getRole': { kind: 'query', name: 'roleById' },
  'admin.createRole': { kind: 'mutator', name: 'role.create' },
  'admin.updateRole': { kind: 'mutator', name: 'role.update' },
  'admin.addRoleMembers': { kind: 'mutator', name: 'role.addMembers' },
  'admin.removeRoleMembers': { kind: 'mutator', name: 'role.removeMembers' },
  'admin.listResources': { kind: 'query', name: 'getAllResources' },
  'admin.listUserAccess': { kind: 'query', name: 'getResourceAccessForUser' },
  'admin.grantAccess': { kind: 'mutator', name: 'resourceAccess.grant' },
  'admin.updateAccess': { kind: 'mutator', name: 'resourceAccess.update' },
  'admin.revokeAccess': { kind: 'mutator', name: 'resourceAccess.revoke' },
  'admin.listInstalledApps': { kind: 'query', name: 'getWorkspaceInstalledApps' },
  'admin.listOrgApps': { kind: 'query', name: 'getOrgApps' },
  'admin.listMarketplaceApps': { kind: 'query', name: 'getMarketplaceApps' },
  'admin.updateApp': { kind: 'mutator', name: 'apps.update' },

  // ----- automations -----
  'automations.list': { kind: 'query', name: 'automationsList' },
  'automations.get': { kind: 'query', name: 'automationById' },
  'automations.listWorkflows': { kind: 'query', name: 'workflowsPaginated' },
  'automations.createProposal': { kind: 'mutator', name: 'automations.createProposal' },
  'automations.update': { kind: 'mutator', name: 'automations.update' },
  'automations.delete': { kind: 'mutator', name: 'automations.delete' },
  'automations.submitForApproval': { kind: 'mutator', name: 'automations.submitForApproval' },
  'automations.revoke': { kind: 'mutator', name: 'automations.revoke' },
  'automations.approve': { kind: 'mutator', name: 'automations.approve' },
  'automations.reject': { kind: 'mutator', name: 'automations.reject' },
  'automations.activate': { kind: 'mutator', name: 'automations.activate' },
  'automations.disable': { kind: 'mutator', name: 'automations.disable' },
  'automations.archive': { kind: 'mutator', name: 'automations.archive' },

  // ----- boards -----
  'boards.list': { kind: 'query', name: 'getAllBoards' },
  'boards.listByProject': { kind: 'query', name: 'boardsByProject' },
  'boards.listByProjectLite': { kind: 'query', name: 'boardsListByProject' },
  'boards.getMany': { kind: 'query', name: 'boardsByIds' },
  'boards.get': { kind: 'query', name: 'getBoardById' },
  'boards.getDetail': { kind: 'query', name: 'boardDetailById' },
  'boards.getFullDetail': { kind: 'query', name: 'boardFullDetailById' },
  'boards.listStages': { kind: 'query', name: 'stagesByBoard' },
  'boards.listStagesForBoards': { kind: 'query', name: 'getStagesByBoardIds' },
  'boards.listStagesByProject': { kind: 'query', name: 'stagesByBoards' },
  'boards.listByChannel': { kind: 'query', name: 'boardsByChannel' },
  'boards.listTransitions': { kind: 'query', name: 'getStageTransitionsByBoardId' },
  'boards.listTransitionsForBoards': { kind: 'query', name: 'getStageTransitionsByBoardIds' },
  'boards.listSlaPolicies': { kind: 'query', name: 'getBoardSlaPolicies' },
  'boards.listSlaPoliciesForBoards': { kind: 'query', name: 'getBoardSlaPoliciesByBoardIds' },
  'boards.listComplexityScores': { kind: 'query', name: 'getBoardComplexityScores' },
  'boards.listSavedViews': { kind: 'query', name: 'savedConfigsByBoard' },
  'boards.listFormMappings': { kind: 'query', name: 'getFormMappingsByBoardIds' },
  'boards.update': { kind: 'mutator', name: 'board.update' },
  'boards.delete': { kind: 'mutator', name: 'board.delete' },
  'boards.upsertSlaPolicy': { kind: 'mutator', name: 'boardSlaPolicy.upsert' },
  'boards.deleteSlaPolicy': { kind: 'mutator', name: 'boardSlaPolicy.delete' },
  'boards.syncTransitions': { kind: 'mutator', name: 'nonLinear.syncTransitions' },
  'boards.updateFlowPlan': { kind: 'mutator', name: 'board.updateFlowPlan' },

  // ----- calls -----
  'calls.listActive': { kind: 'query', name: 'userActiveCalls' },
  'calls.listActiveInChannel': { kind: 'query', name: 'activeCallsInChannel' },
  'calls.listScheduled': { kind: 'query', name: 'userScheduledCallsV2' },
  'calls.listHistory': { kind: 'query', name: 'userCallHistoryV2' },
  'calls.listParticipants': { kind: 'query', name: 'callParticipantsByCallId' },
  'calls.getRecurringSeries': { kind: 'query', name: 'recurringSeriesById' },
  'calls.getSummaryTemplate': { kind: 'query', name: 'summaryTemplateById' },
  'calls.listSummaryTemplates': { kind: 'query', name: 'summaryTemplates' },
  'calls.listRecordings': { kind: 'query', name: 'userRecordings' },
  'calls.listCreatedRecordings': { kind: 'query', name: 'createdOatsRecordings' },
  'calls.listSharedRecordings': { kind: 'query', name: 'sharedOatsRecordings' },
  'calls.getRecording': { kind: 'query', name: 'oatsRecordingByExternalId' },
  'calls.getConversation': { kind: 'query', name: 'getConversationByCallId' },
  'calls.initiate': { kind: 'mutator', name: 'calls.initiate' },
  'calls.join': { kind: 'mutator', name: 'calls.join' },
  'calls.leave': { kind: 'mutator', name: 'calls.leave' },
  'calls.reject': { kind: 'mutator', name: 'calls.reject' },
  'calls.cancel': { kind: 'mutator', name: 'calls.cancel' },
  'calls.invite': { kind: 'mutator', name: 'calls.invite' },
  'calls.linkNotesCanvas': { kind: 'mutator', name: 'calls.linkNotesCanvas' },
  'calls.markMoment': { kind: 'mutator', name: 'calls.markMoment' },
  'calls.requestToJoin': { kind: 'mutator', name: 'calls.requestToJoin' },
  'calls.cancelJoinRequest': { kind: 'mutator', name: 'calls.cancelJoinRequest' },
  'calls.approveLobbyRequest': { kind: 'mutator', name: 'calls.approveLobbyRequest' },
  'calls.rejectLobbyRequest': { kind: 'mutator', name: 'calls.rejectLobbyRequest' },

  // ----- canvases -----
  'canvases.list': { kind: 'query', name: 'userCanvasesPaginated' },
  'canvases.listQuartoDocs': { kind: 'query', name: 'userQuartoDocsPaginated' },
  'canvases.listByChannel': { kind: 'query', name: 'channelCanvasesPaginated' },
  'canvases.listQuartoDocsByChannel': { kind: 'query', name: 'channelQuartoDocsPaginated' },
  'canvases.listByFolder': { kind: 'query', name: 'projectFolderCanvases' },
  'canvases.listHierarchy': { kind: 'query', name: 'hierarchyCanvases' },
  'canvases.get': { kind: 'query', name: 'getCanvas' },
  'canvases.listParticipants': { kind: 'query', name: 'canvasParticipants' },
  'canvases.listVersions': { kind: 'query', name: 'canvasVersions' },
  'canvases.listCommentThreads': { kind: 'query', name: 'canvasCommentThreads' },
  'canvases.listThreadComments': { kind: 'query', name: 'canvasThreadComments' },
  'canvases.listPersonalFolders': { kind: 'query', name: 'personalCanvasFolders' },
  'canvases.listChannelFolders': { kind: 'query', name: 'channelCanvasFolders' },
  'canvases.listProjectFolders': { kind: 'query', name: 'projectCanvasFolders' },
  'canvases.createFolder': { kind: 'mutator', name: 'canvasFolder.create' },
  'canvases.updateFolder': { kind: 'mutator', name: 'canvasFolder.update' },
  'canvases.deleteFolder': { kind: 'mutator', name: 'canvasFolder.delete' },
  'canvases.create': { kind: 'mutator', name: 'canvas.create' },
  'canvases.update': { kind: 'mutator', name: 'canvas.update' },
  'canvases.delete': { kind: 'mutator', name: 'canvas.delete' },
  'canvases.toggleStarred': { kind: 'mutator', name: 'canvasUserStatus.toggleStarred' },
  'canvases.addParticipants': { kind: 'mutator', name: 'canvas.addParticipants' },
  'canvases.addGroupParticipant': { kind: 'mutator', name: 'canvas.addGroupParticipant' },
  'canvases.addChannelParticipant': { kind: 'mutator', name: 'canvas.addChannelParticipant' },
  'canvases.removeParticipant': { kind: 'mutator', name: 'canvas.removeParticipant' },
  'canvases.removeGroupParticipant': { kind: 'mutator', name: 'canvas.removeGroupParticipant' },
  'canvases.removeChannelParticipant': { kind: 'mutator', name: 'canvas.removeChannelParticipant' },
  'canvases.updateParticipantRole': { kind: 'mutator', name: 'canvas.updateParticipantRole' },
  'canvases.updateGroupParticipantRole': { kind: 'mutator', name: 'canvas.updateGroupParticipantRole' },
  'canvases.updateChannelParticipantRole': { kind: 'mutator', name: 'canvas.updateChannelParticipantRole' },
  'canvases.createCommentThread': { kind: 'mutator', name: 'canvasComment.createThread' },
  'canvases.replyToThread': { kind: 'mutator', name: 'canvasComment.reply' },
  'canvases.updateComment': { kind: 'mutator', name: 'canvasComment.updateComment' },
  'canvases.deleteComment': { kind: 'mutator', name: 'canvasComment.deleteComment' },
  'canvases.setThreadStatus': { kind: 'mutator', name: 'canvasComment.setThreadStatus' },
  'canvases.saveVersion': { kind: 'mutator', name: 'canvasVersion.save' },
  'canvases.renameVersion': { kind: 'mutator', name: 'canvasVersion.rename' },
  'canvases.restoreVersion': { kind: 'mutator', name: 'canvasVersion.restore' },
  'canvases.archive': { kind: 'mutator', name: 'canvas.archiveCanvas' },
  'canvases.unarchive': { kind: 'mutator', name: 'canvas.unarchiveCanvas' },

  // ----- channels -----
  'channels.list': { kind: 'query', name: 'userVisibleChannelsV3' },
  'channels.listAll': { kind: 'query', name: 'userAllChannels' },
  'channels.listEmail': { kind: 'query', name: 'userVisibleEmailChannels' },
  'channels.listBrowsable': { kind: 'query', name: 'browsableChannels' },
  'channels.getStats': { kind: 'query', name: 'channelStats' },
  'channels.getUserStatus': { kind: 'query', name: 'getChannelUserStatus' },
  'channels.listParticipants': { kind: 'query', name: 'channelParticipants' },
  'channels.searchParticipants': { kind: 'query', name: 'searchChannelParticipants' },
  'channels.getMyParticipations': { kind: 'query', name: 'getUserMultipleChannelParticipations' },
  'channels.listLinks': { kind: 'query', name: 'channelLinks' },
  'channels.listSections': { kind: 'query', name: 'userChannelSections' },
  'channels.join': { kind: 'mutator', name: 'channel.joinChannel' },
  'channels.leave': { kind: 'mutator', name: 'channel.leaveChannel' },
  'channels.addParticipants': { kind: 'mutator', name: 'channel.addParticipants' },
  'channels.removeParticipant': { kind: 'mutator', name: 'channel.removeParticipant' },
  'channels.updateParticipantRole': { kind: 'mutator', name: 'channel.updateParticipantRole' },
  'channels.rename': { kind: 'mutator', name: 'channel.renameChannel' },
  'channels.updateDescription': { kind: 'mutator', name: 'channel.updateDescription' },
  'channels.archive': { kind: 'mutator', name: 'channel.archiveChannel' },
  'channels.unarchive': { kind: 'mutator', name: 'channel.unarchiveChannel' },
  'channels.makePublic': { kind: 'mutator', name: 'channel.makeChannelPublic' },
  'channels.toggleStarred': { kind: 'mutator', name: 'channel.toggleStarred' },
  'channels.markAsViewed': { kind: 'mutator', name: 'channel.markChannelAsViewed' },
  'channels.moveToSection': { kind: 'mutator', name: 'channel.moveToSection' },
  'channels.createSection': { kind: 'mutator', name: 'channelSection.create' },
  'channels.updateSection': { kind: 'mutator', name: 'channelSection.update' },
  'channels.removeSection': { kind: 'mutator', name: 'channelSection.remove' },
  'channels.closeDm': { kind: 'mutator', name: 'channel.closeDm' },
  'channels.reopenDm': { kind: 'mutator', name: 'channel.reopenDm' },
  'channels.promoteToChannel': { kind: 'mutator', name: 'channel.promoteToChannel' },
  'channels.markUnreadFrom': { kind: 'mutator', name: 'channel.markChannelUnreadFrom' },
  'channels.setAddUserPolicy': { kind: 'mutator', name: 'channel.updateAddUserPolicy' },
  'channels.setCallSummaryPrompt': { kind: 'mutator', name: 'channel.updateCallSummaryPrompt' },
  'channels.setSelectedBoard': { kind: 'mutator', name: 'channel.updateSelectedBoardId' },
  'channels.setShowTicketsInChat': { kind: 'mutator', name: 'channel.updateShowTicketsTabTicketsInChat' },
  'channels.getStatsForChannels': { kind: 'query', name: 'channelStatsByIds' },
  'channels.listParticipantsPaginated': { kind: 'query', name: 'channelParticipantsPaginated' },
  'channels.listUserStatuses': { kind: 'query', name: 'getAllChannelsUserStatus' },
  'channels.listWithMyConversations': { kind: 'query', name: 'conversationOfUserChannels' },

  // ----- collections -----
  'collections.list': { kind: 'query', name: 'scopedCollections' },
  'collections.listSubfolders': { kind: 'query', name: 'collectionSubfolders' },
  'collections.listPermissions': { kind: 'query', name: 'collectionPermissions' },
  'collections.listItems': { kind: 'query', name: 'collectionItems' },
  'collections.get': { kind: 'query', name: 'collectionById' },
  'collections.listFilesByRoot': { kind: 'query', name: 'collectionFilesByRoot' },
  'collections.listWithItems': { kind: 'query', name: 'scopedCollectionsWithItems' },
  'collections.create': { kind: 'mutator', name: 'collection.createCollection' },
  'collections.update': { kind: 'mutator', name: 'collection.updateCollection' },
  'collections.delete': { kind: 'mutator', name: 'collection.deleteCollection' },
  'collections.createFolder': { kind: 'mutator', name: 'collection.createFolder' },
  'collections.renameItem': { kind: 'mutator', name: 'collection.renameItem' },
  'collections.deleteItem': { kind: 'mutator', name: 'collection.deleteItem' },
  'collections.grantPermission': { kind: 'mutator', name: 'collection.grantPermission' },
  'collections.revokePermission': { kind: 'mutator', name: 'collection.revokePermission' },

  // ----- conversations -----
  'conversations.listByChannel': { kind: 'query', name: 'channelConversationsPaginatedV3' },
  'conversations.listLatestByChannel': { kind: 'query', name: 'channelLatestMultipleConversationsV3' },
  'conversations.get': { kind: 'query', name: 'getConversationById' },
  'conversations.getWithChannel': { kind: 'query', name: 'getConversationByIdWithChannel' },
  'conversations.getThread': { kind: 'query', name: 'threadConversationV2' },
  'conversations.getByCallId': { kind: 'query', name: 'getConversationByCallId' },
  'conversations.getMyParticipation': { kind: 'query', name: 'conversationParticipantByConversationId' },
  'conversations.listPinned': { kind: 'query', name: 'getPinnedMessegesV2' },
  'conversations.getLatest': { kind: 'query', name: 'channelLatestConversation' },
  'conversations.listLabels': { kind: 'query', name: 'conversationLabelsByChannelIdV2' },
  'conversations.listAppliedLabels': { kind: 'query', name: 'conversationLabelMappingsByConversationIdV2' },
  'conversations.create': { kind: 'mutator', name: 'conversations.send' },
  'conversations.togglePin': { kind: 'mutator', name: 'conversations.togglePin' },
  'conversations.forwardMessage': { kind: 'mutator', name: 'conversations.forwardMessage' },
  'conversations.subscribe': { kind: 'mutator', name: 'conversations.subscribeToConversation' },
  'conversations.unsubscribe': { kind: 'mutator', name: 'conversations.unsubscribeFromConversation' },
  'conversations.markUnreadFrom': { kind: 'mutator', name: 'conversation.markThreadUnreadFrom' },
  'conversations.getByTimestamp': { kind: 'query', name: 'getConversationByTimestamp' },
  'conversations.listForUser': { kind: 'query', name: 'userConversationsPaginatedV2' },
  'conversations.setTagTypes': { kind: 'mutator', name: 'threadTag.setTypes' },

  // ----- dashboards -----
  'dashboards.list': { kind: 'query', name: 'getAllDashboards' },
  'dashboards.get': { kind: 'query', name: 'getDashboardById' },
  'dashboards.upsert': { kind: 'mutator', name: 'dashboard.upsert' },
  'dashboards.delete': { kind: 'mutator', name: 'dashboard.delete' },
  'dashboards.updateLayout': { kind: 'mutator', name: 'dashboardComponent.updatePositions' },
  'dashboards.upsertQuery': { kind: 'mutator', name: 'query.upsert' },
  'dashboards.deleteQuery': { kind: 'mutator', name: 'query.delete' },
  'dashboards.reorderQueries': { kind: 'mutator', name: 'query.reorder' },

  // ----- email -----
  'email.listForConversations': { kind: 'query', name: 'getEmailsForConversationsV2' },
  'email.listSent': { kind: 'query', name: 'userEmailsSent' },
  'email.listDrafts': { kind: 'query', name: 'userEmailDrafts' },
  'email.getDraftForConversation': { kind: 'query', name: 'getDraftForConversationV2' },
  'email.listComposeDrafts': { kind: 'query', name: 'composeDraftsByChannel' },
  'email.listSignatures': { kind: 'query', name: 'userEmailSignatures' },
  'email.getChannelPreference': { kind: 'query', name: 'getEmailChannelPreference' },
  'email.listLabels': { kind: 'query', name: 'conversationLabelsByChannelIdV2' },
  'email.listConversationsByLabel': { kind: 'query', name: 'conversationLabelMappingsByLabelId' },
  'email.saveDraft': { kind: 'mutator', name: 'emailDraft.upsert' },
  'email.deleteDraft': { kind: 'mutator', name: 'emailDraft.delete' },
  'email.saveComposeDraft': { kind: 'mutator', name: 'emailDraft.upsertComposeDraft' },
  'email.deleteComposeDraft': { kind: 'mutator', name: 'emailDraft.deleteComposeDraft' },
  'email.markAsRead': { kind: 'mutator', name: 'emailRead.markAsRead' },
  'email.bulkMarkAsRead': { kind: 'mutator', name: 'emailRead.bulkMarkAsRead' },
  'email.bulkMarkAsUnread': { kind: 'mutator', name: 'emailRead.bulkMarkAsUnread' },
  'email.createSignature': { kind: 'mutator', name: 'emailSignature.create' },
  'email.updateSignature': { kind: 'mutator', name: 'emailSignature.update' },
  'email.deleteSignature': { kind: 'mutator', name: 'emailSignature.delete' },
  'email.setDefaultSignature': { kind: 'mutator', name: 'emailSignature.setDefault' },
  'email.setChannelPreference': { kind: 'mutator', name: 'emailChannelPreference.upsert' },
  'email.setClassificationConfig': { kind: 'mutator', name: 'emailChannelPreference.upsertClassificationConfig' },
  'email.setPriorityClassificationConfig': { kind: 'mutator', name: 'emailChannelPreference.upsertPriorityClassificationConfig' },
  'email.createLabel': { kind: 'mutator', name: 'conversationLabel.createLabel' },
  'email.applyLabel': { kind: 'mutator', name: 'conversationLabel.applyLabel' },
  'email.removeLabel': { kind: 'mutator', name: 'conversationLabel.removeLabel' },

  // ----- forms -----
  'forms.get': { kind: 'query', name: 'getFormById' },
  'forms.list': { kind: 'query', name: 'getAllForms' },
  'forms.listLite': { kind: 'query', name: 'getAllFormsList' },
  'forms.listByContextType': { kind: 'query', name: 'getFormsByContextType' },
  'forms.listMappingsByContextIds': { kind: 'query', name: 'getFormMappingsByContextIds' },
  'forms.listFields': { kind: 'query', name: 'getFormFieldsByFormId' },
  'forms.getMapping': { kind: 'query', name: 'getFormMappingByContextId' },
  'forms.listMappingsForBoards': { kind: 'query', name: 'getFormMappingsByBoardIds' },
  'forms.listValues': { kind: 'query', name: 'getFormEntityValuesByEntityId' },
  'forms.listAllTicketValues': { kind: 'query', name: 'getAllFormEntityValues' },
  'forms.update': { kind: 'mutator', name: 'form.update' },
  'forms.setMapping': { kind: 'mutator', name: 'formContextMapping.upsert' },
  'forms.deleteMapping': { kind: 'mutator', name: 'formContextMapping.delete' },
  'forms.createValue': { kind: 'mutator', name: 'formEntityValue.createV2' },
  'forms.updateValue': { kind: 'mutator', name: 'formEntityValue.update' },

  // ----- incidents -----
  'incidents.listRcas': { kind: 'query', name: 'allRCAsPaginated' },
  'incidents.getRca': { kind: 'query', name: 'rcaById' },
  'incidents.listImpactAttachments': { kind: 'query', name: 'attachmentsByImpact' },
  'incidents.listAttachmentsForImpacts': { kind: 'query', name: 'attachmentsByImpactIds' },
  'incidents.listReleaseTickets': { kind: 'query', name: 'releaseTickets' },
  'incidents.searchReleaseTickets': { kind: 'query', name: 'releaseTicketsSearch' },
  'incidents.listApplicationReleaseTickets': { kind: 'query', name: 'applicationReleaseTicketsByReleaseId' },
  'incidents.listReleaseChanges': { kind: 'query', name: 'releaseChangesByReleaseId' },
  'incidents.listReleaseChangeFormValues': { kind: 'query', name: 'releaseChangeFormValuesByReleaseId' },
  'incidents.listReleaseChangeLog': { kind: 'query', name: 'releaseChangeLogValuesByReleaseId' },
  'incidents.createRca': { kind: 'mutator', name: 'rca.create' },
  'incidents.updateRca': { kind: 'mutator', name: 'rca.update' },
  'incidents.createImpact': { kind: 'mutator', name: 'impact.create' },
  'incidents.updateImpact': { kind: 'mutator', name: 'impact.update' },
  'incidents.deleteImpact': { kind: 'mutator', name: 'impact.delete' },
  'incidents.createAction': { kind: 'mutator', name: 'coe.create' },
  'incidents.updateAction': { kind: 'mutator', name: 'coe.update' },
  'incidents.deleteAction': { kind: 'mutator', name: 'coe.delete' },
  'incidents.createAttribution': { kind: 'mutator', name: 'releaseAttribution.create' },
  'incidents.updateAttribution': { kind: 'mutator', name: 'releaseAttribution.update' },
  'incidents.deleteAttribution': { kind: 'mutator', name: 'releaseAttribution.delete' },
  'incidents.updateReleaseTicketStatus': { kind: 'mutator', name: 'applicationReleaseTicket.updateStatus' },
  'incidents.setReleaseTicketTestedBy': { kind: 'mutator', name: 'applicationReleaseTicket.setTestedBy' },
  'incidents.listReleaseEvents': { kind: 'query', name: 'releaseEventsByReleaseId' },

  // ----- messages -----
  'messages.listByConversation': { kind: 'query', name: 'conversationMessagesV2' },
  'messages.getMany': { kind: 'query', name: 'messagesByIds' },
  'messages.get': { kind: 'query', name: 'getMessageForActivityV2' },
  'messages.listByChannel': { kind: 'query', name: 'channelAndThreadMessagesV2' },
  'messages.listMine': { kind: 'query', name: 'userSentMessagesPaginated' },
  'messages.getLatestInChannel': { kind: 'query', name: 'channelLatestMessageV2' },
  'messages.listNudges': { kind: 'query', name: 'messageNudges' },
  'messages.send': { kind: 'mutator', name: 'messages.send' },
  'messages.update': { kind: 'mutator', name: 'messages.update' },
  'messages.delete': { kind: 'mutator', name: 'messages.delete' },
  'messages.react': { kind: 'mutator', name: 'messages.react' },
  'messages.setShowInChannel': { kind: 'mutator', name: 'messages.updateShowInChannel' },
  'messages.closeSlashCommandArtifact': { kind: 'mutator', name: 'messages.closeSlashCommandArtifact' },
  'messages.deleteAttachment': { kind: 'mutator', name: 'messageAttachment.delete' },
  'messages.deleteAttachments': { kind: 'mutator', name: 'messageAttachment.deleteMany' },
  'messages.listDrafts': { kind: 'query', name: 'userDrafts' },
  'messages.editDraft': { kind: 'mutator', name: 'draftMessages.edit' },
  'messages.sendDraft': { kind: 'mutator', name: 'draftMessages.send' },
  'messages.deleteDraft': { kind: 'mutator', name: 'draftMessages.delete' },
  'messages.listScheduled': { kind: 'query', name: 'userDelayedMessages' },
  'messages.schedule': { kind: 'mutator', name: 'delayedMessages.create' },
  'messages.cancelScheduled': { kind: 'mutator', name: 'delayedMessages.cancel' },
  'messages.reschedule': { kind: 'mutator', name: 'delayedMessages.reschedule' },
  'messages.editScheduled': { kind: 'mutator', name: 'delayedMessages.edit' },
  'messages.sendScheduledNow': { kind: 'mutator', name: 'delayedMessages.sendNow' },
  'messages.scheduledToDraft': { kind: 'mutator', name: 'delayedMessages.convertToDraft' },
  'messages.getAttachments': { kind: 'query', name: 'attachmentsByIds' },
  'messages.listAttachmentsForThread': { kind: 'query', name: 'attachmentsByInitialMessage' },
  'messages.listChannelAttachments': { kind: 'query', name: 'getConversationAttachementsV2' },
  'messages.listScheduledPaginated': { kind: 'query', name: 'userDelayedMessagesPaginated' },
  'messages.addDraftAttachments': { kind: 'mutator', name: 'draft.createAttachments' },
  'messages.clearDraft': { kind: 'mutator', name: 'draft.clearContent' },
  'messages.handleNonParticipants': { kind: 'mutator', name: 'messages.handleNonParticipantAction' },

  // ----- preferences -----
  'preferences.get': { kind: 'query', name: 'getCurrentUserPreference' },
  'preferences.listBookmarks': { kind: 'query', name: 'userBookmarks' },
  'preferences.listSavedViews': { kind: 'query', name: 'savedConfigsByUser' },
  'preferences.setNotificationSettings': { kind: 'mutator', name: 'userPreference.setGlobalNotificationSettings' },
  'preferences.setNotificationKeywords': { kind: 'mutator', name: 'userPreference.setNotificationKeywords' },
  'preferences.setChannelNotifications': { kind: 'mutator', name: 'notificationSettings.setChannelNotificationLevel' },
  'preferences.setChannelSortOrder': { kind: 'mutator', name: 'userPreference.setChannelSortOrder' },
  'preferences.setSidebarGroup': { kind: 'mutator', name: 'userPreference.setSidebarGroupPreference' },
  'preferences.setEnterSendsMessage': { kind: 'mutator', name: 'userPreference.setEnterSendsMessage' },
  'preferences.setShowThreadTags': { kind: 'mutator', name: 'userPreference.setShowThreadTags' },
  'preferences.setAllowThreadBroadcastMentions': { kind: 'mutator', name: 'userPreference.setAllowThreadBroadcastMentions' },
  'preferences.updateProfile': { kind: 'mutator', name: 'userProfile.upsert' },
  'preferences.updatePresence': { kind: 'mutator', name: 'userPresence.upsert' },
  'preferences.addBookmark': { kind: 'mutator', name: 'bookmark.add' },
  'preferences.removeBookmark': { kind: 'mutator', name: 'bookmark.remove' },
  'preferences.updateBookmark': { kind: 'mutator', name: 'bookmark.updateMetadata' },
  'preferences.createSavedView': { kind: 'mutator', name: 'savedUserConfiguration.create' },
  'preferences.updateSavedView': { kind: 'mutator', name: 'savedUserConfiguration.update' },
  'preferences.deleteSavedView': { kind: 'mutator', name: 'savedUserConfiguration.delete' },

  // ----- projects -----
  'projects.list': { kind: 'query', name: 'getAllProjects' },
  'projects.listLite': { kind: 'query', name: 'getAllProjectsList' },
  'projects.get': { kind: 'query', name: 'projectById' },
  'projects.getMany': { kind: 'query', name: 'projectsByIds' },
  'projects.listTags': { kind: 'query', name: 'projectTagsByProjectId' },
  'projects.listFieldDefinitions': { kind: 'query', name: 'getAllTicketEntityMappings' },
  'projects.listCanvasFolders': { kind: 'query', name: 'projectCanvasFolders' },
  'projects.listApplications': { kind: 'query', name: 'applicationsByProjectId' },
  'projects.listReleaseTickets': { kind: 'query', name: 'releaseTicketsByProjectId' },
  'projects.listRecaps': { kind: 'query', name: 'projectRecaps' },
  'projects.update': { kind: 'mutator', name: 'project.update' },
  'projects.delete': { kind: 'mutator', name: 'project.delete' },
  'projects.saveReleaseBoardConfig': { kind: 'mutator', name: 'project.saveReleaseBoardConfig' },

  // ----- recaps -----
  'recaps.listForChannels': { kind: 'query', name: 'channelRecaps' },
  'recaps.listDaily': { kind: 'query', name: 'channelDailyRecaps' },
  'recaps.listForProjects': { kind: 'query', name: 'projectRecaps' },
  'recaps.listEntityNudges': { kind: 'query', name: 'entityNudges' },
  'recaps.listNudgesByCountRows': { kind: 'query', name: 'surfaceNudgesByCountRowIds' },
  'recaps.saveSubscriptions': { kind: 'mutator', name: 'recap.saveSubscriptions' },
  'recaps.setCustomPrompt': { kind: 'mutator', name: 'recap.setCustomRecapPrompt' },
  'recaps.markSeen': { kind: 'mutator', name: 'recap.markSeen' },
  'recaps.markChannelRead': { kind: 'mutator', name: 'recap.markChannelRecapAsRead' },
  'recaps.markChannelUnread': { kind: 'mutator', name: 'recap.markChannelRecapAsUnread' },

  // ----- supportTickets -----
  'supportTickets.list': { kind: 'query', name: 'supportTicketsPageV4' },
  'supportTickets.listFiltered': { kind: 'query', name: 'supportTicketsFilteredV3' },
  'supportTickets.get': { kind: 'query', name: 'supportTicketRowV3' },
  'supportTickets.getByKey': { kind: 'query', name: 'supportTicketByXyneIdV4' },
  'supportTickets.getDetail': { kind: 'query', name: 'supportTicketDetailV2' },
  'supportTickets.listForEmailChannels': { kind: 'query', name: 'ticketsForEmailChannelsV2' },

  // ----- tickets -----
  'tickets.list': { kind: 'query', name: 'ticketsQueryV2' },
  'tickets.listKanban': { kind: 'query', name: 'kanbanTicketsPageV3' },
  'tickets.listByChannelInWindow': { kind: 'query', name: 'topicsExplorerTickets' },
  'tickets.get': { kind: 'query', name: 'ticketByIdV2' },
  'tickets.getDetails': { kind: 'query', name: 'ticketDetailsByIdV2' },
  'tickets.getByKey': { kind: 'query', name: 'ticketByXyneIdV3' },
  'tickets.getMany': { kind: 'query', name: 'ticketsByIds' },
  'tickets.getRow': { kind: 'query', name: 'ticketRowById' },
  'tickets.search': { kind: 'query', name: 'ticketsSearch' },
  'tickets.listByProject': { kind: 'query', name: 'ticketsByProjectV2' },
  'tickets.listExports': { kind: 'query', name: 'ticketExportsForCurrentUser' },
  'tickets.listActivities': { kind: 'query', name: 'ticketActivities' },
  'tickets.listActivitiesForTickets': { kind: 'query', name: 'ticketActivitiesForTickets' },
  'tickets.listAssignments': { kind: 'query', name: 'ticketAssignmentsByTicketId' },
  'tickets.getWorkflow': { kind: 'query', name: 'getWorkflowForTicket' },
  'tickets.listAttachments': { kind: 'query', name: 'attachmentsByTicket' },
  'tickets.listEmails': { kind: 'query', name: 'getEmailsForTicket' },
  'tickets.getMailbox': { kind: 'query', name: 'myTicketMailboxV2' },
  'tickets.getRca': { kind: 'query', name: 'rcaByTicketId' },
  'tickets.listReleaseAttributions': { kind: 'query', name: 'releaseAttributionsByTicketId' },
  'tickets.listFieldValues': { kind: 'query', name: 'getTicketEntityMappingsByTicketId' },
  'tickets.listSubTickets': { kind: 'query', name: 'subTicketsForTicket' },
  'tickets.getSubTickets': { kind: 'query', name: 'subTicketsByIds' },
  'tickets.listSubTicketMappings': { kind: 'query', name: 'subTicketMappingsForTickets' },
  'tickets.createSubTicket': { kind: 'mutator', name: 'subTicket.create' },
  'tickets.updateSubTicket': { kind: 'mutator', name: 'subTicket.update' },
  'tickets.update': { kind: 'mutator', name: 'ticket.update' },
  'tickets.assign': { kind: 'mutator', name: 'ticket.updateAssignment' },
  'tickets.archive': { kind: 'mutator', name: 'ticket.archiveDeskTicket' },
  'tickets.setStageEta': { kind: 'mutator', name: 'ticketStageEta.update' },
  'tickets.listProjectTags': { kind: 'query', name: 'projectTagsByProjectId' },
  'tickets.addTag': { kind: 'mutator', name: 'ticketTagV2.create' },
  'tickets.removeTag': { kind: 'mutator', name: 'ticketTagV2.delete' },
  'tickets.addReference': { kind: 'mutator', name: 'ticketReference.create' },
  'tickets.updateReference': { kind: 'mutator', name: 'ticketReference.updateRelationType' },
  'tickets.removeReference': { kind: 'mutator', name: 'ticketReference.delete' },
  'tickets.listStageRequests': { kind: 'query', name: 'getTicketStageRequests' },
  'tickets.listOpenStageRequests': { kind: 'query', name: 'getOpenTicketStageRequestsByStageId' },
  'tickets.upsertStageRequest': { kind: 'mutator', name: 'ticketStageRequest.upsert' },
  'tickets.deleteStageRequests': { kind: 'mutator', name: 'ticketStageRequest.deleteByTicketId' },
  'tickets.transitionStage': { kind: 'mutator', name: 'nonLinear.transition' },
  'tickets.setMailboxState': { kind: 'mutator', name: 'ticketMailbox.setState' },
  'tickets.setMailboxStarred': { kind: 'mutator', name: 'ticketMailbox.setStarred' },
  'tickets.listSubTicketsByMapped': { kind: 'query', name: 'subTicketsByMappedTicketId' },
  'tickets.getSubTicketByMapped': { kind: 'query', name: 'subTicketByMappedTicketId' },

  // ----- userGroups -----
  'userGroups.list': { kind: 'query', name: 'getAllUserGroups' },
  'userGroups.getMany': { kind: 'query', name: 'getUserGroupsByIds' },
  'userGroups.get': { kind: 'query', name: 'getUserGroupById' },
  'userGroups.search': { kind: 'query', name: 'searchUserGroups' },
  'userGroups.listMembers': { kind: 'query', name: 'getUserGroupMembers' },
  'userGroups.listMembersForGroups': { kind: 'query', name: 'getUserGroupMembersByGroupIds' },
  'userGroups.listMine': { kind: 'query', name: 'getUserGroupMappingsByUserId' },
  'userGroups.listAssignmentStates': { kind: 'query', name: 'getUserAssignmentStates' },
  'userGroups.listAssignmentStatesForGroups': { kind: 'query', name: 'getUserAssignmentStatesByGroupIds' },
  'userGroups.listWorkloadMappings': { kind: 'query', name: 'getUserWorkloadMappings' },
  'userGroups.getAssignmentStateForUser': { kind: 'query', name: 'getUserAssignmentStatesByUserId' },
  'userGroups.listExpertise': { kind: 'query', name: 'getUserExpertiseMappings' },
  'userGroups.update': { kind: 'mutator', name: 'userGroup.update' },
  'userGroups.delete': { kind: 'mutator', name: 'userGroup.delete' },
  'userGroups.deactivate': { kind: 'mutator', name: 'userGroup.deactivate' },
  'userGroups.reactivate': { kind: 'mutator', name: 'userGroup.reactivate' },
  'userGroups.addUsers': { kind: 'mutator', name: 'userGroup.addUsers' },
  'userGroups.removeUsers': { kind: 'mutator', name: 'userGroup.removeUsers' },
  'userGroups.updateAssignmentConfig': { kind: 'mutator', name: 'assignmentConfig.batchUpdate' },
  'userGroups.toggleAutoRotation': { kind: 'mutator', name: 'assignmentConfig.toggleGroupAutoRotation' },

  // ----- users -----
  'users.list': { kind: 'query', name: 'getUsers' },
  'users.listBasic': { kind: 'query', name: 'getUsersV2' },
  'users.getProfiles': { kind: 'query', name: 'getUserProfilesByIds' },
  'users.getProfile': { kind: 'query', name: 'getUserProfile' },

  // ----- workspace -----
  'workspace.createLink': { kind: 'mutator', name: 'links.create' },
  'workspace.updateLink': { kind: 'mutator', name: 'links.update' },
  'workspace.deleteLink': { kind: 'mutator', name: 'links.delete' },
  'workspace.shareLink': { kind: 'mutator', name: 'links.shareWith' },
  'workspace.unshareLink': { kind: 'mutator', name: 'links.unshare' },
  'workspace.listRepos': { kind: 'query', name: 'getAllRepos' },
  'workspace.createRepo': { kind: 'mutator', name: 'repo.create' },
  'workspace.updateRepo': { kind: 'mutator', name: 'repo.update' },
  'workspace.deleteRepo': { kind: 'mutator', name: 'repo.delete' },
  'workspace.addRepoBranch': { kind: 'mutator', name: 'repo.addBranch' },
  'workspace.getSdlcChannel': { kind: 'query', name: 'getSdlcChannelById' },
  'workspace.listSdlcTracks': { kind: 'query', name: 'getSdlcTracks' },
  'workspace.createSdlcTrack': { kind: 'mutator', name: 'sdlc.createTrack' },
  'workspace.updateSdlcTrack': { kind: 'mutator', name: 'sdlc.updateTrack' },
  'workspace.listEmojis': { kind: 'query', name: 'getAllCustomEmojis' },
  'workspace.getEmoji': { kind: 'query', name: 'getCustomEmojiById' },
  'workspace.getEmojiByName': { kind: 'query', name: 'getCustomEmojiByName' },
  'workspace.listLookupValues': { kind: 'query', name: 'lookupValuesByType' },
  'workspace.listMerchants': { kind: 'query', name: 'getAllMerchants' },
  'workspace.listTicketTags': { kind: 'query', name: 'getAllTicketTags' },
  'workspace.listClassificationMappings': { kind: 'query', name: 'getClassificationMappings' },
  'workspace.createClassificationMapping': { kind: 'mutator', name: 'classificationMapping.create' },
  'workspace.updateClassificationMapping': { kind: 'mutator', name: 'classificationMapping.update' },
  'workspace.deleteClassificationMapping': { kind: 'mutator', name: 'classificationMapping.delete' },
};

/** Every operation id v1 serves. */
export function v1OperationIds(): string[] {
  return Object.keys(V1_MAPPER);
}

/** Resolve an operation id, or undefined when v1 does not define it. */
export function resolveV1Operation(op: string): V1Target | undefined {
  return Object.prototype.hasOwnProperty.call(V1_MAPPER, op) ? V1_MAPPER[op] : undefined;
}
