apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xyne-common.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "xyne-common.labels" . | nindent 4 }}
data:
  squid.conf: |
    {{- .Values.squid.config | trimSuffix "\n" | nindent 4 }}
  allow_hosts.txt: |
    {{- range .Values.squid.allowedHosts }}
    {{ . }}
    {{- end }}
