import type { Request, Response } from 'express';
import PDFDocument from 'pdfkit';
import { z } from 'zod';
import { logger } from '@/utils/logger';

const FlowRunExportRowSchema = z.object({
  sequence: z.number().int().positive(),
  mainTicketId: z.string().max(100),
  mainTicketTitle: z.string().max(500),
  mainTicketStatus: z.string().max(100),
  subTicketId: z.string().max(100),
  subTicketTitle: z.string().max(500),
  subTicketGroup: z.string().max(200),
  subTicketStatus: z.string().max(100),
  lastUpdatedBy: z.string().max(200),
  lastUpdated: z.string().max(100),
});

const FlowRunExportSchema = z.object({
  title: z.string().trim().min(1).max(200),
  rows: z.array(FlowRunExportRowSchema).min(1).max(10_000),
});

const columns = [
  { key: 'sequence', label: '#', width: 28 },
  { key: 'mainTicketId', label: 'Main Ticket ID', width: 68 },
  { key: 'mainTicketTitle', label: 'Main Ticket', width: 105 },
  { key: 'mainTicketStatus', label: 'Main Status', width: 60 },
  { key: 'subTicketId', label: 'Sub-ticket ID', width: 68 },
  { key: 'subTicketTitle', label: 'Sub-ticket / Stage', width: 110 },
  { key: 'subTicketGroup', label: 'Group', width: 75 },
  { key: 'subTicketStatus', label: 'Status', width: 58 },
  { key: 'lastUpdatedBy', label: 'Last Updated By', width: 85 },
  { key: 'lastUpdated', label: 'Last Updated', width: 120 },
] as const;

type FlowRunExportRow = z.infer<typeof FlowRunExportRowSchema>;

function createPdf(title: string, rows: FlowRunExportRow[]): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      layout: 'landscape',
      margins: { top: 32, right: 32, bottom: 32, left: 32 },
      info: { Title: title },
    });
    const chunks: Buffer[] = [];
    const tableLeft = 32;
    const tableWidth = columns.reduce((sum, column) => sum + column.width, 0);
    const pageBottom = 563;
    const cellPadding = 5;

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    let tableContentTop = 0;

    const drawHeader = (): void => {
      const y = doc.y;
      const height = 26;
      doc.rect(tableLeft, y, tableWidth, height).fill('#E9EDF8');
      let x = tableLeft;
      doc.font('Helvetica-Bold').fontSize(8).fillColor('#25304A');
      for (const column of columns) {
        const textHeight = doc.heightOfString(column.label, {
          width: column.width - cellPadding * 2,
          lineBreak: false,
        });
        doc.text(column.label, x + cellPadding, y + (height - textHeight) / 2, {
          width: column.width - cellPadding * 2,
          align: 'center',
          lineBreak: false,
        });
        doc.rect(x, y, column.width, height).strokeColor('#CBD2E1').lineWidth(0.5).stroke();
        x += column.width;
      }
      doc.y = y + height;
    };

    const startPage = (includeTitle: boolean): void => {
      if (includeTitle) {
        doc.font('Helvetica-Bold').fontSize(16).fillColor('#111827').text(title);
        doc.moveDown(0.6);
        doc
          .font('Helvetica-Oblique')
          .fontSize(9)
          .fillColor('#4B5563')
          .text(`Report generated by Xyne Space at ${new Date().toLocaleString('en-IN')}`);
        doc.moveDown(1.25);
      }
      drawHeader();
      tableContentTop = doc.y;
    };

    startPage(true);

    const mainColumnCount = 4;
    const detailLeft =
      tableLeft + columns.slice(0, mainColumnCount).reduce((sum, column) => sum + column.width, 0);
    const groupedRows: FlowRunExportRow[][] = [];
    for (const row of rows) {
      const group = groupedRows[groupedRows.length - 1];
      if (group?.[0]?.mainTicketId === row.mainTicketId) group.push(row);
      else groupedRows.push([row]);
    }

    doc.font('Helvetica').fontSize(8);
    for (const group of groupedRows) {
      const mainValues = columns
        .slice(0, mainColumnCount)
        .map(column => String(group[0][column.key]) || '-');
      const mainContentHeight = Math.max(
        ...mainValues.map((value, index) =>
          doc.heightOfString(value, {
            width: columns[index].width - cellPadding * 2,
          })
        )
      ) + cellPadding * 2;

      let groupRowIndex = 0;
      while (groupRowIndex < group.length) {
        const segmentStartY = doc.y;
        const segment: Array<{ values: string[]; height: number }> = [];
        let segmentHeight = 0;

        while (groupRowIndex < group.length) {
          const row = group[groupRowIndex];
          const values = columns.map(column => String(row[column.key]) || '-');
          const detailHeight = Math.max(
            24,
            ...values.slice(mainColumnCount).map((value, index) =>
              doc.heightOfString(value, {
                width: columns[index + mainColumnCount].width - cellPadding * 2,
              }) + cellPadding * 2
            )
          );
          const requestedRowHeight =
            segment.length === 0 ? Math.max(detailHeight, mainContentHeight) : detailHeight;
          const rowHeight = Math.min(requestedRowHeight, pageBottom - tableContentTop);
          if (segment.length > 0 && segmentStartY + segmentHeight + rowHeight > pageBottom) break;
          if (segment.length === 0 && segmentStartY + rowHeight > pageBottom) {
            doc.addPage();
            startPage(false);
            break;
          }
          segment.push({ values, height: rowHeight });
          segmentHeight += rowHeight;
          groupRowIndex += 1;
        }
        if (segment.length === 0) continue;

        let rowY = segmentStartY;
        for (const row of segment) {
          let x = detailLeft;
          row.values.slice(mainColumnCount).forEach((value, detailIndex) => {
            const column = columns[detailIndex + mainColumnCount];
            doc.font('Helvetica').fontSize(8);
            const textHeight = doc.heightOfString(value, {
              width: column.width - cellPadding * 2,
            });
            const availableTextHeight = Math.max(0, row.height - cellPadding * 2);
            const renderedTextHeight = Math.min(textHeight, availableTextHeight);
            doc
              .fillColor('#1F2937')
              .text(value, x + cellPadding, rowY + (row.height - renderedTextHeight) / 2, {
                width: column.width - cellPadding * 2,
                height: availableTextHeight,
                align: 'center',
                ellipsis: true,
              });
            doc.rect(x, rowY, column.width, row.height).strokeColor('#D8DEE9').lineWidth(0.5).stroke();
            x += column.width;
          });
          rowY += row.height;
        }

        let mainX = tableLeft;
        mainValues.forEach((value, index) => {
          const column = columns[index];
          const textHeight = doc.heightOfString(value, {
            width: column.width - cellPadding * 2,
          });
          const availableTextHeight = Math.max(0, segmentHeight - cellPadding * 2);
          const renderedTextHeight = Math.min(textHeight, availableTextHeight);
          doc
            .font('Helvetica')
            .fontSize(8)
            .fillColor('#1F2937')
            .text(
              value,
              mainX + cellPadding,
              segmentStartY + (segmentHeight - renderedTextHeight) / 2,
              {
                width: column.width - cellPadding * 2,
                height: availableTextHeight,
                align: 'center',
                ellipsis: true,
              }
            );
          doc
            .rect(mainX, segmentStartY, column.width, segmentHeight)
            .strokeColor('#D8DEE9')
            .lineWidth(0.5)
            .stroke();
          mainX += column.width;
        });
        doc.y = segmentStartY + segmentHeight;
      }
    }

    doc.end();
  });
}

export class FlowRunExportController {
  exportPdf = async (req: Request, res: Response): Promise<void> => {
    const parsed = FlowRunExportSchema.safeParse(req.body);
    if (!parsed.success) {
      res.status(400).json({ error: 'Invalid flow run export data' });
      return;
    }

    try {
      const pdf = await createPdf(parsed.data.title, parsed.data.rows);
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', 'attachment; filename="flow-runs.pdf"');
      res.send(pdf);
    } catch (error) {
      logger.error('[FlowRunExportController] Failed to create PDF', error);
      res.status(500).json({ error: 'Failed to create flow run PDF' });
    }
  };
}
