export {
  stateMachine,
  stateMachineActor,
  initialMetricsState,
  setupPresenceListeners,
  cleanupPresenceListeners,
  updateMyStatus,
  getHasOverlay,
  useHasOverlay,
  useOverlayEffect,
  getThreadTrackingSnapshot,
  setThreadLastRead,
  setThreadScroll,
} from '@xyne/shared/machines';

export type {
  DraftMessage,
  DraftMessages,
  User,
  Bookmarks,
  VisibleChannel,
  UserGroup,
  UserPermission,
  UserChannelStatus,
  Conversation,
  DraftMessageDB,
  DelayedMessageDB,
  PeriodMetrics,
  MetricsState,
  UnreadCounts,
  PresenceStatus,
  OnlineUser,
  UserStatusUpdatedEvent,
  ThreadTrackingEntry,
  ThreadTrackingMap,
} from '@xyne/shared/machines';
