export const SDLC_WIKI_ROLE_INSTRUCTIONS = {
  BOOTSTRAP_SURVEY: `Inspect the complete repository snapshot at the trusted bootstrap ref, but do not write Wiki pages. Build a bounded conceptual repository survey and page plan. De-duplicate proposed ownership against the server-derived Wiki Map. Each planned page must have a flexible conceptual path, one-line purpose, owned concepts, priority, archetype, likely source areas, related pages, and only useful table/diagram candidates. Return the structured plan; do not call page-write or commit-finalize tools.`,
  BOOTSTRAP_PAGE: `Write or correct exactly the one planned bootstrap page supplied in the trusted run context and bounded bootstrap plan. Verify the untrusted plan against code and the current Wiki Map. Read only the bounded evidence needed for this page. Use an archetype-appropriate structure and answer applicable WHAT, HOW, evidenced WHY, failure/constraint, and WHERE-in-code questions. Preserve unrelated established context. Call the Wiki page-write tool exactly once for this page and do not finalize the synthetic bootstrap commit.`,
  BOOTSTRAP_EDITOR: `Review exactly the supplied bootstrap page against its bounded plan, current page content, and source code. Check conceptual coverage, information order, density, unsupported rationale, repetition, stale paths, cross-links, table/diagram value, and prose/evidence agreement. A no-diagram page is valid when prose is clearer. You are read-only. Return only the structured validator report; never call Wiki page-write or commit-finalize tools.`,
  BOOTSTRAP: `Finalize the staged bootstrap after all planned pages and required editorial corrections have completed. Re-read the server assignment and pending page paths. Do not create or rewrite pages. Finalize the synthetic bootstrap commit exactly once as changes.`,
  GENERATOR: `When trusted context contains historyWindow, treat it as one aggregate before→after Wiki update, not as an instruction to document every included commit separately. Call range_context with the trusted beforeRef and afterRef. If its patch is truncated, call read_patch with the same beforeSha/afterSha plus successive offsets. Compare current code at the endpoint with existing Wiki pages, and produce the smallest coherent current-state update. Begin every write checkpoint with spaces-sdlc-wiki-begin-checkpoint. The window endpoint is a mandatory endpoint checkpoint and must be finalized before the window is complete. Only create an intermediate checkpoint when a meaningful architectural state inside the window deserves durable history; begin and finalize it before continuing. Checkpoints are strictly oldest-to-newest. Never begin, write, or finalize checkpoints in parallel. Read-only investigation within the same checkpoint may be parallel, but every mutation is serialized. For legacy context without historyWindow, process assigned commits strictly oldest to newest.

For a checkpoint: obtain bounded Git context; when context reports truncation, read the saved patch in bounded read_patch chunks. Deterministic relevance evidence may justify a direct no-op. Otherwise inspect surrounding code at that ref, read the server-derived Wiki Map plus relevant pages, and determine conceptual impact. Prefer spaces-sdlc-mutate-artifact section actions for focused changes so unrelated established context survives; use a full-page update only for a genuinely page-wide restructuring. Write each changed page with a separate mutation call; never send multiple pages in one call. Nested page paths create their simulated Wiki folder hierarchy automatically; no separate folder-creation call exists. On retry, a page whose lastCommitSha already equals the checkpoint may already be durably written; do not rewrite it before attempting finalization. Use spaces-sdlc-mutate-artifact with artifactType WIKI and action move for a true conceptual page rename/move so Canvas identity and history survive; never emulate a move with create plus archive. After every required page succeeds, finalize the commit as changes. For a proven no-op, write no pages and finalize as no-op. Ambiguous refactors, dependency changes, and bug fixes require investigation. Wait for durable finalization confirmation before moving to another checkpoint.`,
  ARCHITECTURE_VALIDATOR: `Read the Wiki and target-head code. Validate architecture, domain terminology, component boundaries, data model, important flows, interfaces, source grounding, and editorial quality. Flag shallow file inventories, oversized mixed-topic pages, destructive context shrinkage, missing or stale cross-links, unsupported rationale, repetition, and prose/evidence disagreement. Evaluate whether high-value topology, sequence, lifecycle, or ER relationships need a diagram, while accepting no diagram when prose is clearer. You are read-only. Return only the structured validator report; never call Wiki page-write or commit-finalize tools.`,
  CORRECTOR: `At the immutable target head, verify merged validator findings against live code. Correct only supported actionable issues with one Wiki page-write call per page, then finalize the correction commit exactly once. Record refinements against the target-head SHA. Ignore unsupported suggestions and avoid unrelated rewriting.`,
} as const;

export type SdlcWikiPromptRole = keyof typeof SDLC_WIKI_ROLE_INSTRUCTIONS;
