// TextEmoticonExtension.ts
// Converts ASCII text emoticons (e.g. ":)", ":(", ":D", ";)") to their
// corresponding Unicode emoji characters as the user types.
//
// The conversion fires when the user types a recognised emoticon followed by
// a space, or when the emoticon ends the paragraph (Enter / submit).  This
// avoids premature substitution while still in the middle of typing.

import { Extension } from '@tiptap/core';
import { Plugin, PluginKey } from 'prosemirror-state';
import { findEmojiByText, getTextEmoticons } from '../../../utils/emojiLookup';

const textEmoticonPluginKey = new PluginKey('textEmoticon');

/** Convert a unified code string like "1F603" or "2764-FE0F" to an emoji character */
function unifiedToEmoji(unified: string): string {
  return unified
    .split('-')
    .map(code => String.fromCodePoint(parseInt(code, 16)))
    .join('');
}

/**
 * Escape special regex characters so emoticons like ":)" or "</3" are matched
 * literally.
 */
function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Build a single InputRule regex that matches any known emoticon followed by a
 * whitespace character at the end of the current input-rule window.
 *
 * The regex uses a capturing group for the emoticon text so we can look it up.
 * Pattern:  (emoticon1|emoticon2|...)(\s)$
 */
function buildInputRuleRegex(emoticons: string[]): RegExp {
  if (emoticons.length === 0) {
    // Fallback: never matches
    return /(?!)/;
  }
  // Sort longest-first so more-specific patterns (":-)") match before ":)"
  const sorted = [...emoticons].sort((a, b) => b.length - a.length);
  const alternation = sorted.map(escapeRegex).join('|');
  return new RegExp(`(${alternation})(\\s)$`);
}

export const TextEmoticonExtension = Extension.create({
  name: 'textEmoticon',

  addProseMirrorPlugins() {
    const emoticons = getTextEmoticons();
    const regex = buildInputRuleRegex(emoticons);

    return [
      new Plugin({
        key: textEmoticonPluginKey,
        appendTransaction(transactions, _oldState, newState) {
          // Skip transactions generated by this plugin to prevent infinite loops
          if (transactions.some(tr => tr.getMeta(textEmoticonPluginKey))) return null;
          if (!transactions.some(tr => tr.docChanged)) return null;

          const { selection } = newState;
          if (!selection.empty) return null;

          const { $from } = selection;
          const textBefore = $from.parent.textContent.slice(0, $from.parentOffset);

          const match = regex.exec(textBefore);
          if (!match) return null;

          const emoticonText = match[1];
          const trailingWhitespace = match[2];
          if (!emoticonText) return null;

          const result = findEmojiByText(emoticonText);
          if (!result) return null;

          const emojiChar = unifiedToEmoji(result.unified);

          const end = $from.pos;
          const start = end - match[0].length;

          return newState.tr
            .insertText(emojiChar + trailingWhitespace, start, end)
            .setMeta(textEmoticonPluginKey, true);
        },
      }),
    ];
  },
});
