/**
 * The icons a track can wear: a short, themed set from the Xyne icons rather than
 * all ~980 of them, most of which (arrows, alarms, chevrons) say nothing about a
 * piece of work. Names are @xyne/icons ids.
 */
export const TRACK_ICON_GROUPS: ReadonlyArray<{ label: string; names: readonly string[] }> = [
  {
    label: 'Planning',
    names: [
      'rocket-ship',
      'focus-target',
      'flag',
      'trophy',
      'award-medal',
      'kanban-board',
      'list-check',
      'subtask',
      'graph-chart-gantt',
      'calendar-event',
      'hourglass',
      'megaphone-announcement-shout',
      'bulb-on',
      'star',
      'notebook',
      'plugin-addon-puzzle',
    ],
  },
  {
    label: 'Engineering',
    names: [
      'code',
      'curly-braces-code-default',
      'terminal-console-square',
      'bug',
      'api',
      'webhook',
      'database',
      'server',
      'cloud-default',
      'cube',
      'package-01',
      'git-branch',
      'git-pull-request',
      'automation',
      'script',
      'tools',
    ],
  },
  {
    label: 'Product & design',
    names: [
      'color-palette',
      'paint-brush',
      'frame',
      'pencil-edit',
      'grid-dashboard-01',
      'photo-image-default',
      'film',
      'laptop',
      'iphone',
      'monitor-01',
      'globe',
      'sparkle-ai-01',
    ],
  },
  {
    label: 'Business',
    names: [
      'credit-card',
      'wallet-default',
      'bank',
      'money-dollar-bag',
      'piggy-bank',
      'receipt-01',
      'invoice-01',
      'shopping-cart',
      'tag',
      'briefcase-job',
      'barchart-up',
      'graph-trend-line-upward',
      'piechart-01',
      'ticket-token',
    ],
  },
  {
    label: 'People & support',
    names: [
      'user-three',
      'community',
      'user-default',
      'bot',
      'chat-chatting',
      'envelope-default',
      'notification-bell-on',
      'phone-default',
      'support-heart',
      'contacts-book',
    ],
  },
  {
    label: 'Security & compliance',
    names: [
      'shield-check',
      'lock-close',
      'key-slant',
      'encrypted-lock',
      'eye-scan',
      'balance-scale-law',
    ],
  },
  {
    label: 'Places & more',
    names: [
      'home-default',
      'building-apartment-big',
      'earth-globe',
      'map-location',
      'truck-default',
      'graduation-hat',
      'heart',
      'gift-default',
      'coffee-cup-01',
      'lightning-thunder-electric-on',
      'sun',
      'crown-winner-king',
    ],
  },
];
