// Constants and utilities for workflow step types
// deterministic/parallel/agent/loops/conditional

export const STEP_TYPES = {
  DETERMINISTIC: 'deterministic',
  AGENT: "agent",
  CONDITIONAL: 'conditional',
  EXTERNAL: 'external',
  LOOPS: 'loops',
  PARALLEL: 'parallel',
} as const

export type StepType = typeof STEP_TYPES[keyof typeof STEP_TYPES]

// Step data interfaces for serialization
export interface StepInput<T = any> {
  type: StepType
  context?: T
}

export interface StepOutput<T = any> {
  completed: boolean
  result?: T
  completedAt: string
  error?: string
  metadata?: Record<string, any>
}

// Checkpoint-specific data
export interface CheckpointStepInput<T> extends StepInput<T> {
  type: typeof STEP_TYPES.DETERMINISTIC
  context: T
}

export interface CheckpointStepOutput<T> extends StepOutput<T> {
  result: T
}

// Conditional-specific data
export interface ConditionalStepInput<T> extends StepInput<T> {
  type: typeof STEP_TYPES.CONDITIONAL
  context: T
}

export interface ConditionalStepOutput extends StepOutput<boolean> {
  result: boolean
}

// External step-specific data
export interface ExternalStepInput<T> extends StepInput<T> {
  type: typeof STEP_TYPES.EXTERNAL
  context: T
  externalConfig: {
    type: 'user_approval' | 'webhook'
    subType?: string
    correlationData?: any
    metadata?: Record<string, any>
  }
}

export interface ExternalStepOutput<R = any> extends StepOutput<R> {
  externalData?: R
  awaitingExternal: boolean
}

// While loop-specific data
export interface WhileLoopStepInput<T> extends StepInput<T> {
  type: typeof STEP_TYPES.LOOPS
  context: T
  loopConfig: {
    maxIterations: number
    description?: string
  }
}

export interface WhileLoopStepOutput extends StepOutput {
  currentIteration: number
  status: 'running' | 'completed' | 'failed'
  iterationHistory?: Array<{
    iteration: number
    startedAt: string
    completedAt?: string
    status: string
  }>
}

// Parallel workflow-specific data
export interface ParallelWorkflowStepInput extends StepInput {
  type: typeof STEP_TYPES.PARALLEL
  parallelConfig: {
    mode: 'wait_for_all' | 'wait_for_first' | 'wait_for_majority' | 'wait_for_count'
    waitCount?: number
    timeout?: number
    failureMode: 'fail_fast' | 'fail_tolerant' | 'fail_threshold'
    failureThreshold?: number
    workflows: Array<{
      workflowType: string
      autoGeneratedId: string
      initialArgs: unknown[]
      priority: number
    }>
  }
}

export interface ParallelWorkflowStepOutput extends StepOutput {
  result: any  // Final merged result
  parallelResults: {
    completedWorkflows: string[]
    failedWorkflows: string[]
    runningWorkflows: string[]
    results: Record<string, any>
    status: 'running' | 'completed' | 'failed' | 'timeout'
    completedCount: number
    totalCount: number
  }
}

// Type guards
export function isStepType(value: string): value is StepType {
  return Object.values(STEP_TYPES).includes(value as StepType)
}

export function isCheckpointStep<T>(
  input: StepInput<T>
): input is CheckpointStepInput<T> {
  return input.type === STEP_TYPES.DETERMINISTIC
}

export function isConditionalStep<T>(
  input: StepInput<T>
): input is ConditionalStepInput<T> {
  return input.type === STEP_TYPES.CONDITIONAL
}

export function isExternalStep<T>(
  input: StepInput<T>
): input is ExternalStepInput<T> {
  return input.type === STEP_TYPES.EXTERNAL
}

export function isWhileLoopStep<T>(
  input: StepInput<T>
): input is WhileLoopStepInput<T> {
  return input.type === STEP_TYPES.LOOPS
}

export function isParallelWorkflowStep(
  input: StepInput
): input is ParallelWorkflowStepInput {
  return input.type === STEP_TYPES.PARALLEL
}

// Validation helpers
export function validateStepInput<T>(input: any): StepInput<T> {
  if (!input || typeof input !== 'object') {
    throw new Error('Step input must be an object')
  }

  if (!input.type || !isStepType(input.type)) {
    throw new Error(`Invalid step type: ${input.type}`)
  }

  return input as StepInput<T>
}

export function validateStepOutput<T>(output: any): StepOutput<T> {
  if (!output || typeof output !== 'object') {
    throw new Error('Step output must be an object')
  }

  if (typeof output.completed !== 'boolean') {
    throw new Error('Step output must have completed boolean field')
  }

  if (!output.completedAt || typeof output.completedAt !== 'string') {
    throw new Error('Step output must have completedAt timestamp')
  }

  return output as StepOutput<T>
}