port: 7880
rtc:
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: false

redis:
  address: redis:6379


keys:
  localdevkey: localdevsecret

logging:
  level: warn
  sample: false

room:
  auto_create: true
  empty_timeout: 120     
  departure_timeout: 10     
  max_participants: 100

turn:
  enabled: false

webhook:
  api_key: localdevkey
  urls:
    - http://host.docker.internal:3001/api/livekit/webhook