import {
  ACLAuditEventType,
  ACLAuditTargetType,
  AIProvisioningProvider,
  AIProvisioningStatus,
  AIProvisioningSubjectType,
  AccessType,
  ActivityClassification,
  ActivityClassificationJobType,
  ActivityType,
  AppIncomingWebhookAction,
  AppIncomingWebhookType,
  AppPermissionStatus,
  AppPermissionType,
  ApproverType,
  AttachmentEntityType,
  AttachmentUploadStatus,
  AttributionConfidence,
  AuthProvider,
  AutoDraftMode,
  AutoDraftStatus,
  BoardType,
  BookmarkEntityType,
  COEStatus,
  CalendarVisibility,
  CallOrigin,
  CallStatus,
  CallType,
  CanvasCommentThreadStatus,
  CanvasRole,
  CanvasVisibility,
  ChannelAddUserPolicy,
  ChannelFilterMode,
  ChannelRole,
  ChannelScopeType,
  ChannelSortOrder,
  ChannelType,
  ChannelVisibility,
  CollectionRole,
  CommandAccessibility,
  CommandType,
  ConversationParticipation,
  DashboardRole,
  DashboardVisibility,
  DefaultOutlet,
  DelayedMessageStatus,
  DeskType,
  DocType,
  EmailMergeMode,
  EmailType,
  EntityType,
  EntityUserAccess,
  ExternalEntityType,
  FormContextType,
  FormEntityType,
  FormFieldType,
  GuestEntity,
  IngestionStatus,
  InviteExperience,
  InvitationResponse,
  LinkVisibility,
  LookupType,
  MailboxState,
  MeetingStatus,
  MessageDirection,
  MessageType,
  NotificationDeliveryMethod,
  NotificationLevel,
  NotificationStatus,
  NotificationType,
  NudgeKind,
  NudgeState,
  NudgeType,
  OrgLLMServiceAccountCredentialStatus,
  OrgLLMServiceAccountProvider,
  OrgLLMServiceAccountPurpose,
  OrgRole,
  OrganizationDomainVerificationStatus,
  PRStatus,
  PRStatusEvent,
  Platform,
  ProjectType,
  QueryType,
  QueryVisualizationType,
  RCAStatus,
  RecapEntityType,
  RecordingStatus,
  RecordingType,
  RecurringCallSeriesStatus,
  ReenterMode,
  ReleaseEventType,
  ReleaseTrackingMode,
  RotationInterval,
  SEVERITY,
  SavedConfigContextType,
  SavedConfigEntityName,
  SavedConfigVisibility,
  SessionRecordingProcessStatus,
  SessionStatus,
  ShareableEntityType,
  Status,
  SurfaceAreaType,
  SurfaceLinkKind,
  TagMethod,
  TeamIntelligenceBatchStatus,
  TeamIntelligenceUserIngestionStatus,
  TelepresenceDeviceType,
  TelepresenceHealthStatus,
  TicketPriority,
  TicketReferenceRelation,
  TicketStageRequestStatus,
  TicketStatus,
  TicketStatusV2,
  UserPresenceStatus,
  UserResponsibility,
  UserStatus,
  UserType,
  VCSProviderType,
  VespaInsertionStatus,
  VespaOperationType,
  VisitSlaMode,
  WorkflowEventType,
  WorkflowExecutionMode,
  WorkflowMappingEntityType,
  WorkspaceJoinPolicy,
  WorkspaceJoinRequestStatus,
  WorkspaceRole,
  WorkspaceType,
} from '@xyne/shared';

export interface EnumTextField {
    prismaModel: string;
    field: string;
    values: readonly string[];
}

export const ENUM_TEXT_FIELDS: readonly EnumTextField[] = [
  { prismaModel: 'Ticket', field: 'status', values: Object.values(TicketStatus) },
  { prismaModel: 'Ticket', field: 'statusV2', values: Object.values(TicketStatusV2) },
  { prismaModel: 'Ticket', field: 'priority', values: Object.values(TicketPriority) },
  { prismaModel: 'TicketAssignment', field: 'userResponsibility', values: Object.values(UserResponsibility) },
  { prismaModel: 'TicketActivity', field: 'activityType', values: Object.values(ActivityType) },
  { prismaModel: 'TicketEntityMapping', field: 'entityType', values: Object.values(EntityType) },
  { prismaModel: 'TicketReferenceMapping', field: 'relationType', values: Object.values(TicketReferenceRelation) },
  { prismaModel: 'Workflow', field: 'eventType', values: Object.values(WorkflowEventType) },
  { prismaModel: 'WorkflowExecution', field: 'mode', values: Object.values(WorkflowExecutionMode) },
  { prismaModel: 'WorkflowMapping', field: 'entityType', values: Object.values(WorkflowMappingEntityType) },
  { prismaModel: 'UserGroup', field: 'rotationInterval', values: Object.values(RotationInterval) },
  { prismaModel: 'UserSession', field: 'status', values: Object.values(SessionStatus) },
  { prismaModel: 'User', field: 'authProvider', values: Object.values(AuthProvider) },
  { prismaModel: 'User', field: 'status', values: Object.values(UserStatus) },
  { prismaModel: 'User', field: 'userType', values: Object.values(UserType) },
  { prismaModel: 'User', field: 'role', values: Object.values(WorkspaceRole) },
  { prismaModel: 'User', field: 'calendarVisibility', values: Object.values(CalendarVisibility) },
  { prismaModel: 'UserPreference', field: 'channelSortOrder', values: Object.values(ChannelSortOrder) },
  { prismaModel: 'UserPreference', field: 'starredSortOrder', values: Object.values(ChannelSortOrder) },
  { prismaModel: 'UserPreference', field: 'dmSortOrder', values: Object.values(ChannelSortOrder) },
  { prismaModel: 'UserPreference', field: 'channelFilterMode', values: Object.values(ChannelFilterMode) },
  { prismaModel: 'UserPreference', field: 'starredFilterMode', values: Object.values(ChannelFilterMode) },
  { prismaModel: 'UserPreference', field: 'dmFilterMode', values: Object.values(ChannelFilterMode) },
  { prismaModel: 'UserPreference', field: 'globalDesktopNotificationLevel', values: Object.values(NotificationLevel) },
  { prismaModel: 'UserPreference', field: 'globalMobileNotificationLevel', values: Object.values(NotificationLevel) },
  { prismaModel: 'UserGroupMapping', field: 'responsibility', values: Object.values(UserResponsibility) },
  { prismaModel: 'UserPresence', field: 'status', values: Object.values(UserPresenceStatus) },
  { prismaModel: 'ResourceAccess', field: 'accessType', values: Object.values(AccessType) },
  { prismaModel: 'ACLAuditLog', field: 'eventType', values: Object.values(ACLAuditEventType) },
  { prismaModel: 'ACLAuditLog', field: 'targetType', values: Object.values(ACLAuditTargetType) },
  { prismaModel: 'PullRequests', field: 'status', values: Object.values(PRStatus) },
  { prismaModel: 'TeamIntelligenceIngestionBatchV2', field: 'status', values: Object.values(TeamIntelligenceBatchStatus) },
  { prismaModel: 'TeamIntelligenceUserIngestionV2', field: 'processingStatus', values: Object.values(TeamIntelligenceUserIngestionStatus) },
  { prismaModel: 'TeamIntelligenceTeamSummaryV2', field: 'status', values: Object.values(TeamIntelligenceBatchStatus) },
  { prismaModel: 'TeamIntelligenceOrgSummaryV2', field: 'status', values: Object.values(TeamIntelligenceBatchStatus) },
  { prismaModel: 'Organization', field: 'status', values: Object.values(Status) },
  { prismaModel: 'OrgMember', field: 'role', values: Object.values(OrgRole) },
  { prismaModel: 'WorkspaceOrganization', field: 'role', values: Object.values(WorkspaceRole) },
  { prismaModel: 'Workspace', field: 'status', values: Object.values(Status) },
  { prismaModel: 'Invitation', field: 'role', values: Object.values(WorkspaceRole) },
  { prismaModel: 'Project', field: 'type', values: Object.values(ProjectType) },
  { prismaModel: 'Board', field: 'boardType', values: Object.values(BoardType) },
  { prismaModel: 'Board', field: 'vcsProvider', values: Object.values(VCSProviderType) },
  { prismaModel: 'Board', field: 'releaseTrackingMode', values: Object.values(ReleaseTrackingMode) },
  { prismaModel: 'Stage', field: 'defaultTicketStatus', values: Object.values(TicketStatus) },
  { prismaModel: 'Stage', field: 'defaultTicketStatusV2', values: Object.values(TicketStatusV2) },
  { prismaModel: 'StagePRStatusMapping', field: 'prStatus', values: Object.values(PRStatusEvent) },
  { prismaModel: 'StageTransition', field: 'visitSlaMode', values: Object.values(VisitSlaMode) },
  { prismaModel: 'StageTransition', field: 'onReenter', values: Object.values(ReenterMode) },
  { prismaModel: 'Channel', field: 'type', values: Object.values(ChannelType) },
  { prismaModel: 'Channel', field: 'scopeType', values: Object.values(ChannelScopeType) },
  { prismaModel: 'Channel', field: 'visibility', values: Object.values(ChannelVisibility) },
  { prismaModel: 'Channel', field: 'addUserPolicy', values: Object.values(ChannelAddUserPolicy) },
  { prismaModel: 'ChannelStats', field: 'addUserPolicy', values: Object.values(ChannelAddUserPolicy) },
  { prismaModel: 'ChannelParticipant', field: 'role', values: Object.values(ChannelRole) },
  { prismaModel: 'ChannelUserStatus', field: 'desktopNotificationLevel', values: Object.values(NotificationLevel) },
  { prismaModel: 'ChannelUserStatus', field: 'mobileNotificationLevel', values: Object.values(NotificationLevel) },
  { prismaModel: 'ChannelSection', field: 'sortOrder', values: Object.values(ChannelSortOrder) },
  { prismaModel: 'ChannelSection', field: 'filterMode', values: Object.values(ChannelFilterMode) },
  { prismaModel: 'ConversationParticipant', field: 'participationType', values: Object.values(ConversationParticipation) },
  { prismaModel: 'Email', field: 'type', values: Object.values(EmailType) },
  { prismaModel: 'EmailDraft', field: 'autoDraftStatus', values: Object.values(AutoDraftStatus) },
  { prismaModel: 'TicketUserMailbox', field: 'state', values: Object.values(MailboxState) },
  { prismaModel: 'EmailChannelPreference', field: 'emailMergeMode', values: Object.values(EmailMergeMode) },
  { prismaModel: 'EmailChannelPreference', field: 'autoDraftMode', values: Object.values(AutoDraftMode) },
  { prismaModel: 'EmailChannelPreference', field: 'deskType', values: Object.values(DeskType) },
  { prismaModel: 'BoardSlaPolicy', field: 'priority', values: Object.values(TicketPriority) },
  { prismaModel: 'Message', field: 'msgType', values: Object.values(MessageType) },
  { prismaModel: 'MessageAttachment', field: 'entityType', values: Object.values(AttachmentEntityType) },
  { prismaModel: 'MessageAttachment', field: 'uploadStatus', values: Object.values(AttachmentUploadStatus) },
  { prismaModel: 'Activity', field: 'classification', values: Object.values(ActivityClassification) },
  { prismaModel: 'Activity', field: 'classificationJobType', values: Object.values(ActivityClassificationJobType) },
  { prismaModel: 'ExternalMessage', field: 'entityType', values: Object.values(ExternalEntityType) },
  { prismaModel: 'ExternalMessage', field: 'direction', values: Object.values(MessageDirection) },
  { prismaModel: 'ProactiveNudge', field: 'type', values: Object.values(NudgeType) },
  { prismaModel: 'SurfaceNudge', field: 'nudgeKind', values: Object.values(NudgeKind) },
  { prismaModel: 'SurfaceNudge', field: 'state', values: Object.values(NudgeState) },
  { prismaModel: 'Notification', field: 'type', values: Object.values(NotificationType) },
  { prismaModel: 'Notification', field: 'status', values: Object.values(NotificationStatus) },
  { prismaModel: 'Notification', field: 'deliveryMethods', values: Object.values(NotificationDeliveryMethod) },
  { prismaModel: 'NotificationPreference', field: 'notificationType', values: Object.values(NotificationType) },
  { prismaModel: 'Call', field: 'callType', values: Object.values(CallType) },
  { prismaModel: 'Call', field: 'callOrigin', values: Object.values(CallOrigin) },
  { prismaModel: 'Call', field: 'status', values: Object.values(CallStatus) },
  { prismaModel: 'CallParticipant', field: 'response', values: Object.values(InvitationResponse) },
  { prismaModel: 'CallParticipant', field: 'meetingStatus', values: Object.values(MeetingStatus) },
  { prismaModel: 'CallRecording', field: 'recordingType', values: Object.values(RecordingType) },
  { prismaModel: 'CallRecording', field: 'status', values: Object.values(RecordingStatus) },
  { prismaModel: 'RecurringCallSeries', field: 'status', values: Object.values(RecurringCallSeriesStatus) },
  { prismaModel: 'RecurringCallParticipant', field: 'response', values: Object.values(InvitationResponse) },
  { prismaModel: 'RecurringCallParticipant', field: 'meetingStatus', values: Object.values(MeetingStatus) },
  { prismaModel: 'Canvas', field: 'visibility', values: Object.values(CanvasVisibility) },
  { prismaModel: 'Canvas', field: 'docType', values: Object.values(DocType) },
  { prismaModel: 'CanvasParticipant', field: 'role', values: Object.values(CanvasRole) },
  { prismaModel: 'Bookmark', field: 'entityType', values: Object.values(BookmarkEntityType) },
  { prismaModel: 'Link', field: 'visibility', values: Object.values(LinkVisibility) },
  { prismaModel: 'VespaInsertionLogs', field: 'type', values: Object.values(VespaOperationType) },
  { prismaModel: 'VespaInsertionLogs', field: 'status', values: Object.values(VespaInsertionStatus) },
  { prismaModel: 'LookupValue', field: 'type', values: Object.values(LookupType) },
  { prismaModel: 'Form', field: 'entityType', values: Object.values(FormEntityType) },
  { prismaModel: 'Form', field: 'contextType', values: Object.values(FormContextType) },
  { prismaModel: 'FormContextMapping', field: 'contextType', values: Object.values(FormContextType) },
  { prismaModel: 'FormContextMapping', field: 'entityType', values: Object.values(FormEntityType) },
  { prismaModel: 'GlobalField', field: 'fieldType', values: Object.values(FormFieldType) },
  { prismaModel: 'FormFields', field: 'fieldType', values: Object.values(FormFieldType) },
  { prismaModel: 'Query', field: 'entityType', values: Object.values(FormEntityType) },
  { prismaModel: 'Query', field: 'visualType', values: Object.values(QueryVisualizationType) },
  { prismaModel: 'UserActivityEvent', field: 'platform', values: Object.values(Platform) },
  { prismaModel: 'CollectionItem', field: 'ingestionStatus', values: Object.values(IngestionStatus) },
  { prismaModel: 'CollectionPermission', field: 'role', values: Object.values(CollectionRole) },
  { prismaModel: 'StageApprovers', field: 'approverType', values: Object.values(ApproverType) },
  { prismaModel: 'ReleaseEvent', field: 'eventType', values: Object.values(ReleaseEventType) },
  { prismaModel: 'TicketStageRequest', field: 'status', values: Object.values(TicketStageRequestStatus) },
  { prismaModel: 'RCA', field: 'severity', values: Object.values(SEVERITY) },
  { prismaModel: 'RCA', field: 'status', values: Object.values(RCAStatus) },
  { prismaModel: 'COE', field: 'status', values: Object.values(COEStatus) },
  { prismaModel: 'ReleaseAttribution', field: 'confidence', values: Object.values(AttributionConfidence) },
  { prismaModel: 'Recap', field: 'entityType', values: Object.values(RecapEntityType) },
  { prismaModel: 'SessionRecordingFile', field: 'status', values: Object.values(SessionRecordingProcessStatus) },
  { prismaModel: 'SurfaceLink', field: 'sourceType', values: Object.values(SurfaceAreaType) },
  { prismaModel: 'SurfaceLink', field: 'targetType', values: Object.values(SurfaceAreaType) },
  { prismaModel: 'SurfaceLink', field: 'linkKind', values: Object.values(SurfaceLinkKind) },
  { prismaModel: 'InstalledAppCommand', field: 'commandType', values: Object.values(CommandType) },
  { prismaModel: 'InstalledAppCommand', field: 'commandAccessibility', values: Object.values(CommandAccessibility) },
  { prismaModel: 'AppIncomingWebhook', field: 'type', values: Object.values(AppIncomingWebhookType) },
  { prismaModel: 'AppIncomingWebhook', field: 'action', values: Object.values(AppIncomingWebhookAction) },
  { prismaModel: 'AppCommand', field: 'commandType', values: Object.values(CommandType) },
  { prismaModel: 'AppCommand', field: 'commandAccessibility', values: Object.values(CommandAccessibility) },
  { prismaModel: 'SavedUserConfiguration', field: 'contextType', values: Object.values(SavedConfigContextType) },
  { prismaModel: 'SavedUserConfiguration', field: 'visibility', values: Object.values(SavedConfigVisibility) },
  { prismaModel: 'SavedUserConfigurationValue', field: 'entityName', values: Object.values(SavedConfigEntityName) },
  { prismaModel: 'DelayedMessage', field: 'status', values: Object.values(DelayedMessageStatus) },
  { prismaModel: 'DynamicDashboard', field: 'visibility', values: Object.values(DashboardVisibility) },
  { prismaModel: 'DashboardParticipant', field: 'role', values: Object.values(DashboardRole) },
  { prismaModel: 'DynamicDashboardQuery', field: 'queryType', values: Object.values(QueryType) },
  { prismaModel: 'DynamicDashboardQuery', field: 'entityType', values: Object.values(FormEntityType) },
  { prismaModel: 'DynamicDashboardQuery', field: 'visualType', values: Object.values(QueryVisualizationType) },
  { prismaModel: 'AvailableAppPermission', field: 'type', values: Object.values(AppPermissionType) },
  { prismaModel: 'InstalledAppPermission', field: 'status', values: Object.values(AppPermissionStatus) },
  { prismaModel: 'Tag', field: 'method', values: Object.values(TagMethod) },
  { prismaModel: 'TelepresenceHealthView', field: 'deviceType', values: Object.values(TelepresenceDeviceType) },
  { prismaModel: 'TelepresenceHealthView', field: 'status', values: Object.values(TelepresenceHealthStatus) },
  { prismaModel: 'TelepresenceHealthLog', field: 'deviceType', values: Object.values(TelepresenceDeviceType) },
  { prismaModel: 'TelepresenceHealthLog', field: 'status', values: Object.values(TelepresenceHealthStatus) },
  { prismaModel: 'EntityAccess', field: 'shareableEntityType', values: Object.values(ShareableEntityType) },
  { prismaModel: 'EntityAccess', field: 'entityUserAccess', values: Object.values(EntityUserAccess) },
  { prismaModel: 'SummaryTemplate', field: 'defaultOutlet', values: Object.values(DefaultOutlet) },
  { prismaModel: 'Workspace', field: 'workspaceType', values: Object.values(WorkspaceType) },
  { prismaModel: 'Workspace', field: 'joinPolicy', values: Object.values(WorkspaceJoinPolicy) },
  { prismaModel: 'Workspace', field: 'inviteExperience', values: Object.values(InviteExperience) },
  { prismaModel: 'WorkspaceJoinRequest', field: 'status', values: Object.values(WorkspaceJoinRequestStatus) },
  { prismaModel: 'AiProvisioningStatus', field: 'subjectType', values: Object.values(AIProvisioningSubjectType) },
  { prismaModel: 'AiProvisioningStatus', field: 'provider', values: Object.values(AIProvisioningProvider) },
  { prismaModel: 'AiProvisioningStatus', field: 'status', values: Object.values(AIProvisioningStatus) },
  { prismaModel: 'OrgLLMServiceAccountCredential', field: 'provider', values: Object.values(OrgLLMServiceAccountProvider) },
  { prismaModel: 'OrgLLMServiceAccountCredential', field: 'purpose', values: Object.values(OrgLLMServiceAccountPurpose) },
  { prismaModel: 'OrgLLMServiceAccountCredential', field: 'status', values: Object.values(OrgLLMServiceAccountCredentialStatus) },
  { prismaModel: 'OrganizationDomain', field: 'verificationStatus', values: Object.values(OrganizationDomainVerificationStatus) },
  { prismaModel: 'CanvasCommentThread', field: 'status', values: Object.values(CanvasCommentThreadStatus) },
  { prismaModel: 'Invitation', field: 'entityType', values: Object.values(GuestEntity) },
  { prismaModel: 'GuestAccess', field: 'accessibleEntityType', values: Object.values(GuestEntity) },
];
export function assertEnumTextValue(
  value: unknown,
  allowed: readonly string[],
  label: string,
): void {
  const resolved =
    value && typeof value === 'object' && 'set' in (value as object)
      ? (value as { set: unknown }).set
      : value;

  if (resolved === undefined || resolved === null) return;
  if (Array.isArray(resolved)) {
    for (const item of resolved) assertEnumTextValue(item, allowed, label);
    return;
  }

  if (typeof resolved !== 'string' || !allowed.includes(resolved)) {
    throw new Error(
      `Invalid value for ${label}: ${JSON.stringify(resolved)}. Allowed values: ${allowed.join(', ')}`,
    );
  }
}

const FIELDS_BY_MODEL = new Map<string, EnumTextField[]>();
for (const ec of ENUM_TEXT_FIELDS) {
  const forModel = FIELDS_BY_MODEL.get(ec.prismaModel) ?? [];
  forModel.push(ec);
  FIELDS_BY_MODEL.set(ec.prismaModel, forModel);
}

export function assertEnumTextForModel(
  model: string,
  data: Record<string, unknown> | null | undefined,
): void {
  if (!data) return;
  const defs = FIELDS_BY_MODEL.get(model);
  if (!defs) return;
  for (const ec of defs) {
    assertEnumTextValue(data[ec.field], ec.values, `${model}.${ec.field}`);
  }
}
