// Framework imports for AgentConfig, Message, and ConversationResult types
import type { AgentConfig, Message, ConversationResult } from '@framework'
import type { WorkflowDefinition } from './registry/workflowRegistry'
import type { WorkflowType } from './types/workflow-enums'

// Base context type - all workflow contexts should extend this
export type BaseWorkflowContext = Record<string, unknown>

// Type constraint for TypeScript enums (string or number enums)
// This ensures only actual TypeScript enums can be used, not plain objects
export type AnyEnum = {
  readonly [key: string]: string
}

// Context with agent result (used internally by agentic checkpoints)
export interface ContextWithAgentResult extends BaseWorkflowContext {
  agentResult?: ConversationResult
}

// Simplified workflow state - identifiers + readonly context
export type WorkflowState<TContext extends BaseWorkflowContext = BaseWorkflowContext> = {
  readonly workflowId: string
  readonly workflowExecutionId: string
  readonly context: Readonly<TContext>
  readonly parentExecutionId?: string  // If set, this is a child workflow
}

// Type-safe checkpoint handler using rest parameters
export type CheckpointHandler<R, Args extends unknown[]> = (...args: Args) => Promise<R>
export type ConditionalHandler<Args extends unknown[]> = (...args: Args) => Promise<boolean>

// External step metadata for dashboard display and user guidance
export interface ExternalStepMetadata {
  type: 'user_approval' | 'webhook' | 'api_callback'
  title?: string
  /**
   * Optional response schema for the external step.
   * If provided, this schema will be used as-is.
   * If not provided, it will be automatically generated by the TypeScript transformer
   * based on the type R in createExternalStep<R, Args, E>().
   */
  responseSchema?: Record<string, any>
}

// Result type for external step requestHandler to signal immediate errors
// When success=true, workflow waits for webhook response
// When success=false, responseProcessor is called immediately with the error data
export type ExternalStepRequestResult<E = never> =
  | { success: true }
  | { success: false; data: E }

// Helper functions for creating ExternalStepRequestResult
export const RequestHandlerSuccess = (): ExternalStepRequestResult<never> => ({ success: true })
export const RequestHandlerError = <E>(data: E): ExternalStepRequestResult<E> => ({ success: false, data })

// Type-safe external step handlers using rest parameters
export type ExternalStepHandler<Args extends unknown[], E = never> = (
  workflowExecutionId: string,
  workflowStepId: string,
  ...args: Args
) => Promise<ExternalStepRequestResult<E>>


export type ExternalResponseProcessor<R, E = never> = (
  rawResponse: string,
  errorData?: E
) => Promise<R>

// Loop control enum for while loops
export enum LoopControl {
  CONTINUE = 'continue',
  BREAK = 'break'
}

// While loop types for iteration-based loops
export type WhileLoopBodyFunction<TContext extends BaseWorkflowContext = BaseWorkflowContext, TEnum extends AnyEnum = AnyEnum> = (
  iteration: number,
  engine: WorkflowEngine<TContext, TEnum>,
  parentStepId?: string
) => Promise<LoopControl>

export type WhileLoopConfig<TContext extends BaseWorkflowContext = BaseWorkflowContext, TEnum extends AnyEnum = AnyEnum> = {
  maxIterations: number
  body: WhileLoopBodyFunction<TContext, TEnum>
  // Removed breakCondition - no longer needed!
}

export enum ParallelExecutionMode {
  WAIT_FOR_ALL = 'wait_for_all'           // All tasks must complete
}

// Child workflow result from parallel execution
export type ChildWorkflowResult<TResult> = {
  executionId: string
  workflowType: string
  result: TResult
  status: 'completed' | 'failed' | 'cancelled'
}

// Type-safe configuration for parallel workflow execution
export type ParallelWorkflowConfig<
  Tasks extends readonly ValidatedWorkflowTask[] = readonly ValidatedWorkflowTask[],
  TFinalResult = void
> = {
  workflows: Tasks
  // Called after EACH child completes - return BREAK to cancel remaining workflows
  onExecutionComplete: (result: WorkflowResultUnion<Tasks>) => Promise<LoopControl>
  // Optional: Called after all complete (or after BREAK cancels remaining)
  onAllCompleted?: (results: WorkflowResultTuple<Tasks>) => Promise<TFinalResult>
}

export type ExternalStepConfig<R, Args extends unknown[], E = never> = {
  type: 'user_approval' | 'webhook'
  requestHandler: ExternalStepHandler<Args, E>  // Sends the request, returns Result
  responseProcessor: ExternalResponseProcessor<R, E>  // Processes response or error data into output
}

// Agent config versions type - maps agent names to version numbers
export type AgentConfigVersions = {
  [agentName: string]: number
}

// Custom configuration that can be passed to workflows
export interface WorkflowCustomConfig {
  agentConfigVersions?: AgentConfigVersions;
  // Add other workflow-specific configuration options here as needed
  [key: string]: unknown;
}

export type PrLinkGenerator = (params: { 
  commitHash: string
  baseBranch: string
  repository: string
}) => string

// Framework-based agentic checkpoint config
export type ExecutorType = 'xyne-code' | 'opencode'

export type AgenticCheckpointConfig = {
  executorType?: ExecutorType
  conversationContext?: {
    messages?: readonly Message[]  // Framework Message type
    initialUserMessage?: string
    systemPrompt?: string
  }
  repoInfo: {
    repoUrl: string
    repoBranch?: string
    baseBranch?: string
    checkoutCommit?: string
    repository?: string
    getCommitMessage?: (raw_commit_message: string) => string
    getPrLink?: PrLinkGenerator
    earlyPRCreation?: boolean  // Feature flag for early PR creation (default: true)
    // Continuation-specific fields (set by agent-executor during continuation)
    continuationCommitHash?: string  // Commit to checkout for continuation
    existingPrLink?: string          // Existing PR to update (not create new)
    /** Optional hook called after repo is cloned, before agent execution. Use for project-specific setup like npm install */
    postCloneSetup?: (repoPath: string, repoName: string) => Promise<void>
  }
  agentConfigVersions?: AgentConfigVersions
  /** When true, captures learnings from the checkpoint for the knowledge base */
  captureKnowledge?: boolean
  /** Override the agent's default maxTurns execution limit */
  maxTurns?: number
}

// Continuation override for resuming agentic steps with user input
// Used when rerunning an agentic step with additional context from user
export type AgenticContinuationOverride = {
  continuationUserMessage: string      // User's message to append to conversation
  sourceChildExecutionId: string       // Original child execution to get history from
}

// Full config with agentConfig for internal use
export type FullAgenticCheckpointConfig = AgenticCheckpointConfig & {
  agentConfig: AgentConfig
}

export interface GitDiffFile {
  oldPath: string
  newPath: string
  type: 'add' | 'delete' | 'modify' | 'rename'
  hunks: Array<{
    oldStart: number
    oldLines: number
    newStart: number
    newLines: number
    content: string
  }>
}

export interface GitDiffStats {
  additions: number
  deletions: number
  files: number
}

export interface WorkflowPreview {
  type: 'loadUrlWithUserAgent'
  userAgent: string
  url: string
}

export interface GitInfo {
  branch: string
  commitHash?: string
  baseCommitHash?: string  // Commit hash before agent started making changes (for accurate diff)
  repoUrl?: string
  pullRequestUrl?: string,
  hasCommits?: boolean
  workingDirectory?: string  // Directory where agentic framework performed operations
  pr_link?: string
  // Cached git diff data (computed before repo cleanup)
  gitDiff?: GitDiffFile[]
  diffStats?: GitDiffStats
  // Preview configuration for live preview in dashboard
  preview?: WorkflowPreview
  // Multi-repository support for unified workspace workflows
  multiRepoResults?: {
    [repoName: string]: {
      branch: string
      commitHash: string
      repoUrl: string
      success: boolean
      pullRequestUrl?: string
      pr_link?: string
      error?: string // Error message if the repository operation failed
    }
  }
}

export interface AgenticCheckpointResult {
  result: ConversationResult
  gitInfo: GitInfo
}

export interface WorkflowEngine<
  TContext extends BaseWorkflowContext,
  TEnum extends AnyEnum
> {
  // Get readonly context
  getContext(): Readonly<TContext>

  createCheckpoint<R, Args extends unknown[]>(
    id: TEnum[keyof TEnum],
    handler: CheckpointHandler<R, Args>,
    ...args: Args
  ): Promise<R>
  createAgenticCheckpoint(
    id: TEnum[keyof TEnum],
    agentName: string,
    config: AgenticCheckpointConfig,
    parentStepId?: string
  ): Promise<AgenticCheckpointResult>
  createConditionalStep<Args extends unknown[]>(
    id: TEnum[keyof TEnum],
    condition: ConditionalHandler<Args>,
    ...args: Args
  ): Promise<boolean>
  createExternalStep<R, Args extends unknown[], E = never>(
    id: TEnum[keyof TEnum],
    metadata: ExternalStepMetadata,
    requestHandler: ExternalStepHandler<Args, E>,
    responseProcessor: ExternalResponseProcessor<R, E>,
    ...args: Args
  ): Promise<R>
  createWhileLoop(
    id: TEnum[keyof TEnum],
    maxIterations: number,
    body: WhileLoopBodyFunction<TContext, TEnum>,
    parentStepId?: string
  ): Promise<void>
  createParallelWorkflows<
    const Tasks extends readonly ValidatedWorkflowTask[],
    TFinalResult = void
  >(
    id: TEnum[keyof TEnum],
    config: ParallelWorkflowConfig<Tasks, TFinalResult>,
    parentStepId?: string
  ): Promise<TFinalResult>
  getCurrentState(): WorkflowState<TContext>
  getWorkflowId(): string
  getWorkflowExecutionId(): string
  // Get accumulated agentic checkpoint results for consolidated knowledge generation
  getPendingAgenticResults(): Array<{
    checkpointId: string
    result: ConversationResult
    gitInfo: GitInfo
  }>
}

// Simple execution state for tracking
export type WorkflowExecutionState<T> = {
  workflowId: string
  context: T
  createdAt: Date
  updatedAt: Date
}

// ============================================================================
// TYPE-SAFE PARALLEL WORKFLOWS - TYPE REGISTRY AND INFERENCE UTILITIES
// ============================================================================

/**
 * Type utilities to extract context and output types from WorkflowDefinition
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type ExtractContextFromDefinition<T> = T extends WorkflowDefinition<infer Context, infer _Output, infer _Enum, infer _PreExecute>
  ? Context
  : never

// eslint-disable-next-line @typescript-eslint/no-unused-vars
type ExtractOutputFromDefinition<T> = T extends WorkflowDefinition<infer _Context, infer Output, infer _Enum, infer _PreExecute>
  ? Output
  : never

/**
 * Workflow Type Registry - Auto-generated from WORKFLOW_DEFINITIONS
 * Maps each WorkflowType to its context and output types
 */
export type WorkflowTypeRegistry = {
  [K in WorkflowType]: {
    context: ExtractContextFromDefinition<(typeof import('./definitions'))['WORKFLOW_DEFINITIONS'][K]>
    output: ExtractOutputFromDefinition<(typeof import('./definitions'))['WORKFLOW_DEFINITIONS'][K]>
  }
}

/**
 * Validated workflow task - ensures initialContext matches the workflow type
 * This is a discriminated union of all possible valid workflow tasks
 */
export type ValidatedWorkflowTask = {
  [K in WorkflowType]: {
    workflowType: K
    initialContext: WorkflowTypeRegistry[K]['context']
  }
}[WorkflowType]

/**
 * Discriminated union type for onExecutionComplete callback
 * Allows type narrowing based on workflowType discriminator
 */
export type WorkflowResultUnion<Tasks extends readonly ValidatedWorkflowTask[]> = {
  [K in keyof Tasks]: Tasks[K] extends { workflowType: infer Type extends WorkflowType }
    ? ChildWorkflowResult<WorkflowTypeRegistry[Type]['output']> & { workflowType: Type }
    : never
}[number]

/**
 * Tuple type for onAllCompleted callback
 * Provides exact types for each position in the results array
 */
export type WorkflowResultTuple<Tasks extends readonly ValidatedWorkflowTask[]> = {
  [K in keyof Tasks]: Tasks[K] extends { workflowType: infer Type extends WorkflowType }
    ? ChildWorkflowResult<WorkflowTypeRegistry[Type]['output']>
    : never
}
