// Markdown summary generator using agentic framework

import { Agent, type AgentConfig, createUserMessage, type Message } from '@framework'
import { LogLevel } from '@framework'
import {logger} from '@/utils/logger';

type CheckpointData = Record<string, unknown>

/**
 * Generates a markdown summary for a checkpoint using an AI agent
 * @param checkpointName - Name of the checkpoint
 * @param input - Input data to the checkpoint
 * @param output - Output data from the checkpoint
 * @returns Markdown formatted summary
 */
export async function generateMarkdownSummary(
  checkpointName: string,
  input: CheckpointData,
  output: CheckpointData
): Promise<string> {
  try {
    // Create agent configuration for markdown generation
    const agentConfig: AgentConfig = {
      model: {
        provider: {
          type: 'litellm',
          config: {
            apiKey: process.env.LITELLM_API_KEY || '',
            baseUrl: process.env.LITELLM_BASE_URL || '', 
            timeout: 600000, // 10 minutes
            retries: 5
          }
        },
        defaultModel: 'glm-latest'
      },
      tools: {
        enabled: [], // No tools needed for markdown generation
        config: {},
        execution: {
          timeout: 500000 // 30 seconds
        }
      },
      execution: {
        maxTurns: 1, // Single turn for markdown generation
        mode: 'continuous',
        timeouts: {
          turn: 30000,
          tool: 30000
        },
        limits: {
          toolsPerTurn: 1 // Must be at least 1, even if no tools are enabled
        },
        errorHandling: {
          continueOnToolError: false,
          maxRetries: 1
        }
      },
      events: {
        logging: LogLevel.ERROR // Only log errors
      }
    }

    // Create the agent
    const agent = Agent.create(agentConfig)

    // Create the prompt for markdown generation
    const prompt = `You are a technical documentation expert. Generate a well-formatted markdown summary for the following checkpoint execution.

**Checkpoint Name:** ${checkpointName}

**Input Data:**
\`\`\`json
${JSON.stringify(input, null, 2)}
\`\`\`

**Output Data:**
\`\`\`json
${JSON.stringify(output, null, 2)}
\`\`\`

Generate a comprehensive markdown summary with the following structure:

# ${checkpointName}

## Summary
[Brief 2-3 sentence overview of what this checkpoint does]

## Input
[Describe the key inputs in a clear, readable format - not just JSON dump]

## Processing
[Explain what processing/analysis was performed]

## Output
[Describe the key outputs and results in a clear, readable format]

## Key Insights
[List 2-3 important insights or findings from this checkpoint]

---

**Important:** 
- Make it readable and informative for engineers
- Focus on the "what" and "why", not just the raw data
- Use proper markdown formatting (headers, lists, code blocks)
- Keep it concise but comprehensive
- Return ONLY the markdown, no additional commentary`

    // Execute the agent
    const result = await agent.execute({
      messages: [
        createUserMessage(prompt)
      ]
    })

    // Extract the markdown from the last assistant message
    // Type guard to check if message is an assistant message
    const assistantMessages = result.messages.filter(
      (msg: Message): msg is Extract<Message, { type: 'assistant' }> => 
        msg.type === 'assistant'
    )
    
    const lastMessage = assistantMessages.pop()

    if (!lastMessage || !lastMessage.content) {
      throw new Error('No markdown generated by agent')
    }

    return lastMessage.content
  } catch (error) {
    logger.error(`Error generating markdown summary for ${checkpointName}:`, error)
    
    // Return simple error message if agent fails
    return 'Unable to generate summary'
  }
}
