/**
 * Self-contained HTML template for create-html-report.
 *
 * The whole document — including CSS — is inlined so the resulting file is
 * standalone (no external fonts, no CDN deps). Users download it, double-click,
 * and it opens in any browser with usable typography on mobile + desktop +
 * print. Dark mode follows the OS via `prefers-color-scheme: dark`.
 *
 * The body slot is filled with already-rendered HTML (output of
 * `marked.parse()`). Any sanitization happens BEFORE this template wraps it.
 */

import sanitizeHtml from "sanitize-html";

export interface HtmlTemplateInput {
  /** Becomes both <title> and the visible <h1>. */
  title: string;
  /** Subtitle line under the H1 (e.g. agent slug + timestamp). Optional. */
  subtitle?: string;
  /** Pre-rendered HTML body — output of marked.parse() after sanitization. */
  body: string;
}

const CSS = `
  :root {
    color-scheme: light dark;
    --bg: #ffffff;
    --fg: #1f2937;
    --fg-muted: #6b7280;
    --border: #e5e7eb;
    --code-bg: #f3f4f6;
    --code-fg: #111827;
    --accent: #2563eb;
    --table-row-alt: #fafafa;
    --quote-border: #d1d5db;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --bg: #0f0f10;
      --fg: #e5e7eb;
      --fg-muted: #9ca3af;
      --border: #2a2a2c;
      --code-bg: #1a1a1c;
      --code-fg: #f1f5f9;
      --accent: #60a5fa;
      --table-row-alt: #18181a;
      --quote-border: #3a3a3d;
    }
  }
  * { box-sizing: border-box; }
  html, body {
    margin: 0;
    padding: 0;
    background: var(--bg);
    color: var(--fg);
    font: 15px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
  }
  .container {
    max-width: 920px;
    margin: 0 auto;
    padding: 32px 24px 80px;
  }
  header { border-bottom: 1px solid var(--border); padding-bottom: 16px; margin-bottom: 28px; }
  header h1 { font-size: 28px; line-height: 1.2; margin: 0 0 6px; font-weight: 700; }
  header .subtitle { color: var(--fg-muted); font-size: 13px; }
  h1, h2, h3, h4, h5, h6 { line-height: 1.25; margin: 1.6em 0 0.5em; font-weight: 600; }
  h1 { font-size: 24px; }
  h2 { font-size: 20px; border-bottom: 1px solid var(--border); padding-bottom: 6px; }
  h3 { font-size: 17px; }
  h4 { font-size: 15px; }
  h5, h6 { font-size: 14px; color: var(--fg-muted); }
  p { margin: 0.6em 0; }
  ul, ol { padding-left: 1.6em; margin: 0.6em 0; }
  li { margin: 0.25em 0; }
  li > p { margin: 0.25em 0; }
  a { color: var(--accent); text-decoration: none; }
  a:hover { text-decoration: underline; }
  strong { font-weight: 600; }
  em { font-style: italic; }
  code {
    background: var(--code-bg);
    color: var(--code-fg);
    padding: 0.1em 0.35em;
    border-radius: 4px;
    font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    font-size: 0.92em;
  }
  pre {
    background: var(--code-bg);
    color: var(--code-fg);
    padding: 14px 16px;
    border-radius: 8px;
    overflow-x: auto;
    font-size: 13px;
    line-height: 1.5;
    margin: 0.8em 0;
  }
  pre code { background: transparent; padding: 0; border-radius: 0; font-size: inherit; }
  blockquote {
    margin: 0.8em 0;
    padding: 0.2em 0 0.2em 14px;
    border-left: 3px solid var(--quote-border);
    color: var(--fg-muted);
  }
  hr { border: none; border-top: 1px solid var(--border); margin: 1.4em 0; }
  table {
    border-collapse: collapse;
    width: 100%;
    margin: 0.8em 0;
    font-size: 14px;
  }
  th, td {
    text-align: left;
    padding: 8px 12px;
    border-bottom: 1px solid var(--border);
    vertical-align: top;
  }
  th { font-weight: 600; background: var(--code-bg); }
  tbody tr:nth-child(even) td { background: var(--table-row-alt); }
  img { max-width: 100%; height: auto; }
  footer {
    margin-top: 60px;
    padding-top: 16px;
    border-top: 1px solid var(--border);
    color: var(--fg-muted);
    font-size: 12px;
  }
  @media print {
    .container { max-width: none; padding: 0; }
    a { color: inherit; text-decoration: underline; }
  }
`;

/** Build a complete `<!DOCTYPE html>...</html>` string. */
export function buildHtmlDocument(input: HtmlTemplateInput): string {
  const subtitleHtml = input.subtitle
    ? `<div class="subtitle">${escapeHtml(input.subtitle)}</div>`
    : "";
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(input.title)}</title>
  <style>${CSS}</style>
</head>
<body>
  <main class="container">
    <header>
      <h1>${escapeHtml(input.title)}</h1>
      ${subtitleHtml}
    </header>
    ${input.body}
    <footer>Generated by Xyne Claw · ${new Date().toISOString()}</footer>
  </main>
</body>
</html>`;
}

/** Tiny HTML entity escaper for non-body text (title/subtitle). */
function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export function sanitizeHtmlBody(html: string): string {
  return sanitizeHtml(html, {
    allowedTags: sanitizeHtml.defaults.allowedTags.concat([
      "img",
      "h1",
      "h2",
      "details",
      "summary",
    ]),
    allowedAttributes: {
      "*": ["class", "id", "align"],
      a: ["href", "name", "target", "rel"],
      img: ["src", "alt", "title", "width", "height"],
      details: ["open"],
      ol: ["start", "type"],
      td: ["colspan", "rowspan"],
      th: ["colspan", "rowspan", "scope"],
    },
    allowedSchemes: ["http", "https", "mailto"],
    allowedSchemesByTag: { img: ["http", "https", "data"] },
    allowProtocolRelative: false,
    exclusiveFilter: (frame) => {
      if (frame.tag !== "img") return false;
      const src = (frame.attribs?.src ?? "").trim().toLowerCase();
      return (
        src.startsWith("data:text/html") ||
        src.startsWith("data:image/svg+xml")
      );
    },
  });
}
