import type { ComponentType } from 'react';
import type { LucideIcon } from 'lucide-react';
import { XyneAIStar } from '../../components/icons/xyne-ai';
import {
  Activity,
  AppWindow,
  BarChart3,
  BookOpen,
  Brain,
  CalendarClock,
  CircleUser,
  ClipboardCheck,
  ClipboardList,
  FileText,
  Filter,
  FolderKanban,
  LifeBuoy,
  LayoutDashboard,
  ListChecks,
  MessageCircle,
  MessagesSquare,
  Mic,
  Phone,
  PieChart,
  Search,
  ShieldUser,
  SlidersHorizontal,
  SmilePlus,
  Sparkles,
  Ticket,
  Users,
  WandSparkles,
  Workflow,
  Wrench,
  PanelsTopLeft,
  PenLine,
  UserCog,
  Copy,
  Bell,
  BarChart2,
  Settings,
  Zap,
  Video,
  Forward,
  Info,
  MousePointerClick,
  PanelRight,
} from 'lucide-react';

export type FeatureCategory =
  | 'messaging'
  | 'activity'
  | 'calls'
  | 'work-tracking'
  | 'data'
  | 'ai'
  | 'admin'
  | 'power-tools';

export interface UserGuideFeature {
  id: string;
  title: string;
  tagline: string;
  path?: string;
  findIn: string;
  shortcut?: string;
  actions: string[];
  steps: string[];
  tip?: string;
  keywords: string[];
  category: FeatureCategory;
  icon: LucideIcon | ComponentType<{ size?: number; className?: string }>;
  visualKey: string;
  screenshots?: Array<string | undefined>;
  /** Optional walkthrough video; opens in a new tab from the feature card. */
  videoUrl?: string;
}

export interface GuideCategoryInfo {
  id: FeatureCategory;
  title: string;
  description: string;
  icon: LucideIcon;
}

export const GUIDE_CATEGORIES: GuideCategoryInfo[] = [
  {
    id: 'messaging',
    title: 'Messaging',
    description: 'Channels, direct messages, threads, and notifications',
    icon: MessagesSquare,
  },
  {
    id: 'activity',
    title: 'Activity & Discovery',
    description: 'Activity feed, catch-up recaps, and global search',
    icon: Bell,
  },
  {
    id: 'calls',
    title: 'Calls & Collaboration',
    description: 'Voice and video calls, canvas, and screen sharing',
    icon: Video,
  },
  {
    id: 'work-tracking',
    title: 'Work Tracking',
    description: 'Tickets, boards, projects, workflows, and support queues',
    icon: Ticket,
  },
  {
    id: 'data',
    title: 'Data & Reporting',
    description: 'Analytics, dashboards, product insights, and forms',
    icon: BarChart2,
  },
  {
    id: 'ai',
    title: 'AI & Knowledge',
    description: 'Xyne AI assistant, memory, knowledge base, and agents',
    icon: WandSparkles,
  },
  {
    id: 'admin',
    title: 'Administration',
    description: 'User groups, access control, integrations, and settings',
    icon: Settings,
  },
  {
    id: 'power-tools',
    title: 'Power Tools',
    description: 'RCA, VSCode workspace, browser panel, and shortcuts',
    icon: Zap,
  },
];

export const USER_GUIDE_FEATURES: UserGuideFeature[] = [
  {
    id: 'chat',
    title: 'Chat (Channels)',
    tagline: 'Main place for team conversations and updates.',
    path: '/chat/dir',
    findIn: 'Sidebar -> Chat',
    actions: ['Open channels', 'Read and reply to threads', 'Share files and links'],
    steps: [
      'Click Chat [[Inbox]] in the left sidebar to open the channels list.',
      'Select a channel — e.g. #general or #engineering — to open the conversation.',
      'Type your message in the text box at the bottom and press Enter to send.',
      'To reply inside a thread, hover a message and click the reply button [[MessageCircleMore]] on the right.',
      'To share a file, click the attach button [[Plus]] next to the message box and choose a file.',
      'Xyne Spaces checks your spelling as you type — red underlines flag misspellings. Right-click to see suggestions.',
      'Type ASCII emoticons like ":)" or "<3" and they automatically convert to emoji (smiley face, heart) when you send.',
    ],
    tip: 'Use @ to mention a teammate (e.g. @alice.chen) so they get a notification instantly. Typing @ also triggers bot search — if your workspace has bots configured, select one to start an automated conversation with it.',
    keywords: ['chat', 'channel', 'conversation', 'messages', 'spell check', 'emoji'],
    category: 'messaging',
    icon: MessagesSquare,
    visualKey: 'chat',
    screenshots: [],
    videoUrl:
      'https://next.frame.io/share/4820d565-1c8a-41e9-afe4-5d452c7a0b78/view/ef722fdb-a9c7-4acd-9288-a90fa8d33303',
  },
  {
    id: 'dms',
    title: 'Direct Messages',
    tagline: 'Private one-to-one or small group conversations.',
    path: '/chat/dm',
    findIn: 'Chat -> DMs tab',
    actions: ['Message a teammate', 'Start private discussions', 'Share quick updates'],
    steps: [
      'Open Chat [[Inbox]] from the sidebar, then click the "DMs" tab at the top.',
      'A badge on the DMs tab shows your total unread DM count at a glance.',
      'Click create message [[PenBox]] to start a new conversation.',
      'Type a teammate\'s name — e.g. "Bob Kumar" — and select them from the dropdown.',
      'Write your message and press Enter. The conversation is private to you and Bob.',
      'To start a group DM, click create message [[PenBox]] and add multiple names one by one. When more than one person is selected, the form shows "Group conversation with N people". Click "Start DM" to create it.',
    ],
    tip: 'Star a DM to pin it at the top of your list — great for people you message daily.',
    keywords: ['dm', 'direct message', 'private', 'group dm', 'unread'],
    category: 'messaging',
    icon: MessageCircle,
    visualKey: 'dms',
  },
  {
    id: 'threads',
    title: 'Threads',
    tagline: 'Keep replies organized under the original message.',
    path: '/chat/threads',
    findIn: 'Chat -> Threads',
    actions: ['Open thread inbox', 'Reply in context', 'Track active discussions'],
    steps: [
      'Go to Chat [[Inbox]] and click the "Threads" tab in the top navigation — threads are available on messages sent in channels.',
      "The Threads inbox shows all threads you've participated in or been mentioned in.",
      'Click any thread entry to jump straight to that conversation in context.',
      'Reply inside the thread panel on the right without leaving your current channel.',
    ],
    tip: 'To get updates on a thread even without replying, hover the message, click More [[MoreVertical]], and select "Subscribe to notifications".',
    keywords: ['thread', 'reply', 'discussion'],
    category: 'messaging',
    icon: ListChecks,
    visualKey: 'threads',
  },
  {
    id: 'activity',
    title: 'Activity',
    tagline: 'See recent updates, mentions, and important events.',
    path: '/chat/activity',
    findIn: 'Chat -> Activity',
    actions: ['Review recent events', 'Catch missed notifications', 'Jump to source message'],
    steps: [
      'Open Chat [[Inbox]] and click the Activity [[Activity]] tab in the top navigation.',
      'Scan the feed — each row shows who mentioned you or reacted to your message.',
      'Click any activity item to jump directly to that message in the original channel.',
      'Use the filter tabs at the top (Your Mentions, Replies, Reactions, Tickets, etc.) to narrow down the activity feed.',
      'Mark all visible items as read using the "Mark as read" button at the top right of the Activity panel.',
    ],
    tip: 'Activity is your quickest way to catch up after being away — faster than scrolling channels.',
    keywords: ['activity', 'notifications', 'mentions'],
    category: 'activity',
    icon: Activity,
    visualKey: 'activity',
  },
  {
    id: 'bookmarks',
    title: 'Bookmarks',
    tagline: 'Save important items for quick future access.',
    path: '/chat/bookmarks',
    findIn: 'Chat -> Bookmarks',
    actions: [
      'Save key messages',
      'Organize references',
      'Re-open critical content',
      'Snooze a bookmark',
      'Mark a bookmark as done',
    ],
    steps: [
      'Hover over any message, click the options menu [[MoreVertical]] in the hover toolbar, and select Add bookmark [[Bookmark]].',
      'The message is instantly saved. Open Chat [[Inbox]] → Bookmarks [[Bookmark]] to see all saved items.',
      'Click a bookmark entry to jump back to the original message in its channel.',
      'To remove a bookmark, hover the message, click the options menu [[MoreVertical]] in the hover toolbar, and select Remove bookmark [[BookmarkMinus]] — or click "Remove" directly in the Bookmarks panel.',
      'To snooze a bookmark, open the Bookmarks panel, hover a bookmark item, and click the snooze button [[Clock]].',
      'Choose a snooze duration: 30 mins, 1 hour, 3 hours, Tomorrow at 9:00 AM, or Monday at 9:00 AM — the bookmark will resurface at the chosen time.',
      'Click the done button [[Check]] on a bookmark entry to mark it as done — it moves to the completed section and stops further snooze reminders.',
    ],
    tip: 'Snooze a bookmark to "remind me later" — great for messages you cannot action right now but do not want to forget.',
    keywords: ['bookmark', 'saved', 'important', 'snooze', 'remind later', 'mark done'],
    category: 'messaging',
    icon: BookOpen,
    visualKey: 'bookmarks',
  },
  {
    id: 'scheduled-messages',
    title: 'Scheduled Messages',
    tagline: 'Write now, send later at the right time.',
    path: '/scheduled-messages',
    findIn: 'Sidebar -> Scheduled Messages',
    actions: ['Create scheduled message', 'Choose send time', 'Edit or cancel pending schedules'],
    steps: [
      'Click Scheduled Messages [[CalendarClock]] in the left sidebar to open the scheduled messages page.',
      'Click "Create Scheduled Message" in the top-right to open the compose form.',
      'Select the target channel, write your message, and choose the days and time to send — e.g. "Weekdays (Mon–Fri) at 9:00 AM".',
      'Click "Save" to confirm — the message appears in the list with its channel, schedule, and send time.',
      'Click any scheduled message card to edit the content, change the schedule, or cancel it.',
    ],
    tip: 'Use the channel and author filters at the top of the page to quickly find a specific scheduled message.',
    keywords: ['schedule', 'messages', 'timed send', 'scheduled messages', 'recurring'],
    category: 'messaging',
    icon: CalendarClock,
    visualKey: 'scheduled',
  },
  {
    id: 'recap',
    title: 'Recap',
    tagline: 'Get a summary of what happened while you were away.',
    path: '/chat/recap',
    findIn: 'Chat -> Recap',
    actions: ['Read quick summaries', 'Catch up faster', 'Open key linked messages'],
    steps: [
      'Click the Recap [[Sparkles]] tab in the Chat navigation.',
      'The AI-generated summary shows what happened across your channels the previous day.',
      'Scan the per-channel summaries — e.g. "#engineering had 14 messages about the API migration".',
      'Click a numbered citation next to a recap point to view the source message in context.',
      'To change which channels appear in your recap, click the settings button [[Settings]] and update your channel selection.',
    ],
    tip: 'Run Recap first thing in the morning instead of scrolling every channel manually.',
    keywords: ['recap', 'summary', 'catch up'],
    category: 'activity',
    icon: Sparkles,
    visualKey: 'recap',
  },
  {
    id: 'search',
    title: 'Global Search',
    tagline: 'Find messages, tickets, users, and files quickly.',
    findIn: 'Anywhere -> Command Menu',
    shortcut: 'Cmd/Ctrl + K',
    actions: [
      'Search people and channels',
      'Find old messages',
      'Search bots with @',
      'Open results instantly',
    ],
    steps: [
      'Press Cmd+K (Mac) or Ctrl+K (Windows/Linux) from anywhere in the app.',
      'Start typing — e.g. "API timeout" — to search across messages, tickets, and users.',
      'Use arrow keys to navigate results, then press Enter to open the selected item.',
      'Prefix your query with "#" to quickly switch to a specific channel by name.',
      'Prefix your query with "@" to search bots quickly (for example, "@release-bot").',
      'When you select a bot result, Xyne opens the bot chat context so you can message that bot directly from chat.',
      'You can find that bot chat in the DM area under Chat -> DMs (it appears like a direct-message thread with the bot).',
      'Use the tabs at the top (People, Messages, Channels, Tickets, Files, Canvas, Calls) to filter results by type.',
    ],
    tip: 'Use "#" for channel jump and "@" for bot lookup. Selecting a bot from search takes you straight into bot chat, so you can ask it immediately.',
    keywords: ['search', 'command menu', 'cmdk'],
    category: 'activity',
    icon: Search,
    visualKey: 'search',
  },
  {
    id: 'bot-chat-from-search',
    title: 'Chat with Bots from Search',
    tagline: 'Open a bot conversation directly from the command menu.',
    findIn: 'Anywhere -> Command Menu -> Bot result',
    shortcut: 'Cmd/Ctrl + K',
    actions: ['Find bots quickly', 'Open bot chat directly', 'Start asking immediately'],
    steps: [
      'Press Cmd+K (Mac) or Ctrl+K (Windows/Linux) to open Global Search.',
      'Type "@" followed by the bot name — e.g. "@release-bot" — to filter to bot results.',
      'Use arrow keys to highlight the bot result and press Enter.',
      'Xyne opens the bot chat directly so you can send a prompt immediately.',
      'If you close the command menu, reopen the same bot chat from Chat -> DMs in the left sidebar.',
      'Type your query in chat and press Enter to start the bot workflow or response.',
    ],
    tip: 'Use bot search when you already know which automation or assistant you need — it is faster than browsing channels first.',
    keywords: ['bot search', '@', 'bot chat', 'command menu', 'open bot'],
    category: 'activity',
    icon: MessageCircle,
    visualKey: 'search',
  },
  {
    id: 'calls',
    title: 'Calls',
    tagline: 'View and join your recent and scheduled calls.',
    path: '/calls',
    findIn: 'Sidebar -> Calls',
    actions: [
      'Open call history',
      'Rejoin call links',
      'Review call details',
      'Mute or unmute microphone',
      'Toggle camera',
      'Open in-call chat',
      'Send reactions',
      'Open call tools',
      'Expand call view',
      'End a call',
    ],
    steps: [
      'Click Calls [[Phone]] in the left sidebar to open the calls list.',
      'Your recent calls are listed — tabs show All, Scheduled, and Missed calls.',
      'Click "Join call" on an active call link to re-enter the meeting — clicking on participant avatars shows the list of people on the call.',
      'To start a new call, click "New Call" and choose "Start an instant call" or "Schedule call for later" from the dropdown.',
      'While in a call, use the control toolbar at the bottom: click the microphone button [[Mic]] to toggle your microphone on or off.',
      'Click the camera button [[Video]] to turn your video on or off.',
      'Use the small arrow next to the mic/camera controls to switch your active input/output devices when needed.',
      'Click the screen share button [[Monitor]] to share your screen. In the picker, choose "Entire Screen" to share everything or "Window" to share only a specific app — a red border appears around the shared content. Click "Stop Sharing" when done.',
      'Click the participants button [[Users]] to open the participants panel — see who is muted, speaking, or waiting. You can also click participant avatars in the call to view the people list and profiles.',
      'Click the chat button in the call toolbar to open the in-call conversation panel and follow live messages.',
      'Click the reactions button to send quick emoji feedback without interrupting the speaker.',
      'Click the tools/apps button to open available call utilities and integrations.',
      'Click the expand/fullscreen button in the call toolbar to enlarge or focus the call view.',
      'Click the Leave call button [[PhoneOff]] to leave the call.',
      'To share a call externally, click the share icon in the call header to copy the join URL — send it to anyone to let them join even without a Xyne Spaces account.',
    ],
    tip: 'Mute yourself when you are not speaking — it removes background noise for everyone and is good call etiquette.',
    keywords: [
      'calls',
      'meeting',
      'voice',
      'in a call',
      'status',
      'mute',
      'camera',
      'end call',
      'participants',
    ],
    category: 'calls',
    icon: Phone,
    visualKey: 'calls',
    videoUrl:
      'https://next.frame.io/share/4820d565-1c8a-41e9-afe4-5d452c7a0b78/view/356f6713-241f-4c3c-8e6b-a33ceaf4206a',
  },
  {
    id: 'recordings',
    title: 'Recordings',
    tagline: 'Replay important conversations when needed.',
    path: '/recordings',
    findIn: 'Sidebar -> Recordings',
    actions: ['Browse recordings', 'Open recording details', 'Share or delete recording'],
    steps: [
      'Click Recordings [[Mic]] in the left sidebar.',
      'Browse the list of recorded calls — each entry shows the title, date, and duration.',
      'Click a recording row to open recording details.',
      'Use View Thread to jump back to the related chat context.',
      'Click Share Recording to copy a link and share it in a channel or DM.',
      'Use Delete Recording if you need to remove it.',
    ],
    keywords: ['recordings', 'meeting notes', 'view thread', 'share recording', 'delete recording'],
    category: 'calls',
    icon: Mic,
    visualKey: 'recordings',
  },
  {
    id: 'canvas',
    title: 'My Canvas',
    tagline: 'A personal and collaborative writing space accessible from the global chat nav.',
    path: '/chat/canvas',
    findIn: 'Chat -> Canvas',
    actions: ['Create new canvas', 'Draft collaborative notes', 'Reference in chat'],
    steps: [
      'Open Chat [[Inbox]] and click the Canvas tab [[PanelsTopLeft]] in the top navigation to open your global canvas list.',
      'Click "New Canvas" to create a blank document with a title — e.g. "Q2 Product Roadmap".',
      'Use the rich-text toolbar to add headings, bullet lists, and code blocks.',
      'Invite teammates to collaborate by clicking "Share" and typing their names.',
      'To share a canvas in chat, open the canvas and click the "Share" button — copy the link and paste it into any channel or DM.',
    ],
    tip: 'My Canvas is great for team-wide documents. For documents tied to a specific channel, use the Canvas tab inside that channel instead.',
    keywords: ['canvas', 'docs', 'collaboration', 'my canvas'],
    category: 'calls',
    icon: PanelsTopLeft,
    visualKey: 'canvas',
  },
  {
    id: 'channel-canvas',
    title: 'Channel Canvas',
    tagline: "Per-channel collaborative documents linked to that channel's context.",
    path: '/chat/dir',
    findIn: 'Chat -> open any channel -> Canvas tab',
    actions: [
      'Create channel-scoped canvas',
      'Collaborate within a channel team',
      'Keep docs close to conversation',
    ],
    steps: [
      'Open any channel, then click the "Canvas" tab in the channel header tabs.',
      'Click "New Canvas" to create a document scoped to that channel.',
      'Use the rich-text toolbar to add headings, bullet lists, and code blocks.',
      'All channel members can view and collaborate on the canvas.',
      'Share the canvas link in the channel conversation for quick access.',
    ],
    tip: 'Use Channel Canvas for working documents tied to a specific project or team channel.',
    keywords: ['canvas', 'channel canvas', 'docs', 'collaboration'],
    category: 'calls',
    icon: PanelsTopLeft,
    visualKey: 'channel-canvas',
  },

  {
    id: 'tickets',
    title: 'Tickets',
    tagline: 'Track customer or internal issues from intake to resolution.',
    path: '/tickets',
    findIn: 'Sidebar -> Tickets',
    actions: ['Create and assign tickets', 'Update status', 'Link ticket discussions'],
    steps: [
      'Click Tickets [[Ticket]] in the left sidebar to open the ticket queue.',
      'Click "Create Ticket" and fill in the title — e.g. "Bug: API timeout on checkout" — and description.',
      'Assign the ticket to a teammate using the Assignee dropdown. You can also set a Reviewer, QA, and Manager in the create ticket form.',
      'Set the priority (Low / Medium / High / Critical) and select a project to group it under.',
      'Click "Save" — the ticket is created with an ID like #1024 and appears in the queue.',
      'Update status by clicking the status badge on the ticket to cycle through workflow stages.',
    ],
    tip: 'Paste a ticket ID (e.g. #1024) into any chat message — teammates can click it to jump directly to the ticket.',
    keywords: ['ticket', 'issue', 'task'],
    category: 'work-tracking',
    icon: Ticket,
    visualKey: 'tickets',
    videoUrl:
      'https://next.frame.io/share/4820d565-1c8a-41e9-afe4-5d452c7a0b78/view/af01fd39-f693-4f14-a706-14ac114465d6',
  },
  {
    id: 'support',
    title: 'Support',
    tagline: 'Handle customer issues from triage to resolution.',
    path: '/support',
    findIn: 'Sidebar -> Support',
    actions: ['Open support queue', 'Triage incoming requests', 'Convert to tickets'],
    steps: [
      'Click Support [[LifeBuoy]] in the left sidebar to open the support queue.',
      'Review incoming requests and open any item to inspect details and conversation history.',
      'Assign an owner and set priority so urgent requests are handled first.',
      'Convert a support request into a ticket when follow-up work is required.',
      'Post updates back to the request thread so the reporter can track progress.',
    ],
    tip: 'Use Support for intake and communication, and Tickets for structured execution.',
    keywords: ['support', 'support queue', 'triage', 'customer request', 'helpdesk'],
    category: 'work-tracking',
    icon: LifeBuoy,
    visualKey: 'support',
  },
  {
    id: 'projects-board',
    title: 'Projects Board',
    tagline: 'Kanban-style board for team execution.',
    path: '/projects',
    findIn: 'Sidebar -> Projects Board',
    actions: ['Open project board', 'Move cards across stages', 'Track progress'],
    steps: [
      'Click Projects Board [[FolderKanban]] in the left sidebar.',
      'Select a project — e.g. "Mobile App v2.0" — from the project list at the top.',
      'The board shows columns: Todo, In Progress, Done, Cancelled, and On Hold.',
      'Drag a card — e.g. "Design login screen" — from "Todo" to "In Progress" to update its status.',
      'Click any card to open details: description, assignee, due date, and linked tickets.',
      'Click "Create Ticket" at the bottom of a column to add a new task directly on the board.',
    ],
    tip: 'Filter the board by assignee to see only your own cards — use the "Assigned to Me" filter in the top bar.',
    keywords: ['projects', 'kanban', 'board'],
    category: 'work-tracking',
    icon: FolderKanban,
    visualKey: 'projects-board',
  },

  {
    id: 'product-insights',
    title: 'Product Insights',
    tagline: 'Understand usage and behavior trends.',
    path: '/product-insights',
    findIn: 'Sidebar -> Insights',
    actions: ['Open insight dashboards', 'Review trend signals', 'Share product learnings'],
    steps: [
      'Click Insights [[PieChart]] in the left sidebar to open the Product Insights view.',
      'The overview shows ticket data grouped by theme — a pie chart displays cluster counts across categories.',
      'Click a cluster in the chart to drill into the individual tickets for that theme.',
      'Review the ticket list for a cluster to understand patterns and recurring issues.',
    ],
    tip: 'Set a weekly reminder to review Insights every Monday — spot trends before they become problems.',
    keywords: ['insights', 'product', 'trends'],
    category: 'data',
    icon: PieChart,
    visualKey: 'insights',
  },
  {
    id: 'forms',
    title: 'Forms',
    tagline: 'Collect structured information from users or teams.',
    path: '/forms',
    findIn: 'Sidebar -> Forms',
    actions: [
      'Create forms',
      'Collect responses',
      'Use data in workflows',
      'Edit an existing form',
    ],
    steps: [
      'Click Forms [[Clipboard]] in the left sidebar.',
      'Click "Create Form" and give it a name — e.g. "Bug Report" or "Feature Request".',
      'Add fields using the add field button [[Plus]] : Text, Multiline, Number, Date, Single Select, or Multi Select.',
      'Share the form link with your team by copying the URL from the form page and posting it in a relevant channel like #support.',
      "All submitted entries are shown in the form's response table by default — no extra navigation needed.",
      'To edit an existing form, click its name in the Forms list to open the form editor — add, reorder, or remove fields, then click "Update Form".',
    ],
    tip: 'Connect a form to a workflow so each new submission automatically creates a ticket for your team to action.',
    keywords: ['forms', 'responses', 'intake', 'edit form'],
    category: 'data',
    icon: FileText,
    visualKey: 'forms',
  },
  {
    id: 'workflows',
    title: 'Workflows',
    tagline: 'Automate multi-step task execution.',
    path: '/tickets/:ticketId/workflow',
    findIn: 'Ticket detail -> Workflow',
    actions: ['Open workflow runs', 'Inspect step results', 'Retry or continue tasks'],
    steps: [
      'Open a ticket — e.g. #1024 — and navigate to the Workflow screen for that ticket.',
      'Use the "Rerun" button (title: "Rerun Workflow") to re-trigger the automated steps, or use the workflow trigger modal for the initial run.',
      'Each step in the workflow shows a status: Pending, Running, Complete, or Failed.',
      'Click a failed step to see the error log and retry it.',
      'Once the workflow completes, click the "Final Git Diff" tab to inspect all code changes generated or applied during the run.',
      'The "Live Edits" tab shows real-time in-progress changes as the workflow executes — no need to refresh.',
      'The "Preview Changes" tab lets you review staged changes before they are applied.',
      'Some workflows include an "RCA" tab — if triggered, it auto-populates the Root Cause Analysis form with timeline data from the workflow run.',
      'To build a new workflow, go to Settings [[Settings]] → Workflows and define the steps.',
    ],
    tip: 'Workflows can auto-assign tickets, send notifications, and call external APIs — all without code.',
    keywords: ['workflow', 'automation', 'pipeline', 'git diff', 'live edits', 'rca'],
    category: 'work-tracking',
    icon: Workflow,
    visualKey: 'workflows',
  },
  {
    id: 'xyne-ai',
    title: 'Xyne AI',
    tagline: 'Context-aware AI assistant for day-to-day work.',
    findIn: 'Top-right action bar',
    actions: [
      'Ask questions',
      'Summarize context',
      'Generate next actions',
      'Start a new chat session',
      'Browse chat history',
      'Toggle web search or deep research',
      'Add context to a query',
      'Attach files',
      'Stop AI response',
    ],
    steps: [
      'Click the Xyne AI button [[XyneAIStar]] in the top-right action bar to open the AI panel.',
      'Type a question in natural language — e.g. "Summarize what happened in #incidents today".',
      'Xyne AI pulls from your channels, tickets, and knowledge base to give a contextual answer.',
      'Ask follow-up questions in the same thread — e.g. "Who is working on it?".',
      'Click "Add to Canvas" or "Post to channel" to share the AI output with your team.',
      'Click the new chat button [[SquarePen]] in the panel header to clear the current session and start a fresh conversation.',
      'Click the history button [[ChatHistory]] to browse your previous AI chat sessions and reopen any of them.',
      'Click the memories button [[Brain]] to open your AI memory entries — review, add, or delete what Xyne AI remembers about your workspace.',
      'Click the activity button [[Activity]] to see a log of your recent AI interactions.',
      'Click the settings button [[Settings]] to open the Settings modal — it contains two tabs: "Custom Instructions" (to shape how Xyne AI responds) and "Skills".',
      'Click the close button [[X]] in the header to close the AI panel without losing your current conversation.',
      'In the input box, click the "/" button to attach channels, tickets, or documents as context for your next query.',
      'Click the web search toggle [[Globe]] to include real-time web results alongside your workspace data.',
      'Click the Deep Research button to switch to a thorough multi-step research mode — great for complex questions that need extended reasoning.',
      'Click the Create Canvas button to have the AI write directly into a new canvas document instead of replying inline.',
      'Click the attach button [[Plus]] in the input area to attach files — images, PDFs, or code files — as direct input for your query.',
      'Click the stop button [[StopIcon]] while the AI is responding to halt generation immediately.',
      'Xyne AI uses Memory v2 — it remembers key facts about your workspace across sessions. Open the Memories panel to review or edit what it knows.',
    ],
    tip: 'Use the Custom Instructions tab (inside Settings) to tell Xyne AI your role and preferred response style once — it applies to every future conversation automatically.',
    keywords: [
      'xyne ai',
      'assistant',
      'ai',
      'memory',
      'fresh chat',
      'new chat',
      'history',
      'web search',
      'deep research',
      'add context',
      'attach',
      'custom instructions',
      'stop',
      'canvas',
    ],
    category: 'ai',
    icon: XyneAIStar,
    visualKey: 'xyne-ai',
  },
  {
    id: 'knowledge-base',
    title: 'Knowledge Base',
    tagline: 'Searchable internal knowledge and docs.',
    path: '/knowledge-base',
    findIn: 'Sidebar -> Knowledge Base',
    actions: ['Browse sources', 'Search answers', 'Link knowledge in workstreams'],
    steps: [
      'Click Knowledge Base [[BookOpen]] in the left sidebar.',
      'Use the "Select Project" dropdown to filter documents by project.',
      'Browse the filtered document list — e.g. "API Documentation", "Onboarding Guide", "Engineering Runbook".',
      'Click a document to open the full article. Use Cmd+F to search within the document.',
    ],
    tip: 'Link knowledge base articles inside tickets and chat to give teammates instant context.',
    keywords: ['knowledge', 'docs', 'kb'],
    category: 'ai',
    icon: BookOpen,
    visualKey: 'knowledge-base',
  },
  {
    id: 'memory',
    title: 'Context Memory',
    tagline: 'Persistent operational context used by teams and AI.',
    path: '/memory',
    findIn: 'Sidebar -> Context',
    actions: ['Review saved context', 'Update key notes', 'Reuse historical decisions'],
    steps: [
      'Click Context [[Brain]] in the left sidebar to open the Context Memory view.',
      'The list shows saved context entries — e.g. "Platform migration: decided to use Postgres".',
      'Use the search bar (placeholder: "Search context...") to filter entries by keyword.',
      'Xyne AI automatically reads relevant context entries when answering questions about your org.',
      "Click any entry to edit or delete it if it's outdated. Removing stale entries keeps AI answers accurate.",
    ],
    tip: 'Save team decisions and recurring context here so new teammates can get up to speed faster.',
    keywords: ['memory', 'context', 'history', 'memory v2', 'filter'],
    category: 'ai',
    icon: Brain,
    visualKey: 'memory',
  },
  {
    id: 'user-groups',
    title: 'User Groups',
    tagline: 'Organize users by team, function, or responsibility.',
    path: '/user-groups',
    findIn: 'Sidebar -> User Groups',
    actions: ['Create groups', 'Assign users', 'Control group-level operations'],
    steps: [
      'Click User Groups [[UsersIcon]] in the left sidebar.',
      'Click "Create User Group" and give it a name — e.g. "Engineering" or "Customer Success".',
      'Add members by typing names — e.g. "Alice Chen", "Bob Kumar" — and selecting from the dropdown.',
      'Save the group. You can now @mention the group in chat (e.g. @engineering) to notify all members.',
      'To enable automatic ticket distribution, open the group and toggle "Enable Auto-Rotation" — the system will route incoming tickets to available members based on workload.',
      'For fine-grained control, open the "Assignment Configuration" page to set Managers and Team Leads within the group.',
    ],
    tip: '@mentioning a user group in a channel is faster than @mentioning each person individually.',
    keywords: ['user groups', 'teams', 'roles', 'auto-assignment', 'assignment config'],
    category: 'admin',
    icon: Users,
    visualKey: 'user-groups',
  },
  {
    id: 'user-management',
    title: 'User Management',
    tagline: 'Control access and role permissions.',
    path: '/resource-access',
    findIn: 'Sidebar -> User Management',
    actions: ['Grant access', 'Adjust permissions', 'Audit member rights'],
    steps: [
      'Click User Management [[ShieldUser]] in the left sidebar (Admins only).',
      'The member table shows all workspace users with their role and last active date.',
      'Click a user row to open their profile and change their role: Member or Admin.',
      'To invite a new user, enter their email and click "Send Invitation" to send the invite.',
      'To remove access, click the remove button [[X]] on a user row to remove them from the workspace.',
    ],
    tip: 'Assign the "Admin" role only to users who need to manage workspace settings and members.',
    keywords: ['user management', 'permissions', 'access'],
    category: 'admin',
    icon: ShieldUser,
    visualKey: 'user-management',
  },
  {
    id: 'analytics',
    title: 'Analytics',
    tagline: 'Track key performance and operational KPIs.',
    path: '/analytics',
    findIn: 'Sidebar -> Analytics',
    actions: ['Open metric dashboards', 'Inspect trends', 'Compare date ranges'],
    steps: [
      'Click Analytics [[ChartSpline]] in the left sidebar to open the main analytics view.',
      'The overview shows KPI cards: e.g. "Messages sent: 2,340", "Tickets resolved: 87", "Call duration: 14h".',
      'Click any KPI card to drill into a time-series chart for that metric.',
      'Use the date picker to compare ranges — e.g. "Apr 1–15" vs "Mar 1–15".',
    ],
    tip: 'Use the date picker to compare performance across different time periods — e.g. this month vs. last month.',
    keywords: ['analytics', 'metrics', 'kpi'],
    category: 'data',
    icon: BarChart3,
    visualKey: 'analytics',
  },
  {
    id: 'apps',
    title: 'Apps',
    tagline: 'Connect and manage app integrations.',
    path: '/apps',
    findIn: 'Sidebar -> Apps',
    actions: ['Explore integrations', 'Connect tools', 'Manage app status'],
    steps: [
      'Click Apps [[AppWindow]] in the left sidebar to open the Xyne Apps management page.',
      'The page lists all custom apps (bots and webhook integrations) configured for your workspace.',
      'Each app has a generated JWT token used to authenticate webhook calls — copy it from the app detail view.',
    ],
    tip: 'Use Xyne Apps to connect external tools via webhooks and automate notifications into your workspace channels.',
    keywords: ['apps', 'integrations', 'connectors'],
    category: 'admin',
    icon: AppWindow,
    visualKey: 'apps',
  },
  {
    id: 'rca',
    title: 'RCA',
    tagline: 'Root Cause Analysis workflows for incident review.',
    path: '/tickets/:ticketId/workflow',
    findIn: 'Ticket Detail -> Workflow/RCA tab',
    actions: ['Create RCA entries', 'Document causes', 'Track follow-up actions'],
    steps: [
      'Open a ticket detail and go to its Workflow area. If RCA is enabled for that ticket flow, open the RCA tab.',
      'Click "New RCA" and fill in the incident title — e.g. "API Outage – Apr 22, 02:14 UTC".',
      'Fill in the sections: Attribution, RCA (root cause), Impact, and COE (Correction of Errors).',
      'Assign follow-up action items to team members — e.g. "Alice Chen: Add DB connection pool limit".',
    ],
    tip: 'Link the RCA to the original incident ticket so the full history is connected in one place.',
    keywords: ['rca', 'root cause', 'incident'],
    category: 'power-tools',
    icon: ClipboardCheck,
    visualKey: 'rca',
  },
  {
    id: 'shortcuts',
    title: 'Keyboard Shortcuts',
    tagline: 'Use shortcuts to move faster through the product.',
    findIn: 'Global -> Shortcuts Help',
    shortcut: '?',
    actions: ['Open shortcuts modal', 'Learn key actions', 'Speed up routine workflows'],
    steps: [
      'Press Cmd+Shift+/ (Mac) or Ctrl+Shift+/ (Windows/Linux) from anywhere in the app to open the Keyboard Shortcuts modal.',
      'Browse shortcuts grouped by category: Navigation, Chat, Tickets, and Global.',
      'Use Cmd+K / Ctrl+K to open Global Search — the most important shortcut to learn first.',
      'Close any modal or panel with the Escape key.',
    ],
    tip: 'Print or bookmark the shortcuts cheat sheet — learning 5 shortcuts saves hours per month.',
    keywords: ['shortcuts', 'keyboard', 'productivity'],
    category: 'power-tools',
    icon: Wrench,
    visualKey: 'shortcuts',
  },
  // ─────────────────────────────────────────────────────────────────
  // COMMUNICATE additions
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'emoji-reactions',
    title: 'Emoji Reactions',
    tagline: 'React to any message with an emoji in one click.',
    findIn: 'Chat -> Hover a message -> Emoji button',
    actions: ['Add an emoji reaction', 'Toggle reaction off', 'View who reacted'],
    steps: [
      'Hover over any message in a channel or DM — the hover toolbar appears on the right.',
      'Click the emoji button [[SmilePlus]] in the toolbar to open the emoji picker.',
      'Browse or search for an emoji — e.g. type "thumbs" to find the thumbs-up emoji quickly.',
      'Click the emoji to add your reaction. It appears below the message with a count.',
      'Click the same emoji again directly below the message to remove your reaction.',
      'Hover over a reaction count to see the list of people who reacted.',
    ],
    tip: 'Add a checkmark reaction to signal "done" or "acknowledged" without sending a reply that clutters the thread.',
    keywords: ['emoji', 'reactions', 'like', 'thumbs up'],
    category: 'messaging',
    icon: SmilePlus,
    visualKey: 'emoji-reactions',
  },
  {
    id: 'user-profile',
    title: 'User Profiles',
    tagline: 'View teammate details, presence, and common channels.',
    path: '/chat/dir',
    findIn: 'Click any avatar -> Profile',
    actions: [
      'Open a profile',
      'Edit your own profile',
      'Start a DM or call from profile',
      'Edit display name, team, and phone',
    ],
    steps: [
      "Click on any teammate's avatar or name anywhere in the app to open their profile panel.",
      'The profile shows their name, presence (Online / Away), custom status, email, and team.',
      'Click "Message" to start a DM directly from the profile panel without navigating elsewhere.',
      'Click the call button [[Headphones]] to start a call with that person immediately.',
      'To edit your own profile, click your account menu at the bottom of the sidebar, then click Profile [[User]]. Update your display name, team, and phone number, then press Enter to save.',
    ],
    tip: 'The "Common Channels" section at the bottom of a profile shows every channel you share — great for knowing who to loop in.',
    keywords: [
      'profile',
      'avatar',
      'presence',
      'status',
      'teammate',
      'display name',
      'phone',
      'team',
    ],
    category: 'messaging',
    icon: CircleUser,
    visualKey: 'user-profile',
  },
  // ─────────────────────────────────────────────────────────────────
  // WORK additions
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'my-tickets',
    title: 'My Tickets',
    tagline: 'Your personal Kanban board showing only tickets assigned to you.',
    path: '/my-tickets',
    findIn: 'Sidebar -> My Tickets',
    actions: ['See all your assigned tickets', 'Update ticket status', 'Plan daily work'],
    steps: [
      'Click My Tickets [[Filter]] in the left sidebar (also accessible from the Tickets directory) to open your personal board.',
      'The board shows only tickets assigned to you, organized by status column.',
      'Drag a ticket card across columns — e.g. from "In Progress" to "In Review" — to update its status.',
      'Click any card to open the full ticket detail panel on the right.',
      'Use the priority filter in the toolbar to surface Critical and High tickets first.',
    ],
    tip: "Start each morning by opening My Tickets — it's your single source of truth for what to work on today.",
    keywords: ['my tickets', 'personal board', 'assigned', 'my work'],
    category: 'work-tracking',
    icon: Filter,
    visualKey: 'my-tickets',
  },
  {
    id: 'ticket-detail',
    title: 'Ticket Detail',
    tagline: 'Full ticket view with sub-tickets, related tickets, and attachments.',
    path: '/tickets',
    findIn: 'Tickets list or Kanban board -> Click any ticket',
    actions: ['Add sub-tickets', 'Link related items'],
    steps: [
      'Click any ticket in the list or board to open the full detail panel.',
      'Set the assignee using the "Assignee" dropdown.',
      'Add tags by clicking the "+ Tag" button and typing from the project-wide tag list.',
      'Scroll to "Sub-Tickets" and click "Create Sub-Ticket" to create a child task linked to this ticket.',
      'In "Related Tickets", click "+ Add ticket" to link related tickets with a relation type (e.g. "Linked", "Possible duplicate", "Duplicate").',
      'The Activity tab at the bottom shows a full audit trail: every status change, comment, and assignment change.',
    ],
    tip: 'Sub-tickets are ideal for breaking down a large feature ticket — the parent ticket tracks overall progress automatically.',
    keywords: ['ticket detail', 'sub-tickets', 'references', 'assignee', 'attachments', 'activity'],
    category: 'work-tracking',
    icon: ClipboardList,
    visualKey: 'ticket-detail',
  },
  {
    id: 'ticket-views',
    title: 'Ticket Board Views',
    tagline: 'Switch between Kanban, Table, and Calendar layouts.',
    path: '/projects',
    findIn: 'Projects Board or My Tickets -> View switcher (top-right toolbar)',
    actions: ['Switch view', 'Use calendar view', 'Apply column filters'],
    steps: [
      'Open any project board or My Tickets.',
      'Click the view switcher icons in the top-right toolbar to switch between Kanban, Table, or Calendar view.',
      'In Kanban view, drag cards across stages.',
      'In Table view, you can bulk-edit multiple tickets at once by selecting checkboxes on the left.',
      'In Calendar view, tickets with ETAs appear on their due date on the calendar grid.',
      'Use the filter icon [[Filter]] in the toolbar to filter tickets by status, priority, assignee, tags, or any dynamic form field.',
    ],
    tip: 'Calendar view is the fastest way to spot scheduling conflicts across your project — try it before sprint planning.',
    keywords: ['kanban', 'list view', 'table view', 'calendar', 'filter', 'board view'],
    category: 'work-tracking',
    icon: LayoutDashboard,
    visualKey: 'ticket-views',
  },
  // ─────────────────────────────────────────────────────────────────
  // ADMIN additions
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'settings-panel',
    title: 'Settings & Preferences',
    tagline: 'Control your status, theme, notifications, and assignment availability.',
    findIn: 'Bottom of sidebar -> Your avatar / name',
    actions: ['Set presence status', 'Pause notifications', 'Change theme', 'Log out'],
    steps: [
      'Click your avatar [[CircleUser]] or name at the very bottom of the left sidebar to open the Settings popover.',
      'Toggle your presence between "Active" and "Away" using the status switch at the top.',
      'Click "Set a custom status" to enter an emoji + text (e.g. "Deep work") and choose when it expires.',
      'Click Pause notifications [[Bell]] and pick a duration — e.g. "For 1 hour" — to silence all alerts temporarily.',
      'Under Appearance, click a theme swatch — Classic or Summer Breeze — to apply it instantly.',
      'Click "Profile" [[User]] to open and edit your full profile from the same popover.',
      'Click "Sign out of Xyne Space" at the bottom of the popover to sign out of your current session securely.',
    ],
    tip: 'Use "Pause notifications" before going into a focus block or during off-hours to avoid interruptions.',
    keywords: [
      'settings',
      'preferences',
      'theme',
      'status',
      'notifications',
      'pause',
      'appearance',
      'logout',
      'log out',
      'sign out',
      'meeting detection',
    ],
    category: 'admin',
    icon: SlidersHorizontal,
    visualKey: 'settings-panel',
  },
  // ─────────────────────────────────────────────────────────────────
  // NEW FEATURES
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'channel-rename',
    title: 'Channel Rename',
    tagline: 'Rename a channel to keep it clear and relevant as the team evolves.',
    findIn: 'Chat -> Channel Info panel -> About section -> Channel Name card',
    actions: ['Rename an existing channel', 'Update channel purpose'],
    steps: [
      'Open the channel you want to rename by clicking it in the Chat sidebar.',
      'Click the channel name in the header to open the Channel Info panel.',
      'In the About section, find the "Channel Name" card and click the edit button [[SquarePen]] to enter edit mode.',
      'Type the new name — channel names are lowercase with hyphens, e.g. "platform-engineering".',
      'Click "Save" to confirm. All existing message history stays intact; only the name changes.',
    ],
    tip: 'Notify the team in the channel after renaming — post a quick message like "Renamed to #platform-engineering to better reflect our scope."',
    keywords: ['channel', 'rename', 'channel name', 'edit channel'],
    category: 'messaging',
    icon: PenLine,
    visualKey: 'channel-rename',
  },
  {
    id: 'group-assignment-config',
    title: 'Group Assignment Config',
    tagline: 'Define who can assign and manage tickets within a user group.',
    path: '/user-groups/:userGroupId/assignment-config',
    findIn: 'User Groups -> Select a group -> Auto Assignment -> Assignment Configuration',
    actions: [
      'Set manager roles',
      'Configure team lead permissions',
      'Control ticket routing rules',
    ],
    steps: [
      'Click User Groups [[UsersIcon]] in the left sidebar and open the group you want to configure. (Admins only.)',
      'On the selected group page, click the "Auto Assignment" button, then click ">" to open "Assignment Configuration".',
      'Under "Managers", add the team members who should have manager-level control — e.g. "Alice Chen".',
      'Under "Team Leads", add the members who can assign tickets within the group but with narrower scope.',
      'Toggle "Enable Auto-Rotation" to allow the system to automatically assign tickets to available group members based on workload.',
      'Click "Save" to apply the configuration — changes take effect immediately for new ticket assignments in this group.',
    ],
    tip: 'Use Team Leads for day-to-day ticket routing and reserve Managers for escalations and configuration changes.',
    keywords: ['assignment', 'group', 'manager', 'team lead', 'ticket routing', 'permissions'],
    category: 'admin',
    icon: UserCog,
    visualKey: 'group-assignment-config',
  },
  {
    id: 'duplicate-ticket-detection',
    title: 'Duplicate Ticket Detection',
    tagline: 'Automatically prevents duplicate tickets before they are created.',
    path: '/tickets',
    findIn: 'Tickets -> Create Ticket',
    actions: ['Prevent duplicate tickets', 'Review auto-flagged duplicates'],
    steps: [
      'Start creating a ticket by clicking "Create Ticket" and filling in the title.',
      'Xyne Spaces automatically checks for similar existing tickets in the background as you type — no separate action needed.',
      'If a potential duplicate is detected early, you will be flagged before the ticket is created — review the similar ticket and decide whether to proceed or use the existing one instead.',
    ],
    tip: 'Duplicate detection runs automatically in the background — the system flags potential duplicates early so your team avoids working on the same issue twice.',
    keywords: ['duplicate', 'deduplication', 'similar tickets'],
    category: 'work-tracking',
    icon: Copy,
    visualKey: 'duplicate-ticket-detection',
  },
  // ─────────────────────────────────────────────────────────────────
  // P0 — Message Actions (hover toolbar) — completely undocumented
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'message-actions',
    title: 'Message Actions',
    tagline: 'Act on any message directly from the hover toolbar.',
    findIn: 'Chat -> Hover any message -> toolbar on the right',
    actions: [
      'Create a ticket from a message',
      'Ask AI about a message',
      'Pin, copy link, or forward a message',
      'Mark as unread or subscribe to a thread',
      'Edit or delete your own message',
    ],
    steps: [
      'Hover over any message to reveal the action toolbar on its right side.',
      'Click the emoji button [[SmilePlus]] in the toolbar to add an emoji reaction.',
      'Click the reply button [[MessageCircleMore]] to reply in-thread without navigating away from the channel.',
      'Click "Create Ticket" [[Ticket]] to instantly open a new ticket pre-filled with the message text — no copy-pasting required.',
      'Click the Xyne AI button [[XyneAIStar]] to ask the AI assistant a question in the context of that specific message.',
      'Click More [[MoreVertical]] in the toolbar to open the dropdown with additional actions.',
      'Click Add bookmark [[Bookmark]] to save the message to your Bookmarks.',
      'Click "Subscribe to notifications" [[Bell]] to add yourself to that thread\'s notification list even without replying.',
      'Click "Mark as unread" [[Circle]] to reset the channel unread marker to that message so you can return to it later.',
      'Click "Pin message" [[Pin]] to make it visible to everyone via the Channel Info → Pinned Messages.',
      'Click "Copy link" [[Link]] to copy a deep link you can paste anywhere to jump directly to that message.',
      'Click "Copy message" [[Copy]] to copy the plain text of the message.',
      'Click "Forward message" [[Forward]] to open the Forward Message modal and send to another channel or DM.',
      'Click "Edit" [[SquarePen]] or "Delete" [[Trash2]] to modify or remove the message (available only for your own messages).',
    ],
    tip: '"Create Ticket from message" is the fastest way to turn a bug report or feature idea in chat into a trackable ticket — the message text becomes the ticket description automatically.',
    keywords: [
      'message actions',
      'hover toolbar',
      'pin',
      'copy link',
      'create ticket from message',
      'forward',
      'mark unread',
      'subscribe',
      'edit message',
      'delete message',
      'ask ai',
    ],
    category: 'messaging',
    icon: MousePointerClick,
    visualKey: 'message-actions',
  },
  // ─────────────────────────────────────────────────────────────────
  // P1 — Channel Management
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'channel-management',
    title: 'Channel Management',
    tagline: 'Organise, customise, and control individual channels.',
    findIn: 'Channel header -> Info button or channel name dropdown',
    actions: [
      'Star a channel',
      'Browse all channels',
      'Set per-channel notification level',
      'Add members to a channel',
      'Browse channel content tabs',
      'Archive or leave a channel',
    ],
    steps: [
      'Open a channel and click the channel name at the top of the screen to open the Channel Info panel.',
      'Click the star button [[Star]] in the Channel Info panel to star the channel.',
      'To browse all available channels, open Chat [[Inbox]] and use "Browse channels" [[Search]] to search and join any public channel.',
      'To change notification settings for this channel only, click the bell [[Bell]] in the channel header and choose: All Messages, Mentions Only, or Nothing.',
      'Use the tabs inside the Channel Info panel to browse: About, Members, Notifications, and Settings.',
      'To add more people, click "Add People" in the Channel Info header or type /invite @username in the message box.',
      'To leave a channel, open the channel options menu [[EllipsisVertical]] in the header and select "Leave Channel" — it is removed from your sidebar but history is preserved.',
      'Admins can archive a channel from the same three-dot menu by selecting "Archive Channel" — archived channels become read-only and are hidden from new members.',
      'Channel admins can rename the channel, update its description, or convert it between public and private via Channel Settings.',
    ],
    tip: 'Star your 3–5 most important channels so they remain easy to access.',
    keywords: [
      'channel',
      'star',
      'browse channels',
      'notifications',
      'archive',
      'leave channel',
      'channel info',
      'channel settings',
      'add people',
      'pinned messages',
      'channel tabs',
    ],
    category: 'messaging',
    icon: Info,
    visualKey: 'channel-management',
  },
  // ─────────────────────────────────────────────────────────────────
  // P1 — Forward Message
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'forward-message',
    title: 'Forward Message',
    tagline: 'Send any message to another channel or DM with optional context.',
    findIn: 'Chat -> Hover a message -> More -> Forward Message',
    actions: [
      'Forward a message to a channel',
      'Forward a message to a DM',
      'Add a note before forwarding',
    ],
    steps: [
      'Hover over any message and click [[Forward]] in the hover toolbar to open the Forward Message modal.',
      'The Forward Message modal opens — the original message is shown in a preview at the bottom.',
      'Use the search box to type the destination: a channel name (e.g. "#product") or a teammate\'s name for a DM.',
      'Select the destination from the dropdown results.',
      'Optionally type a note in the text field below the preview — e.g. "FYI — this is related to ticket #1024".',
      'Click "Forward" — the message appears in the destination with a "Forwarded from #source-channel" attribution banner.',
    ],
    tip: 'Use Forward instead of copy-paste to preserve the original author attribution and include a deep link back to the source message.',
    keywords: ['forward', 'forward message', 'share message', 'send to channel', 'attribution'],
    category: 'messaging',
    icon: Forward,
    visualKey: 'forward-message',
  },
  // ─────────────────────────────────────────────────────────────────
  // P1 — Thread Panel Actions
  // ─────────────────────────────────────────────────────────────────
  {
    id: 'thread-panel-actions',
    title: 'Thread Panel',
    tagline: 'Reply, escalate, and act on threads without leaving your channel.',
    findIn: 'Chat -> Hover a message -> Reply in thread -> panel opens on the right',
    actions: [
      'Reply in context',
      'Switch thread tabs (Messages / Details / Files)',
      'Toggle thread notifications',
      'Add context links to a thread',
      'Start a call from a thread',
      'Ask Xyne AI about a thread',
      'Create a ticket from a thread',
      'Open thread in a new window',
      'Expand thread to full view',
      'Close the thread panel',
      'Work with ticket-linked details',
    ],
    steps: [
      'Hover a message in a channel and click the reply icon — or click "X replies" below a message — to open the Thread Panel on the right. Note: threads are only available in channels, not in DMs.',
      'Reply in the thread by typing in the text box at the bottom of the panel and pressing Enter.',
      'Use the navigation tabs at the top of the panel (Messages, Details, Files) based on what is available for that thread.',
      'In the Details tab, update linked ticket fields (assignee, priority, status, tags) without leaving chat.',
      'Click the notification button [[Bell]] in the thread header to subscribe/unsubscribe from thread notifications.',
      'Click the link/context button [[Link]] in the thread header to add relevant channel, message, ticket, file, or user context into the thread.',
      'Click [[Headphones]] in the thread panel header to start a call with the other participants in that thread.',
      'Click [[XyneAIStar]] in the thread panel header to ask the AI to summarise the thread or suggest next actions based on the conversation.',
      'When available, click "Create Ticket" [[Ticket]] in the thread header to convert the discussion into a new ticket.',
      'On desktop, click the external-link button to open the thread in a separate window for side-by-side work.',
      'Click the expand button to open the full thread and ticket detail panel.',
      'Click the close button [[X]] to close the thread panel and return to the channel view.',
    ],
    tip: 'Use the Thread Panel Details tab to update ticket fields inline — it is faster than opening the full ticket page when you just need to change status or assignee.',
    keywords: [
      'thread',
      'thread panel',
      'reply',
      'details tab',
      'workflows tab',
      'call from thread',
      'expand thread',
      'ask ai thread',
      'thread tabs',
    ],
    category: 'messaging',
    icon: PanelRight,
    visualKey: 'thread-panel-actions',
  },
  {
    id: 'ticket-thread-panel',
    title: 'Ticket Thread Panel',
    tagline: 'Manage ticket-linked conversations in a dedicated panel.',
    findIn: 'Open a ticket-linked thread from Chat',
    actions: [
      'Review ticket context',
      'Update ticket fields',
      'Navigate ticket details',
      'Use ticket-thread header actions (notifications, copy link, workflow, call)',
      'Access RCA context when present',
    ],
    steps: [
      'Open a thread attached to a ticket from a channel conversation.',
      'Use the ticket-thread header controls as needed: notification toggle [[Bell]], expand view, add context [[Link]], Ask AI [[XyneAIStar]], open in new window (desktop), trigger workflow, copy ticket link [[Link]], start call [[Headphones]], and close [[X]].',
      'In the thread panel, use the Details area to review and update ticket fields like assignee, priority, and status.',
      'Use Files and related context blocks to inspect ticket evidence without leaving chat.',
      'When the ticket includes RCA metadata, review it from the ticket context view before escalating or resolving.',
    ],
    tip: 'Treat chat thread panel and ticket thread panel as separate workflows: chat threads for conversation, ticket threads for execution context.',
    keywords: [
      'ticket thread',
      'thread details',
      'rca context',
      'chat thread panel',
      'ticket panel',
    ],
    category: 'messaging',
    icon: PanelRight,
    visualKey: 'ticket-thread-panel',
  },
];
