// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const alertCircle: IconVariants = {
  "Stroke": [
    ["path", {"d":"M12 12.6241V8.62412M12 15.9991V16.0002M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12ZM13 15.9999V15.9988C13 15.4465 12.5523 14.9988 12 14.9988C11.4477 14.9988 11 15.4465 11 15.9988V15.9999C11 16.5522 11.4477 16.9999 12 16.9999C12.5523 16.9999 13 16.5522 13 15.9999ZM13 12.6238V8.62375C13 8.07147 12.5523 7.62375 12 7.62375C11.4477 7.62375 11 8.07147 11 8.62375V12.6238C11 13.176 11.4477 13.6238 12 13.6238C12.5523 13.6238 13 13.176 13 12.6238Z","fill":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21Z","fill":"currentColor","opacity":0.28,"key":"c0"}],
    ["path", {"d":"M12 12.6241V8.62412M12 15.9991V16.0002M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z","stroke":"currentColor","key":"c1"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21Z","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M12 12.6241V8.62415M12 15.9991V16.0003","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2Z","fill":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M12 12.6238V8.62378M12 15.9988V15.9999","stroke":"currentColor","key":"d1"}],
  ],
};

export const AlertCircle = createPikaIcon("alert-circle", alertCircle);
export default AlertCircle;
