// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const barchartLine: IconVariants = {
  "Stroke": [
    ["path", {"d":"M6 20V14M12 20L12 4M18 20V10","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M6 20V14M12 20L12 4M18 20V10","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M6 20V14M12 20L12 4M18 20V10","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M6 20V14M18 20V10","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M12 20V4","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M6 20V14M12 20L12 4M18 20V10","stroke":"currentColor","key":"s0"}],
  ],
};

export const BarchartLine = createPikaIcon("barchart-line", barchartLine);
export default BarchartLine;
