// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const baseline: IconVariants = {
  "Stroke": [
    ["path", {"d":"M6 16L8.98243 7.54967C9.90866 4.92532 10.3718 3.61315 11.0542 3.24688C11.6449 2.92983 12.3551 2.92983 12.9458 3.24688C13.6282 3.61315 14.0913 4.92532 15.0176 7.54967L18 16M8 11H16M17 20L7 20","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M6 16L8.98243 7.54967C9.90866 4.92532 10.3718 3.61315 11.0542 3.24688C11.6449 2.92983 12.3551 2.92983 12.9458 3.24688C13.6282 3.61315 14.0913 4.92532 15.0176 7.54967L18 16M8 11H16M17 20L7 20","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M6 16L8.98243 7.54967C9.90866 4.92532 10.3718 3.61315 11.0542 3.24688C11.6449 2.92983 12.3551 2.92983 12.9458 3.24688C13.6282 3.61315 14.0913 4.92532 15.0176 7.54967L18 16M8 11H16M17 20L7 20","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M17 20L7 20","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M6 16L8.98243 7.54967C9.90866 4.92532 10.3718 3.61315 11.0542 3.24688C11.6449 2.92983 12.3551 2.92983 12.9458 3.24688C13.6282 3.61315 14.0913 4.92532 15.0176 7.54967L18 16M8 11H16","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M6 16L8.98243 7.54967C9.90866 4.92532 10.3718 3.61315 11.0542 3.24688C11.6449 2.92983 12.3551 2.92983 12.9458 3.24688C13.6282 3.61315 14.0913 4.92532 15.0176 7.54967L18 16M8 11H16M17 20L7 20","stroke":"currentColor","key":"s0"}],
  ],
};

export const Baseline = createPikaIcon("baseline", baseline);
export default Baseline;
