// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const burgerMenuTwo: IconVariants = {
  "Stroke": [
    ["path", {"d":"M4 16H20M4 8H20","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M4 16H20M4 8H20","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M4 16H20M4 8H20","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M4 8H20","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M4 16H20","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M4 16H20M4 8H20","stroke":"currentColor","key":"s0"}],
  ],
};

export const BurgerMenuTwo = createPikaIcon("burger-menu-two", burgerMenuTwo);
export default BurgerMenuTwo;
