// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const checkTickSingle: IconVariants = {
  "Stroke": [
    ["path", {"d":"M5.5 12.5L10.0168 17.7247L10.4177 17.0238C12.5668 13.2658 15.541 10.0448 19.1161 7.60354L20 7","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M5.5 12.5L10.0168 17.7247L10.4177 17.0238C12.5668 13.2658 15.541 10.0448 19.1161 7.60354L20 7","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M5.5 12.5L10.0168 17.7247L10.4177 17.0238C12.5668 13.2658 15.541 10.0448 19.1161 7.60354L20 7","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M5.5 12.5L10.0168 17.7247L10.4177 17.0238C12.5668 13.2658 15.541 10.0448 19.1161 7.60354L20 7","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M5.5 12.5L10.0168 17.7247","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M5.5 12.5L10.0168 17.7247L10.4177 17.0238C12.5668 13.2658 15.541 10.0448 19.1161 7.60354L20 7","stroke":"currentColor","key":"s0"}],
  ],
};

export const CheckTickSingle = createPikaIcon("check-tick-single", checkTickSingle);
export default CheckTickSingle;
