// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const cryptoCurrencyPolygon: IconVariants = {
  "Stroke": [
    ["path", {"d":"M12 7.48718V6.66667L7.5 4L3 6.66667V12L7.5 14.6667L16.5 9.33333L21 12V17.3333L16.5 20L12 17.3333V16.4615","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M12 7.48718V6.66667L7.5 4L3 6.66667V12L7.5 14.6667L16.5 9.33333L21 12V17.3333L16.5 20L12 17.3333V16.4615","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M12 7.48718V6.66667L7.5 4L3 6.66667V12L7.5 14.6667L16.5 9.33333L21 12V17.3333L16.5 20L12 17.3333V16.4615","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M12 7.48718V6.66667L7.5 4L3 6.66667V12L7.5 14.6667L16.5 9.33333L21 12V17.3333L16.5 20L12 17.3333V16.4615","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M3 12V6.66667L7.5 4L12 6.66667V7.48718M21 12V17.3333L16.5 20L12 17.3333V16.4615","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M12 7.48718V6.66667L7.5 4L3 6.66667V12L7.5 14.6667L16.5 9.33333L21 12V17.3333L16.5 20L12 17.3333V16.4615","stroke":"currentColor","key":"s0"}],
  ],
};

export const CryptoCurrencyPolygon = createPikaIcon("crypto-currency-polygon", cryptoCurrencyPolygon);
export default CryptoCurrencyPolygon;
