// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const currencySignRupees: IconVariants = {
  "Stroke": [
    ["path", {"d":"M5 4H11.0208M11.0208 4H19M11.0208 4C13.7741 4 16.0093 6.2259 16.0207 8.97917L16.0208 9M15 21L5.5 14H11.0208C13.7834 14 16.021 11.76 16.0208 9M16.0208 9H5M16.0208 9H19","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M5 4H11.0208M11.0208 4H19M11.0208 4C13.7741 4 16.0093 6.2259 16.0207 8.97917L16.0208 9M15 21L5.5 14H11.0208C13.7834 14 16.021 11.76 16.0208 9M16.0208 9H5M16.0208 9H19","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M5 4H11.0208M11.0208 4H19M11.0208 4C13.7741 4 16.0093 6.2259 16.0207 8.97917L16.0208 9M15 21L5.5 14H11.0208C13.7834 14 16.021 11.76 16.0208 9M16.0208 9H5M16.0208 9H19","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M5 9H19","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M5 4H11.0208M11.0208 4H19M11.0208 4C13.7741 4 16.0093 6.2259 16.0207 8.97917C16.0323 11.7487 13.7904 14 11.0208 14H5.5L15 21","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M5 4H11.0208M11.0208 4H19M11.0208 4C13.7741 4 16.0093 6.2259 16.0207 8.97917L16.0208 9M15 21L5.5 14H11.0208C13.7834 14 16.021 11.76 16.0208 9M16.0208 9H5M16.0208 9H19","stroke":"currentColor","key":"s0"}],
  ],
};

export const CurrencySignRupees = createPikaIcon("currency-sign-rupees", currencySignRupees);
export default CurrencySignRupees;
