// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const encryptedLock: IconVariants = {
  "Stroke": [
    ["path", {"d":"M16 9V7C16 4.79086 14.2091 3 12 3C9.79086 3 8 4.79086 8 7V9M5 13H13M5 17H11M5 21H9M16 13H19M14 17H19M12 21H19","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M16 9V7C16 4.79086 14.2091 3 12 3C9.79086 3 8 4.79086 8 7V9M5 13H13M5 17H11M5 21H9M16 13H19M14 17H19M12 21H19","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M16 9V7C16 4.79086 14.2091 3 12 3C9.79086 3 8 4.79086 8 7V9M5 13H13M5 17H11M5 21H9M16 13H19M14 17H19M12 21H19","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M5 17H11M16 13H19M12 21H19","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M16 9V7C16 4.79086 14.2091 3 12 3C9.79086 3 8 4.79086 8 7V9M5 13H13M5 21H9M14 17H19","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M16 9V7C16 4.79086 14.2091 3 12 3C9.79086 3 8 4.79086 8 7V9M5 13H13M5 17H11M5 21H9M16 13H19M14 17H19M12 21H19","stroke":"currentColor","key":"s0"}],
  ],
};

export const EncryptedLock = createPikaIcon("encrypted-lock", encryptedLock);
export default EncryptedLock;
