// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const equalsDefault: IconVariants = {
  "Stroke": [
    ["path", {"d":"M5 9H19M5 15H19","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M5 9H19M5 15H19","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M5 9H19M5 15H19","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M5 15H19","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M5 9H19","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M5 9H19M5 15H19","stroke":"currentColor","key":"s0"}],
  ],
};

export const EqualsDefault = createPikaIcon("equals-default", equalsDefault);
export default EqualsDefault;
