// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const filterLines: IconVariants = {
  "Stroke": [
    ["path", {"d":"M8 12H16M11 18H13M4 6H20","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M8 12H16M11 18H13M4 6H20","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M8 12H16M11 18H13M4 6H20","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M8 12H16M11 18H13","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M4 6H20","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M8 12H16M11 18H13M4 6H20","stroke":"currentColor","key":"s0"}],
  ],
};

export const FilterLines = createPikaIcon("filter-lines", filterLines);
export default FilterLines;
