// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const fontTt: IconVariants = {
  "Stroke": [
    ["path", {"d":"M17 19V13M10 19V5M14 13H20M4 5H16","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M17 19V13M10 19V5M14 13H20M4 5H16","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M17 19V13M10 19V5M14 13H20M4 5H16","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M10 19V5M4 5H16","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M17 19V13M14 13H20","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M17 19V13M10 19V5M14 13H20M4 5H16","stroke":"currentColor","key":"s0"}],
  ],
};

export const FontTt = createPikaIcon("font-tt", fontTt);
export default FontTt;
