// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const graphChartAverage: IconVariants = {
  "Stroke": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3M7 7L7.22319 6.72367C8.61414 5.00154 11.3274 5.32747 12.2709 7.33003L15.7291 14.67C16.6726 16.6725 19.3859 16.9985 20.7768 15.2763L21 15M6 11H6.01M10 11H10.01M18 11H18.01M22 11H22.01","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3M7 7L7.22319 6.72367C8.61414 5.00154 11.3274 5.32747 12.2709 7.33003L15.7291 14.67C16.6726 16.6725 19.3859 16.9985 20.7768 15.2763L21 15M6 11H6.01M10 11H10.01M18 11H18.01M22 11H22.01","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3M7 7L7.22319 6.72367C8.61414 5.00154 11.3274 5.32747 12.2709 7.33003L15.7291 14.67C16.6726 16.6725 19.3859 16.9985 20.7768 15.2763L21 15M6 11H6.01M10 11H10.01M18 11H18.01M22 11H22.01","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M7 7.00009L7.22319 6.72376C8.61414 5.00163 11.3274 5.32756 12.2709 7.33012L15.7291 14.6701C16.6726 16.6726 19.3859 16.9986 20.7768 15.2764L21 15.0001M6 11.0001H6.01M10 11.0001H10.01M18 11.0001H18.01M22 11.0001H22.01","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3M7 7L7.22319 6.72367C8.61414 5.00154 11.3274 5.32747 12.2709 7.33003L15.7291 14.67C16.6726 16.6725 19.3859 16.9985 20.7768 15.2763L21 15M6 11H6.01M10 11H10.01M18 11H18.01M22 11H22.01","stroke":"currentColor","key":"s0"}],
  ],
};

export const GraphChartAverage = createPikaIcon("graph-chart-average", graphChartAverage);
export default GraphChartAverage;
