// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const graphChartWaterfall: IconVariants = {
  "Stroke": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3M8 17V14M12 13V10M16 9V6M20 17V3","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3M8 17V14M12 13V10M16 9V6M20 17V3","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3M8 17V14M12 13V10M16 9V6M20 17V3","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M8 17V14M12 13V10M16 9V6M20 17V3","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3M8 17V14M12 13V10M16 9V6M20 17V3","stroke":"currentColor","key":"s0"}],
  ],
};

export const GraphChartWaterfall = createPikaIcon("graph-chart-waterfall", graphChartWaterfall);
export default GraphChartWaterfall;
