// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const hashtag: IconVariants = {
  "Stroke": [
    ["path", {"d":"M7 20L7.9375 15M7.9375 15L9.0625 9M7.9375 15H14.9375M7.9375 15H3.5M9.0625 9L10 4M9.0625 9L16.0625 9M9.0625 9H4.5M14 20L14.9375 15M14.9375 15L16.0625 9M14.9375 15H19.5M16.0625 9L17 4M16.0625 9H20.5","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M7 20L7.9375 15M7.9375 15L9.0625 9M7.9375 15H14.9375M7.9375 15H3.5M9.0625 9L10 4M9.0625 9L16.0625 9M9.0625 9H4.5M14 20L14.9375 15M14.9375 15L16.0625 9M14.9375 15H19.5M16.0625 9L17 4M16.0625 9H20.5","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M7 20L7.9375 15M7.9375 15L9.0625 9M7.9375 15H14.9375M7.9375 15H3.5M9.0625 9L10 4M9.0625 9L16.0625 9M9.0625 9H4.5M14 20L14.9375 15M14.9375 15L16.0625 9M14.9375 15H19.5M16.0625 9L17 4M16.0625 9H20.5","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M7 20L10 4M14 20L17 4","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M19.5 15H3.5M20.5 9H4.5","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M7 20L7.9375 15M7.9375 15L9.0625 9M7.9375 15H14.9375M7.9375 15H3.5M9.0625 9L10 4M9.0625 9L16.0625 9M9.0625 9H4.5M14 20L14.9375 15M14.9375 15L16.0625 9M14.9375 15H19.5M16.0625 9L17 4M16.0625 9H20.5","stroke":"currentColor","key":"s0"}],
  ],
};

export const Hashtag = createPikaIcon("hashtag", hashtag);
export default Hashtag;
