// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const headingH6: IconVariants = {
  "Stroke": [
    ["path", {"d":"M4 12H12M4 18V6M12 18V6M16 16C16 17.1046 16.8954 18 18 18H19C20.1046 18 21 17.1046 21 16C21 14.8954 20.1046 14 19 14H18C16.8954 14 16 14.8954 16 16ZM16 16V12C16 10.8954 16.8954 10 18 10H19C19.7403 10 20.3866 10.4022 20.7324 11","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M4 12H12M4 18V6M12 18V6M16 16C16 17.1046 16.8954 18 18 18H19C20.1046 18 21 17.1046 21 16C21 14.8954 20.1046 14 19 14H18C16.8954 14 16 14.8954 16 16ZM16 16V12C16 10.8954 16.8954 10 18 10H19C19.7403 10 20.3866 10.4022 20.7324 11","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M4 12H12M4 18V6M12 18V6M16 16C16 17.1046 16.8954 18 18 18H19C20.1046 18 21 17.1046 21 16C21 14.8954 20.1046 14 19 14H18C16.8954 14 16 14.8954 16 16ZM16 16V12C16 10.8954 16.8954 10 18 10H19C19.7403 10 20.3866 10.4022 20.7324 11","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M4 12H12M4 18V6M12 18V6","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M16 16C16 17.1046 16.8954 18 18 18H19C20.1046 18 21 17.1046 21 16C21 14.8954 20.1046 14 19 14H18C16.8954 14 16 14.8954 16 16ZM16 16V12C16 10.8954 16.8954 10 18 10H19C19.7403 10 20.3866 10.4022 20.7324 11","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M4 12H12M4 18V6M12 18V6M16 16C16 17.1046 16.8954 18 18 18H19C20.1046 18 21 17.1046 21 16C21 14.8954 20.1046 14 19 14H18C16.8954 14 16 14.8954 16 16ZM16 16V12C16 10.8954 16.8954 10 18 10H19C19.7403 10 20.3866 10.4022 20.7324 11","stroke":"currentColor","key":"s0"}],
  ],
};

export const HeadingH6 = createPikaIcon("heading-h6", headingH6);
export default HeadingH6;
