// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const informationCircle: IconVariants = {
  "Stroke": [
    ["path", {"d":"M12 11.9999V15.9999M12 8.6249V8.62378M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12ZM13 8.6239C13 8.07162 12.5523 7.6239 12 7.6239C11.4477 7.6239 11 8.07162 11 8.6239V8.62503C11 9.17731 11.4477 9.62503 12 9.62503C12.5523 9.62503 13 9.17731 13 8.62503V8.6239ZM13 12C13 11.4477 12.5523 11 12 11C11.4477 11 11 11.4477 11 12V16C11 16.5523 11.4477 17 12 17C12.5523 17 13 16.5523 13 16V12Z","fill":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21Z","fill":"currentColor","opacity":0.28,"key":"c0"}],
    ["path", {"d":"M12 11.9999V15.9999M12 8.6249V8.62378M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z","stroke":"currentColor","key":"c1"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21Z","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M12 11.9999V15.9999M12 8.6249V8.62378","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2Z","fill":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M12 12V16M12 8.62503V8.6239","stroke":"currentColor","key":"d1"}],
  ],
};

export const InformationCircle = createPikaIcon("information-circle", informationCircle);
export default InformationCircle;
