// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const keyRight: IconVariants = {
  "Stroke": [
    ["path", {"d":"M10 12C10 14.2091 8.20914 16 6 16C3.79086 16 2 14.2091 2 12C2 9.79086 3.79086 8 6 8C8.20914 8 10 9.79086 10 12ZM10 12H22V15M18 12V14","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M6 7C8.41896 7 10.4367 8.71776 10.9 11H22C22.5523 11 23 11.4477 23 12V15C23 15.5523 22.5523 16 22 16C21.4477 16 21 15.5523 21 15V13H19V14C19 14.5523 18.5523 15 18 15C17.4477 15 17 14.5523 17 14V13H10.9C10.4367 15.2822 8.41896 17 6 17C3.23858 17 1 14.7614 1 12C1 9.23858 3.23858 7 6 7Z","fill":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M2 12C2 14.2091 3.79086 16 6 16C8.20914 16 10 14.2091 10 12C10 9.79086 8.20914 8 6 8C3.79086 8 2 9.79086 2 12Z","fill":"currentColor","opacity":0.28,"key":"c0"}],
    ["path", {"d":"M10 12C10 14.2091 8.20914 16 6 16C3.79086 16 2 14.2091 2 12C2 9.79086 3.79086 8 6 8C8.20914 8 10 9.79086 10 12ZM10 12H22V15M18 12V14","stroke":"currentColor","key":"c1"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M18 12H22V15M18 12H10M18 12V14","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M2 12C2 14.2091 3.79086 16 6 16C8.20914 16 10 14.2091 10 12C10 9.79086 8.20914 8 6 8C3.79086 8 2 9.79086 2 12Z","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M18 12H22V15M18 12H10M18 12V14","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M6 7C8.76142 7 11 9.23858 11 12C11 14.7614 8.76142 17 6 17C3.23858 17 1 14.7614 1 12C1 9.23858 3.23858 7 6 7Z","fill":"currentColor","key":"d1"}],
  ],
};

export const KeyRight = createPikaIcon("key-right", keyRight);
export default KeyRight;
