// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const linkHorizontal: IconVariants = {
  "Stroke": [
    ["path", {"d":"M15 12H9M15 7H16C18.7614 7 21 9.23858 21 12C21 14.7614 18.7614 17 16 17H15M9 7H8C5.23858 7 3 9.23858 3 12C3 14.7614 5.23858 17 8 17H9","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M15 12H9M15 7H16C18.7614 7 21 9.23858 21 12C21 14.7614 18.7614 17 16 17H15M9 7H8C5.23858 7 3 9.23858 3 12C3 14.7614 5.23858 17 8 17H9","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M15 12H9M15 7H16C18.7614 7 21 9.23858 21 12C21 14.7614 18.7614 17 16 17H15M9 7H8C5.23858 7 3 9.23858 3 12C3 14.7614 5.23858 17 8 17H9","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M15 7H16C18.7614 7 21 9.23858 21 12C21 14.7614 18.7614 17 16 17H15M9 7H8C5.23858 7 3 9.23858 3 12C3 14.7614 5.23858 17 8 17H9","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M15 12H9","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M15 12H9M15 7H16C18.7614 7 21 9.23858 21 12C21 14.7614 18.7614 17 16 17H15M9 7H8C5.23858 7 3 9.23858 3 12C3 14.7614 5.23858 17 8 17H9","stroke":"currentColor","key":"s0"}],
  ],
};

export const LinkHorizontal = createPikaIcon("link-horizontal", linkHorizontal);
export default LinkHorizontal;
