// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const listCheckDouble: IconVariants = {
  "Stroke": [
    ["path", {"d":"M12 12H21M12 18H21M12 6L21 6M3 8.10466L4.89736 10C5.80992 8.40431 7.07282 7.0366 8.59087 6M3 16.1047L4.89736 18C5.80992 16.4043 7.07282 15.0366 8.59087 14","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M12 12H21M12 18H21M12 6L21 6M3 8.10466L4.89736 10C5.80992 8.40431 7.07282 7.0366 8.59087 6M3 16.1047L4.89736 18C5.80992 16.4043 7.07282 15.0366 8.59087 14","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M12 12H21M12 18H21M12 6L21 6M3 8.10466L4.89736 10C5.80992 8.40431 7.07282 7.0366 8.59087 6M3 16.1047L4.89736 18C5.80992 16.4043 7.07282 15.0366 8.59087 14","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M12 12H21M12 18H21M12 6L21 6","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M3 8.10466L4.89736 10C5.80992 8.40431 7.07282 7.0366 8.59087 6M3 16.1047L4.89736 18C5.80992 16.4043 7.07282 15.0366 8.59087 14","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M12 12H21M12 18H21M12 6L21 6M3 8.10466L4.89736 10C5.80992 8.40431 7.07282 7.0366 8.59087 6M3 16.1047L4.89736 18C5.80992 16.4043 7.07282 15.0366 8.59087 14","stroke":"currentColor","key":"s0"}],
  ],
};

export const ListCheckDouble = createPikaIcon("list-check-double", listCheckDouble);
export default ListCheckDouble;
