// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const listRemove: IconVariants = {
  "Stroke": [
    ["path", {"d":"M4 12H10M4 18H10M4 6H20M14 15H20","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M4 12H10M4 18H10M4 6H20M14 15H20","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M4 12H10M4 18H10M4 6H20M14 15H20","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M4 12H10M4 18H10M4 6H20","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M14 15H20","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M4 12H10M4 18H10M4 6H20M14 15H20","stroke":"currentColor","key":"s0"}],
  ],
};

export const ListRemove = createPikaIcon("list-remove", listRemove);
export default ListRemove;
