// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const listLong: IconVariants = {
  "Stroke": [
    ["path", {"d":"M4 9H20M4 14H20M4 19H12M4 4H20","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M4 9H20M4 14H20M4 19H12M4 4H20","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M4 9H20M4 14H20M4 19H12M4 4H20","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M4 14H20M4 4H20","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M4 9H20M4 19H12","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M4 9H20M4 14H20M4 19H12M4 4H20","stroke":"currentColor","key":"s0"}],
  ],
};

export const ListLong = createPikaIcon("list-long", listLong);
export default ListLong;
