// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const minusDefault: IconVariants = {
  "Stroke": [
    ["path", {"d":"M5 12H19","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M5 12H19","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M5 12H19","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M5 12H19","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M9 12H15","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M5 12H19","stroke":"currentColor","key":"s0"}],
  ],
};

export const MinusDefault = createPikaIcon("minus-default", minusDefault);
export default MinusDefault;
