// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const mouseDefault: IconVariants = {
  "Stroke": [
    ["path", {"d":"M12 10V8M12 21C8.13401 21 5 17.866 5 14V10C5 6.13401 8.13401 3 12 3C15.866 3 19 6.13401 19 10V14C19 17.866 15.866 21 12 21Z","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M4 10C4 5.58172 7.58172 2 12 2C16.4183 2 20 5.58172 20 10V14C20 18.4183 16.4183 22 12 22C7.58172 22 4 18.4183 4 14V10ZM13 7.95C13 7.39772 12.5523 6.95 12 6.95C11.4477 6.95 11 7.39772 11 7.95V10.05C11 10.6023 11.4477 11.05 12 11.05C12.5523 11.05 13 10.6023 13 10.05V7.95Z","fill":"currentColor","fillRule":"evenodd","clipRule":"evenodd","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M19 14V10C19 6.13401 15.866 3 12 3C8.13401 3 5 6.13401 5 10V14C5 17.866 8.13401 21 12 21C15.866 21 19 17.866 19 14Z","fill":"currentColor","opacity":0.28,"key":"c0"}],
    ["path", {"d":"M12 10V8M12 21C8.13401 21 5 17.866 5 14V10C5 6.13401 8.13401 3 12 3C15.866 3 19 6.13401 19 10V14C19 17.866 15.866 21 12 21Z","stroke":"currentColor","key":"c1"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M19 14V10C19 6.13401 15.866 3 12 3C8.13401 3 5 6.13401 5 10V14C5 17.866 8.13401 21 12 21C15.866 21 19 17.866 19 14Z","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M12 10V8","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M12 2C7.58172 2 4 5.58172 4 10V14C4 18.4183 7.58172 22 12 22C16.4183 22 20 18.4183 20 14V10C20 5.58172 16.4183 2 12 2Z","fill":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M12 10.05V7.94995","stroke":"currentColor","key":"d1"}],
  ],
};

export const MouseDefault = createPikaIcon("mouse-default", mouseDefault);
export default MouseDefault;
