// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const pauseSmall: IconVariants = {
  "Stroke": [
    ["path", {"d":"M9.50098 9V15M14.4998 9V15","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M9.50098 9V15M14.4998 9V15","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M9.50098 9V15M14.4998 9V15","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M14.5 9V15","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M9.50098 9V15","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M9.50098 9V15M14.4998 9V15","stroke":"currentColor","key":"s0"}],
  ],
};

export const PauseSmall = createPikaIcon("pause-small", pauseSmall);
export default PauseSmall;
