// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const searchDefault: IconVariants = {
  "Stroke": [
    ["path", {"d":"M21 21L14.9497 14.9497M14.9497 14.9497C16.2165 13.683 17 11.933 17 10C17 6.13401 13.866 3 10 3C6.13401 3 3 6.13401 3 10C3 13.866 6.13401 17 10 17C11.933 17 13.683 16.2165 14.9497 14.9497Z","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M10 2C5.58172 2 2 5.58172 2 10C2 14.4183 5.58172 18 10 18C11.8483 18 13.5513 17.3723 14.9056 16.3198L20.2929 21.7071C20.6834 22.0976 21.3166 22.0976 21.7071 21.7071C22.0976 21.3166 22.0976 20.6834 21.7071 20.2929L16.3198 14.9056C17.3723 13.5513 18 11.8483 18 10C18 5.58172 14.4183 2 10 2Z","fill":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M17 10C17 11.933 16.2165 13.683 14.9497 14.9497C13.683 16.2165 11.933 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z","fill":"currentColor","opacity":0.28,"key":"c0"}],
    ["path", {"d":"M21 21L14.9497 14.9497M14.9497 14.9497C16.2165 13.683 17 11.933 17 10C17 6.13401 13.866 3 10 3C6.13401 3 3 6.13401 3 10C3 13.866 6.13401 17 10 17C11.933 17 13.683 16.2165 14.9497 14.9497Z","stroke":"currentColor","key":"c1"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M14.9497 14.9492L21 20.9995","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M17 10C17 11.933 16.2165 13.683 14.9497 14.9497C13.683 16.2165 11.933 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M14.9497 14.9492L21 20.9995","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M10 2C5.58172 2 2 5.58172 2 10C2 14.4183 5.58172 18 10 18C12.2089 18 14.2102 17.1035 15.6569 15.6569C17.1035 14.2102 18 12.2089 18 10C18 5.58172 14.4183 2 10 2Z","fill":"currentColor","key":"d1"}],
  ],
};

export const SearchDefault = createPikaIcon("search-default", searchDefault);
export default SearchDefault;
