// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const terminalConsoleCircle: IconVariants = {
  "Stroke": [
    ["path", {"d":"M8 13L10 11L8 9M13 13H16M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M2 12C2 6.47716 6.47716 2 12 2C17.5229 2 22 6.47716 22 12C22 17.5229 17.5229 22 12 22C6.47716 22 2 17.5229 2 12ZM8.70711 8.29289C8.31658 7.90237 7.68342 7.90237 7.29289 8.29289C6.90237 8.68342 6.90237 9.31658 7.29289 9.70711L8.58579 11L7.29289 12.2929C6.90237 12.6834 6.90237 13.3166 7.29289 13.7071C7.68342 14.0976 8.31658 14.0976 8.70711 13.7071L10.7071 11.7071C11.0976 11.3166 11.0976 10.6834 10.7071 10.2929L8.70711 8.29289ZM13 12C12.4477 12 12 12.4477 12 13C12 13.5523 12.4477 14 13 14H16C16.5523 14 17 13.5523 17 13C17 12.4477 16.5523 12 16 12H13Z","fill":"currentColor","fillRule":"evenodd","clipRule":"evenodd","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21Z","fill":"currentColor","opacity":0.28,"key":"c0"}],
    ["path", {"d":"M8 13L10 11L8 9M13 13H16M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z","stroke":"currentColor","key":"c1"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21Z","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M8 13L10 11L8 9M13 13H16","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M12 2C6.47716 2 2 6.47716 2 12C2 17.5229 6.47716 22 12 22C17.5229 22 22 17.5229 22 12C22 6.47716 17.5229 2 12 2Z","fill":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M8 13L10 11L8 9M13 13H16","stroke":"currentColor","key":"d1"}],
  ],
};

export const TerminalConsoleCircle = createPikaIcon("terminal-console-circle", terminalConsoleCircle);
export default TerminalConsoleCircle;
