// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const textQuote: IconVariants = {
  "Stroke": [
    ["path", {"d":"M5 8V16","stroke":"currentColor","key":"s0"}],
    ["path", {"d":"M9.5 10H19","stroke":"currentColor","key":"s1"}],
    ["path", {"d":"M9.5 14H19","stroke":"currentColor","key":"s2"}],
  ],
  "Solid": [
    ["path", {"d":"M5 8V16","stroke":"currentColor","key":"s0"}],
    ["path", {"d":"M9.5 10H19","stroke":"currentColor","key":"s1"}],
    ["path", {"d":"M9.5 14H19","stroke":"currentColor","key":"s2"}],
  ],
  "Contrast": [
    ["path", {"d":"M5 8V16","stroke":"currentColor","key":"s0"}],
    ["path", {"d":"M9.5 10H19","stroke":"currentColor","key":"s1"}],
    ["path", {"d":"M9.5 14H19","stroke":"currentColor","key":"s2"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M5 8V16","stroke":"currentColor","key":"s0"}],
    ["path", {"d":"M9.5 10H19","stroke":"currentColor","key":"s1"}],
    ["path", {"d":"M9.5 14H19","stroke":"currentColor","key":"s2"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M5 8V16","stroke":"currentColor","key":"s0"}],
    ["path", {"d":"M9.5 10H19","stroke":"currentColor","key":"s1"}],
    ["path", {"d":"M9.5 14H19","stroke":"currentColor","key":"s2"}],
  ],
};

export const TextQuote = createPikaIcon("text-quote", textQuote);
export default TextQuote;
