// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const textClear: IconVariants = {
  "Stroke": [
    ["path", {"d":"M4 7V4H20V7","stroke":"currentColor","key":"s0"}],
    ["path", {"d":"M5 20H11","stroke":"currentColor","key":"s1"}],
    ["path", {"d":"M13 4L8 20","stroke":"currentColor","key":"s2"}],
    ["path", {"d":"M15 15L20 20","stroke":"currentColor","key":"s3"}],
    ["path", {"d":"M20 15L15 20","stroke":"currentColor","key":"s4"}],
  ],
  "Solid": [
    ["path", {"d":"M4 7V4H20V7","stroke":"currentColor","key":"s0"}],
    ["path", {"d":"M5 20H11","stroke":"currentColor","key":"s1"}],
    ["path", {"d":"M13 4L8 20","stroke":"currentColor","key":"s2"}],
    ["path", {"d":"M15 15L20 20","stroke":"currentColor","key":"s3"}],
    ["path", {"d":"M20 15L15 20","stroke":"currentColor","key":"s4"}],
  ],
  "Contrast": [
    ["path", {"d":"M4 7V4H20V7","stroke":"currentColor","key":"s0"}],
    ["path", {"d":"M5 20H11","stroke":"currentColor","key":"s1"}],
    ["path", {"d":"M13 4L8 20","stroke":"currentColor","key":"s2"}],
    ["path", {"d":"M15 15L20 20","stroke":"currentColor","key":"s3"}],
    ["path", {"d":"M20 15L15 20","stroke":"currentColor","key":"s4"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M4 7V4H20V7","stroke":"currentColor","key":"s0"}],
    ["path", {"d":"M5 20H11","stroke":"currentColor","key":"s1"}],
    ["path", {"d":"M13 4L8 20","stroke":"currentColor","key":"s2"}],
    ["path", {"d":"M15 15L20 20","stroke":"currentColor","key":"s3"}],
    ["path", {"d":"M20 15L15 20","stroke":"currentColor","key":"s4"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M4 7V4H20V7","stroke":"currentColor","key":"s0"}],
    ["path", {"d":"M5 20H11","stroke":"currentColor","key":"s1"}],
    ["path", {"d":"M13 4L8 20","stroke":"currentColor","key":"s2"}],
    ["path", {"d":"M15 15L20 20","stroke":"currentColor","key":"s3"}],
    ["path", {"d":"M20 15L15 20","stroke":"currentColor","key":"s4"}],
  ],
};

export const TextClear = createPikaIcon("text-clear", textClear);
export default TextClear;
