// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const threeDotsMenuVertical: IconVariants = {
  "Stroke": [
    ["path", {"d":"M12 6C11.4477 6 11 5.55228 11 5C11 4.44772 11.4477 4 12 4C12.5523 4 13 4.44772 13 5C13 5.55228 12.5523 6 12 6Z","stroke":"currentColor","key":"s0"}],
    ["path", {"d":"M12 13C11.4477 13 11 12.5523 11 12C11 11.4477 11.4477 11 12 11C12.5523 11 13 11.4477 13 12C13 12.5523 12.5523 13 12 13Z","stroke":"currentColor","key":"s1"}],
    ["path", {"d":"M12 20C11.4477 20 11 19.5523 11 19C11 18.4477 11.4477 18 12 18C12.5523 18 13 18.4477 13 19C13 19.5523 12.5523 20 12 20Z","stroke":"currentColor","key":"s2"}],
  ],
  "Solid": [
    ["path", {"d":"M12 6C11.4477 6 11 5.55228 11 5C11 4.44772 11.4477 4 12 4C12.5523 4 13 4.44772 13 5C13 5.55228 12.5523 6 12 6Z","stroke":"currentColor","key":"s0"}],
    ["path", {"d":"M12 13C11.4477 13 11 12.5523 11 12C11 11.4477 11.4477 11 12 11C12.5523 11 13 11.4477 13 12C13 12.5523 12.5523 13 12 13Z","stroke":"currentColor","key":"s1"}],
    ["path", {"d":"M12 20C11.4477 20 11 19.5523 11 19C11 18.4477 11.4477 18 12 18C12.5523 18 13 18.4477 13 19C13 19.5523 12.5523 20 12 20Z","stroke":"currentColor","key":"s2"}],
  ],
  "Contrast": [
    ["path", {"d":"M12 6C11.4477 6 11 5.55228 11 5C11 4.44772 11.4477 4 12 4C12.5523 4 13 4.44772 13 5C13 5.55228 12.5523 6 12 6Z","stroke":"currentColor","key":"s0"}],
    ["path", {"d":"M12 13C11.4477 13 11 12.5523 11 12C11 11.4477 11.4477 11 12 11C12.5523 11 13 11.4477 13 12C13 12.5523 12.5523 13 12 13Z","stroke":"currentColor","key":"s1"}],
    ["path", {"d":"M12 20C11.4477 20 11 19.5523 11 19C11 18.4477 11.4477 18 12 18C12.5523 18 13 18.4477 13 19C13 19.5523 12.5523 20 12 20Z","stroke":"currentColor","key":"s2"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M12 6C11.4477 6 11 5.55228 11 5C11 4.44772 11.4477 4 12 4C12.5523 4 13 4.44772 13 5C13 5.55228 12.5523 6 12 6Z","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M12 20C11.4477 20 11 19.5523 11 19C11 18.4477 11.4477 18 12 18C12.5523 18 13 18.4477 13 19C13 19.5523 12.5523 20 12 20Z","stroke":"currentColor","opacity":0.28,"key":"d1"}],
    ["path", {"d":"M12 13C11.4477 13 11 12.5523 11 12C11 11.4477 11.4477 11 12 11C12.5523 11 13 11.4477 13 12C13 12.5523 12.5523 13 12 13Z","stroke":"currentColor","key":"d2"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M12 6C11.4477 6 11 5.55228 11 5C11 4.44772 11.4477 4 12 4C12.5523 4 13 4.44772 13 5C13 5.55228 12.5523 6 12 6Z","stroke":"currentColor","key":"s0"}],
    ["path", {"d":"M12 13C11.4477 13 11 12.5523 11 12C11 11.4477 11.4477 11 12 11C12.5523 11 13 11.4477 13 12C13 12.5523 12.5523 13 12 13Z","stroke":"currentColor","key":"s1"}],
    ["path", {"d":"M12 20C11.4477 20 11 19.5523 11 19C11 18.4477 11.4477 18 12 18C12.5523 18 13 18.4477 13 19C13 19.5523 12.5523 20 12 20Z","stroke":"currentColor","key":"s2"}],
  ],
};

export const ThreeDotsMenuVertical = createPikaIcon("three-dots-menu-vertical", threeDotsMenuVertical);
export default ThreeDotsMenuVertical;
