// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const userUser01: IconVariants = {
  "Stroke": [
    ["path", {"d":"M16 7C16 9.20914 14.2091 11 12 11C9.79086 11 8 9.20914 8 7C8 4.79086 9.79086 3 12 3C14.2091 3 16 4.79086 16 7Z","stroke":"currentColor","key":"s0"}],
    ["path", {"d":"M17 15H7C5.34315 15 4 16.3431 4 18C4 19.6569 5.34315 21 7 21H17C18.6569 21 20 19.6569 20 18C20 16.3431 18.6569 15 17 15Z","stroke":"currentColor","key":"s1"}],
  ],
  "Solid": [
    ["path", {"d":"M12 2.25C9.37665 2.25 7.25 4.37665 7.25 7C7.25 9.62335 9.37665 11.75 12 11.75C14.6234 11.75 16.75 9.62335 16.75 7C16.75 4.37665 14.6234 2.25 12 2.25Z","fill":"currentColor","key":"s0"}],
    ["path", {"d":"M3 18C3 15.7909 4.79086 14 7 14H17C19.2091 14 21 15.7909 21 18C21 20.2091 19.2091 22 17 22H7C4.79086 22 3 20.2091 3 18Z","fill":"currentColor","key":"s1"}],
  ],
  "Contrast": [
    ["path", {"d":"M16 7C16 9.20914 14.2091 11 12 11C9.79086 11 8 9.20914 8 7C8 4.79086 9.79086 3 12 3C14.2091 3 16 4.79086 16 7Z","fill":"currentColor","opacity":0.28,"key":"c0"}],
    ["path", {"d":"M17 15H7C5.34315 15 4 16.3431 4 18C4 19.6569 5.34315 21 7 21H17C18.6569 21 20 19.6569 20 18C20 16.3431 18.6569 15 17 15Z","fill":"currentColor","opacity":0.28,"key":"c1"}],
    ["path", {"d":"M16 7C16 9.20914 14.2091 11 12 11C9.79086 11 8 9.20914 8 7C8 4.79086 9.79086 3 12 3C14.2091 3 16 4.79086 16 7Z","stroke":"currentColor","key":"c2"}],
    ["path", {"d":"M17 15H7C5.34315 15 4 16.3431 4 18C4 19.6569 5.34315 21 7 21H17C18.6569 21 20 19.6569 20 18C20 16.3431 18.6569 15 17 15Z","stroke":"currentColor","key":"c3"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M17 15H7C5.34315 15 4 16.3431 4 18C4 19.6569 5.34315 21 7 21H17C18.6569 21 20 19.6569 20 18C20 16.3431 18.6569 15 17 15Z","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M16 7C16 9.20914 14.2091 11 12 11C9.79086 11 8 9.20914 8 7C8 4.79086 9.79086 3 12 3C14.2091 3 16 4.79086 16 7Z","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M7 14C4.79086 14 3 15.7909 3 18C3 20.2091 4.79086 22 7 22H17C19.2091 22 21 20.2091 21 18C21 15.7909 19.2091 14 17 14H7Z","fill":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M12 2.25C9.37665 2.25 7.25 4.37665 7.25 7C7.25 9.62335 9.37665 11.75 12 11.75C14.6234 11.75 16.75 9.62335 16.75 7C16.75 4.37665 14.6234 2.25 12 2.25Z","fill":"currentColor","key":"d1"}],
  ],
};

export const UserUser01 = createPikaIcon("user-user-01", userUser01);
export default UserUser01;
