// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const acDefault: IconVariants = {
  "Stroke": [
    ["path", {"d":"M18 12H16M22 16V10C22 8.89543 21.1046 8 20 8H4C2.89543 8 2 8.89543 2 10V16H22Z","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M1 10C1 8.34315 2.34315 7 4 7H20C21.6569 7 23 8.34315 23 10V16C23 16.5523 22.5523 17 22 17H2C1.44772 17 1 16.5523 1 16V10ZM16 11C15.4477 11 15 11.4477 15 12C15 12.5523 15.4477 13 16 13H18C18.5523 13 19 12.5523 19 12C19 11.4477 18.5523 11 18 11H16Z","fill":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M20 8H4C2.89543 8 2 8.89543 2 10V16H22V10C22 8.89543 21.1046 8 20 8Z","fill":"currentColor","opacity":0.28,"key":"c0"}],
    ["path", {"d":"M18 12H16M22 16V10C22 8.89543 21.1046 8 20 8H4C2.89543 8 2 8.89543 2 10V16H22Z","stroke":"currentColor","key":"c1"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M20 8H4C2.89543 8 2 8.89543 2 10V16H22V10C22 8.89543 21.1046 8 20 8Z","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M18 12H16","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M4 7C2.34315 7 1 8.34315 1 10V16C1 16.5523 1.44772 17 2 17H22C22.5523 17 23 16.5523 23 16V10C23 8.34315 21.6569 7 20 7H4Z","fill":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M18 12H16","stroke":"currentColor","key":"d1"}],
  ],
};

export const AcDefault = createPikaIcon("ac-default", acDefault);
export default AcDefault;
