// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const ceilingLampOff: IconVariants = {
  "Stroke": [
    ["path", {"d":"M12 7C7.02944 7 3 11.0294 3 16H21C21 11.0294 16.9706 7 12 7ZM12 7V4M15 16C15 17.6569 13.6569 19 12 19C10.3431 19 9 17.6569 9 16L15 16Z","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M13 4C13 3.44772 12.5523 3 12 3C11.4477 3 11 3.44772 11 4V6.04938C5.94668 6.5511 2 10.8147 2 16C2 16.5523 2.44772 17 3 17H8.12602C8.57006 18.7252 10.1362 20 12 20C13.8638 20 15.4299 18.7252 15.874 17H21C21.5523 17 22 16.5523 22 16C22 10.8147 18.0533 6.5511 13 6.04938V4ZM12 18C11.2597 18 10.6134 17.5978 10.2676 17L13.7324 17C13.3866 17.5978 12.7403 18 12 18Z","fill":"currentColor","fillRule":"evenodd","clipRule":"evenodd","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M12 7C7.02944 7 3 11.0294 3 16H21C21 11.0294 16.9706 7 12 7Z","fill":"currentColor","opacity":0.28,"key":"c0"}],
    ["path", {"d":"M12 7C7.02944 7 3 11.0294 3 16H21C21 11.0294 16.9706 7 12 7ZM12 7V4M15 16C15 17.6569 13.6569 19 12 19C10.3431 19 9 17.6569 9 16L15 16Z","stroke":"currentColor","key":"c1"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M15 16L9 16M3 16C3 11.0294 7.02944 7 12 7C16.9706 7 21 11.0294 21 16H3Z","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M13 4C13 3.44772 12.5522 3 12 3C11.4477 3 11 3.44772 11 4V6.04938C11.3289 6.01672 11.6625 6 12 6C12.3375 6 12.6711 6.01672 13 6.04938V4Z","fill":"currentColor","key":"d1"}],
    ["path", {"d":"M8.12598 17C8.57002 18.7252 10.1361 20 12 20C13.8638 20 15.4299 18.7252 15.8739 17H13.7324C13.3866 17.5978 12.7402 18 12 18C11.2597 18 10.6133 17.5978 10.2675 17L8.12598 17Z","fill":"currentColor","key":"d2"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M3 17H21C21.5523 17 22 16.5523 22 16C22 10.4772 17.5228 6 12 6C6.47715 6 2 10.4772 2 16C2 16.5523 2.44772 17 3 17Z","fill":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M13 4C13 3.44772 12.5522 3 12 3C11.4477 3 11 3.44772 11 4V6.04938C11.3289 6.01672 11.6625 6 12 6C12.3375 6 12.6711 6.01672 13 6.04938V4Z","fill":"currentColor","key":"d1"}],
    ["path", {"d":"M8.12598 17C8.57002 18.7252 10.1361 20 12 20C13.8638 20 15.4299 18.7252 15.8739 17H13.7324C13.3866 17.5978 12.7402 18 12 18C11.2597 18 10.6133 17.5978 10.2675 17L8.12598 17Z","fill":"currentColor","key":"d2"}],
  ],
};

export const CeilingLampOff = createPikaIcon("ceiling-lamp-off", ceilingLampOff);
export default CeilingLampOff;
