// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const cryptoCurrencyUsdt: IconVariants = {
  "Stroke": [
    ["path", {"d":"M5 5H12M12 5H19M12 5V11M12 14V19M12 14C16.9706 14 22 12.8807 22 11.5C22 10.1193 16.9706 9 12 9C7.02944 9 2 10.1193 2 11.5C2 12.8807 7.02944 14 12 14Z","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M5 5H12M12 5H19M12 5V11M12 14V19M12 14C16.9706 14 22 12.8807 22 11.5C22 10.1193 16.9706 9 12 9C7.02944 9 2 10.1193 2 11.5C2 12.8807 7.02944 14 12 14Z","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M5 5H12M12 5H19M12 5V11M12 14V19M12 14C16.9706 14 22 12.8807 22 11.5C22 10.1193 16.9706 9 12 9C7.02944 9 2 10.1193 2 11.5C2 12.8807 7.02944 14 12 14Z","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M22 11.5C22 12.8807 16.9706 14 12 14C7.02944 14 2 12.8807 2 11.5C2 10.1193 7.02944 9 12 9C16.9706 9 22 10.1193 22 11.5Z","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M5 4C4.44772 4 4 4.44772 4 5C4 5.55228 4.44772 6 5 6H11V11C11 11.5523 11.4477 12 12 12C12.5523 12 13 11.5523 13 11V6H19C19.5523 6 20 5.55228 20 5C20 4.44772 19.5523 4 19 4H5Z","fill":"currentColor","key":"d1"}],
    ["path", {"d":"M13 14.9856C12.6672 14.9951 12.3334 15 12.0002 15C11.6668 15 11.333 14.9951 11 14.9855V19C11 19.5523 11.4477 20 12 20C12.5523 20 13 19.5523 13 19V14.9856Z","fill":"currentColor","key":"d2"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M5 5H12M12 5H19M12 5V11M12 14V19M12 14C16.9706 14 22 12.8807 22 11.5C22 10.1193 16.9706 9 12 9C7.02944 9 2 10.1193 2 11.5C2 12.8807 7.02944 14 12 14Z","stroke":"currentColor","key":"s0"}],
  ],
};

export const CryptoCurrencyUsdt = createPikaIcon("crypto-currency-usdt", cryptoCurrencyUsdt);
export default CryptoCurrencyUsdt;
