// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const currencySignPound: IconVariants = {
  "Stroke": [
    ["path", {"d":"M16 20H6.24976C5.9866 20 5.90286 19.6207 6.13823 19.4948C7.5685 18.7301 8.51847 17.2045 8.51847 15.4754V12.8889M8.51847 12.8889V8C8.51847 5.72763 10.2909 4 12.3693 4C14.3276 4 16 5.62062 16 7.76471M8.51847 12.8889H6.02463M8.51847 12.8889H16","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M16 20H6.24976C5.9866 20 5.90286 19.6207 6.13823 19.4948C7.5685 18.7301 8.51847 17.2045 8.51847 15.4754V12.8889M8.51847 12.8889V8C8.51847 5.72763 10.2909 4 12.3693 4C14.3276 4 16 5.62062 16 7.76471M8.51847 12.8889H6.02463M8.51847 12.8889H16","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M16 20H6.24976C5.9866 20 5.90286 19.6207 6.13823 19.4948C7.5685 18.7301 8.51847 17.2045 8.51847 15.4754V12.8889M8.51847 12.8889V8C8.51847 5.72763 10.2909 4 12.3693 4C14.3276 4 16 5.62062 16 7.76471M8.51847 12.8889H6.02463M8.51847 12.8889H16","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M6.02441 12.8889H15.9998","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M16 20H6.24976C5.9866 20 5.90286 19.6207 6.13823 19.4948C7.5685 18.7301 8.51847 17.2045 8.51847 15.4754V8C8.51847 5.72763 10.2909 4 12.3693 4C14.3276 4 16 5.62062 16 7.76471","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M16 20H6.24976C5.9866 20 5.90286 19.6207 6.13823 19.4948C7.5685 18.7301 8.51847 17.2045 8.51847 15.4754V12.8889M8.51847 12.8889V8C8.51847 5.72763 10.2909 4 12.3693 4C14.3276 4 16 5.62062 16 7.76471M8.51847 12.8889H6.02463M8.51847 12.8889H16","stroke":"currentColor","key":"s0"}],
  ],
};

export const CurrencySignPound = createPikaIcon("currency-sign-pound", currencySignPound);
export default CurrencySignPound;
