// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const currencySignYuan: IconVariants = {
  "Stroke": [
    ["path", {"d":"M5 3L12 11.1M12 11.1L19 3M12 11.1V12M12 12V16M12 12H6M12 12H18M12 16V21M12 16H6M12 16H18","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M5 3L12 11.1M12 11.1L19 3M12 11.1V12M12 12V16M12 12H6M12 12H18M12 16V21M12 16H6M12 16H18","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M5 3L12 11.1M12 11.1L19 3M12 11.1V12M12 12V16M12 12H6M12 12H18M12 16V21M12 16H6M12 16H18","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M6 12H18M6 16H18","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M5 3L12 11.1M12 11.1L19 3M12 11.1V21","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M5 3L12 11.1M12 11.1L19 3M12 11.1V12M12 12V16M12 12H6M12 12H18M12 16V21M12 16H6M12 16H18","stroke":"currentColor","key":"s0"}],
  ],
};

export const CurrencySignYuan = createPikaIcon("currency-sign-yuan", currencySignYuan);
export default CurrencySignYuan;
