// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const currencySignFranc: IconVariants = {
  "Stroke": [
    ["path", {"d":"M16.5 4H10.8571C10.0592 4 9.66019 4 9.33944 4.11223C8.76495 4.31326 8.31326 4.76495 8.11223 5.33944C8 5.66019 8 6.05917 8 6.85714V12M15.5 12H8M8 12H5M8 12V16M5 16H8M8 16H12M8 16V21","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M16.5 4H10.8571C10.0592 4 9.66019 4 9.33944 4.11223C8.76495 4.31326 8.31326 4.76495 8.11223 5.33944C8 5.66019 8 6.05917 8 6.85714V12M15.5 12H8M8 12H5M8 12V16M5 16H8M8 16H12M8 16V21","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M16.5 4H10.8571C10.0592 4 9.66019 4 9.33944 4.11223C8.76495 4.31326 8.31326 4.76495 8.11223 5.33944C8 5.66019 8 6.05917 8 6.85714V12M15.5 12H8M8 12H5M8 12V16M5 16H8M8 16H12M8 16V21","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M15.5 12H5M5 16H12","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M16.5 4H10.8571C10.0592 4 9.66019 4 9.33944 4.11223C8.76495 4.31326 8.31326 4.76495 8.11223 5.33944C8 5.66019 8 6.05917 8 6.85714V21","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M16.5 4H10.8571C10.0592 4 9.66019 4 9.33944 4.11223C8.76495 4.31326 8.31326 4.76495 8.11223 5.33944C8 5.66019 8 6.05917 8 6.85714V12M15.5 12H8M8 12H5M8 12V16M5 16H8M8 16H12M8 16V21","stroke":"currentColor","key":"s0"}],
  ],
};

export const CurrencySignFranc = createPikaIcon("currency-sign-franc", currencySignFranc);
export default CurrencySignFranc;
