// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const currencySignRuble: IconVariants = {
  "Stroke": [
    ["path", {"d":"M8 12H14C16.2091 12 18 10.2091 18 8C18 5.79086 16.2091 4 14 4H10.8571C10.0592 4 9.66019 4 9.33944 4.11223C8.76495 4.31326 8.31326 4.76495 8.11223 5.33944C8 5.66019 8 6.05917 8 6.85714V12ZM8 12L5 12M8 12V16M8 21V16M5 16H8M15 16H8","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M8 12H14C16.2091 12 18 10.2091 18 8C18 5.79086 16.2091 4 14 4H10.8571C10.0592 4 9.66019 4 9.33944 4.11223C8.76495 4.31326 8.31326 4.76495 8.11223 5.33944C8 5.66019 8 6.05917 8 6.85714V12ZM8 12L5 12M8 12V16M8 21V16M5 16H8M15 16H8","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M8 12H14C16.2091 12 18 10.2091 18 8C18 5.79086 16.2091 4 14 4H10.8571C10.0592 4 9.66019 4 9.33944 4.11223C8.76495 4.31326 8.31326 4.76495 8.11223 5.33944C8 5.66019 8 6.05917 8 6.85714V12ZM8 12L5 12M8 12V16M8 21V16M5 16H8M15 16H8","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M5 16H15","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M8 12H14C16.2091 12 18 10.2091 18 8C18 5.79086 16.2091 4 14 4H10.8571C10.0592 4 9.66019 4 9.33944 4.11223C8.76495 4.31326 8.31326 4.76495 8.11223 5.33944C8 5.66019 8 6.05917 8 6.85714V12ZM8 12L5 12M8 12V21","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M8 12H14C16.2091 12 18 10.2091 18 8C18 5.79086 16.2091 4 14 4H10.8571C10.0592 4 9.66019 4 9.33944 4.11223C8.76495 4.31326 8.31326 4.76495 8.11223 5.33944C8 5.66019 8 6.05917 8 6.85714V12ZM8 12L5 12M8 12V16M8 21V16M5 16H8M15 16H8","stroke":"currentColor","key":"s0"}],
  ],
};

export const CurrencySignRuble = createPikaIcon("currency-sign-ruble", currencySignRuble);
export default CurrencySignRuble;
