// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const equalsCancel: IconVariants = {
  "Stroke": [
    ["path", {"d":"M9.66667 15L14.3333 9L19 3M14.3333 9H5M15 15L19 15M18.9805 9H19M5 21L9.66667 15M9.66667 15H5","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M9.66667 15L14.3333 9L19 3M14.3333 9H5M15 15L19 15M18.9805 9H19M5 21L9.66667 15M9.66667 15H5","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M9.66667 15L14.3333 9L19 3M14.3333 9H5M15 15L19 15M18.9805 9H19M5 21L9.66667 15M9.66667 15H5","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M5 9H14.3333M15 15L19 15M18.9805 9H19M5 15H9.66667","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M5 21L19 3","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M9.66667 15L14.3333 9L19 3M14.3333 9H5M15 15L19 15M18.9805 9H19M5 21L9.66667 15M9.66667 15H5","stroke":"currentColor","key":"s0"}],
  ],
};

export const EqualsCancel = createPikaIcon("equals-cancel", equalsCancel);
export default EqualsCancel;
