// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const exclamationMark: IconVariants = {
  "Stroke": [
    ["path", {"d":"M12 5V14M12 19V19.01","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M12 5V14M12 19V19.01","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M12 5V14M12 19V19.01","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M12 5V14","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M12 19V19.01","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M12 5V14M12 19V19.01","stroke":"currentColor","key":"s0"}],
  ],
};

export const ExclamationMark = createPikaIcon("exclamation-mark", exclamationMark);
export default ExclamationMark;
