// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const filterHorizontal: IconVariants = {
  "Stroke": [
    ["path", {"d":"M3 7H10M10 7C10 8.65685 11.3431 10 13 10H14C15.6569 10 17 8.65685 17 7C17 5.34315 15.6569 4 14 4H13C11.3431 4 10 5.34315 10 7ZM16 17H21M20 7H21M3 17H6M6 17C6 18.6569 7.34315 20 9 20H10C11.6569 20 13 18.6569 13 17C13 15.3431 11.6569 14 10 14H9C7.34315 14 6 15.3431 6 17Z","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M13 3C11.1362 3 9.57006 4.27477 9.12602 6H3C2.44772 6 2 6.44772 2 7C2 7.55228 2.44772 8 3 8H9.12602C9.57006 9.72523 11.1362 11 13 11H14C16.2091 11 18 9.20914 18 7C18 4.79086 16.2091 3 14 3H13Z","fill":"currentColor","key":"s0"}],
    ["path", {"d":"M20 6C19.4477 6 19 6.44772 19 7C19 7.55228 19.4477 8 20 8H21C21.5523 8 22 7.55228 22 7C22 6.44772 21.5523 6 21 6H20Z","fill":"currentColor","key":"s1"}],
    ["path", {"d":"M9 13C7.13616 13 5.57006 14.2748 5.12602 16H3C2.44772 16 2 16.4477 2 17C2 17.5523 2.44772 18 3 18H5.12602C5.57006 19.7252 7.13616 21 9 21H10C12.2091 21 14 19.2091 14 17C14 14.7909 12.2091 13 10 13H9Z","fill":"currentColor","key":"s2"}],
    ["path", {"d":"M16 16C15.4477 16 15 16.4477 15 17C15 17.5523 15.4477 18 16 18H21C21.5523 18 22 17.5523 22 17C22 16.4477 21.5523 16 21 16H16Z","fill":"currentColor","key":"s3"}],
  ],
  "Contrast": [
    ["path", {"d":"M10 7C10 5.34315 11.3431 4 13 4H14C15.6569 4 17 5.34315 17 7C17 8.65685 15.6569 10 14 10H13C11.3431 10 10 8.65685 10 7Z","fill":"currentColor","opacity":0.28,"key":"c0"}],
    ["path", {"d":"M6 17C6 15.3431 7.34315 14 9 14H10C11.6569 14 13 15.3431 13 17C13 18.6569 11.6569 20 10 20H9C7.34315 20 6 18.6569 6 17Z","fill":"currentColor","opacity":0.28,"key":"c1"}],
    ["path", {"d":"M3 7H10M10 7C10 8.65685 11.3431 10 13 10H14C15.6569 10 17 8.65685 17 7C17 5.34315 15.6569 4 14 4H13C11.3431 4 10 5.34315 10 7ZM16 17H21M20 7H21M3 17H6M6 17C6 18.6569 7.34315 20 9 20H10C11.6569 20 13 18.6569 13 17C13 15.3431 11.6569 14 10 14H9C7.34315 14 6 15.3431 6 17Z","stroke":"currentColor","key":"c2"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M3 7H10M16 17H21M20 7H21M3 17H6","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M10 7C10 5.34315 11.3431 4 13 4H14C15.6569 4 17 5.34315 17 7C17 8.65685 15.6569 10 14 10H13C11.3431 10 10 8.65685 10 7Z","stroke":"currentColor","key":"d1"}],
    ["path", {"d":"M6 17C6 15.3431 7.34315 14 9 14H10C11.6569 14 13 15.3431 13 17C13 18.6569 11.6569 20 10 20H9C7.34315 20 6 18.6569 6 17Z","stroke":"currentColor","key":"d2"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M3 7H10M16 17H21M20 7H21M3 17H6","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M13 3C10.7909 3 9 4.79086 9 7C9 9.20914 10.7909 11 13 11H14C16.2091 11 18 9.20914 18 7C18 4.79086 16.2091 3 14 3H13Z","fill":"currentColor","key":"d1"}],
    ["path", {"d":"M9 13C6.79086 13 5 14.7909 5 17C5 19.2091 6.79086 21 9 21H10C12.2091 21 14 19.2091 14 17C14 14.7909 12.2091 13 10 13H9Z","fill":"currentColor","key":"d2"}],
  ],
};

export const FilterHorizontal = createPikaIcon("filter-horizontal", filterHorizontal);
export default FilterHorizontal;
