// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const frame: IconVariants = {
  "Stroke": [
    ["path", {"d":"M7 3V7M7 7V17M7 7L17 7M7 7L3 7M7 17V21M7 17L17 17M7 17H3M21 7L17 7M17 7V3M17 7V17M17 17V21M17 17H21","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M7 3V7M7 7V17M7 7L17 7M7 7L3 7M7 17V21M7 17L17 17M7 17H3M21 7L17 7M17 7V3M17 7V17M17 17V21M17 17H21","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M7 3V7M7 7V17M7 7L17 7M7 7L3 7M7 17V21M7 17L17 17M7 17H3M21 7L17 7M17 7V3M17 7V17M17 17V21M17 17H21","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M21 17H17V21M17 3V7H21M3 7L7 7V3M7 21V17H3","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M17 17V7H7V17L17 17Z","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M7 3V7M7 7V17M7 7L17 7M7 7L3 7M7 17V21M7 17L17 17M7 17H3M21 7L17 7M17 7V3M17 7V17M17 17V21M17 17H21","stroke":"currentColor","key":"s0"}],
  ],
};

export const Frame = createPikaIcon("frame", frame);
export default Frame;
