// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const gitCommit: IconVariants = {
  "Stroke": [
    ["path", {"d":"M15 12C15 13.6569 13.6569 15 12 15C10.3431 15 9 13.6569 9 12M15 12C15 10.3431 13.6569 9 12 9C10.3431 9 9 10.3431 9 12M15 12H21M9 12H3","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M12 8C10.1362 8 8.57006 9.27477 8.12602 11H3C2.44772 11 2 11.4477 2 12C2 12.5523 2.44772 13 3 13H8.12602C8.57006 14.7252 10.1362 16 12 16C13.8638 16 15.4299 14.7252 15.874 13H21C21.5523 13 22 12.5523 22 12C22 11.4477 21.5523 11 21 11H15.874C15.4299 9.27477 13.8638 8 12 8Z","fill":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M15 12C15 13.6569 13.6569 15 12 15C10.3431 15 9 13.6569 9 12C9 10.3431 10.3431 9 12 9C13.6569 9 15 10.3431 15 12Z","fill":"currentColor","opacity":0.28,"key":"c0"}],
    ["path", {"d":"M15 12C15 13.6569 13.6569 15 12 15C10.3431 15 9 13.6569 9 12M15 12C15 10.3431 13.6569 9 12 9C10.3431 9 9 10.3431 9 12M15 12H21M9 12H3","stroke":"currentColor","key":"c1"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M3 12H9M15 12H21","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M15 12C15 13.6569 13.6569 15 12 15C10.3431 15 9 13.6569 9 12C9 10.3431 10.3431 9 12 9C13.6569 9 15 10.3431 15 12Z","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M3 12H9M15 12H21","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M12 8C9.79086 8 8 9.79086 8 12C8 14.2091 9.79086 16 12 16C14.2091 16 16 14.2091 16 12C16 9.79086 14.2091 8 12 8Z","fill":"currentColor","key":"d1"}],
  ],
};

export const GitCommit = createPikaIcon("git-commit", gitCommit);
export default GitCommit;
