// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const graphChartMaximum: IconVariants = {
  "Stroke": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3M8 5H8.01M11 5H11.01M17 5H17.01M20 5H20.01M13.99 5H14M7 17C7.82746 11.8168 10.6479 8 14 8C17.3521 8 20.1725 11.8168 21 17","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3M8 5H8.01M11 5H11.01M17 5H17.01M20 5H20.01M13.99 5H14M7 17C7.82746 11.8168 10.6479 8 14 8C17.3521 8 20.1725 11.8168 21 17","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3M8 5H8.01M11 5H11.01M17 5H17.01M20 5H20.01M13.99 5H14M7 17C7.82746 11.8168 10.6479 8 14 8C17.3521 8 20.1725 11.8168 21 17","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M7 17C7.82746 11.8168 10.6479 8 14 8C17.3521 8 20.1725 11.8168 21 17M8 5H8.01M11 5H11.01M17 5H17.01M20 5H20.01M13.99 5H14","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3M8 5H8.01M11 5H11.01M17 5H17.01M20 5H20.01M13.99 5H14M7 17C7.82746 11.8168 10.6479 8 14 8C17.3521 8 20.1725 11.8168 21 17","stroke":"currentColor","key":"s0"}],
  ],
};

export const GraphChartMaximum = createPikaIcon("graph-chart-maximum", graphChartMaximum);
export default GraphChartMaximum;
