// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const graphChartMinimum: IconVariants = {
  "Stroke": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3M8 17H8.01M11 17H11.01M17 17H17.01M20 17H20.01M13.99 17H14M7 5C7.82746 10.1832 10.6479 14 14 14C17.3521 14 20.1725 10.1832 21 5","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3M8 17H8.01M11 17H11.01M17 17H17.01M20 17H20.01M13.99 17H14M7 5C7.82746 10.1832 10.6479 14 14 14C17.3521 14 20.1725 10.1832 21 5","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3M8 17H8.01M11 17H11.01M17 17H17.01M20 17H20.01M13.99 17H14M7 5C7.82746 10.1832 10.6479 14 14 14C17.3521 14 20.1725 10.1832 21 5","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M8 17H8.01M11 17H11.01M17 17H17.01M20 17H20.01M13.99 17H14M7 5C7.82746 10.1832 10.6479 14 14 14C17.3521 14 20.1725 10.1832 21 5","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3M8 17H8.01M11 17H11.01M17 17H17.01M20 17H20.01M13.99 17H14M7 5C7.82746 10.1832 10.6479 14 14 14C17.3521 14 20.1725 10.1832 21 5","stroke":"currentColor","key":"s0"}],
  ],
};

export const GraphChartMinimum = createPikaIcon("graph-chart-minimum", graphChartMinimum);
export default GraphChartMinimum;
