// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const graphTrendLine: IconVariants = {
  "Stroke": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3M7 14L7.61026 12.1692C8.35529 9.93413 11.5295 9.97104 12.2224 12.2228C12.8649 14.311 15.7261 14.5478 16.7032 12.5937L19 8","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3M7 14L7.61026 12.1692C8.35529 9.93413 11.5295 9.97104 12.2224 12.2228C12.8649 14.311 15.7261 14.5478 16.7032 12.5937L19 8","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3M7 14L7.61026 12.1692C8.35529 9.93413 11.5295 9.97104 12.2224 12.2228C12.8649 14.311 15.7261 14.5478 16.7032 12.5937L19 8","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M7 14L7.61026 12.1692C8.35529 9.93413 11.5295 9.97104 12.2224 12.2228C12.8649 14.311 15.7261 14.5478 16.7032 12.5937L19 8","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M21 21H7C4.79086 21 3 19.2091 3 17V3M7 14L7.61026 12.1692C8.35529 9.93413 11.5295 9.97104 12.2224 12.2228C12.8649 14.311 15.7261 14.5478 16.7032 12.5937L19 8","stroke":"currentColor","key":"s0"}],
  ],
};

export const GraphTrendLine = createPikaIcon("graph-trend-line", graphTrendLine);
export default GraphTrendLine;
