// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const heading: IconVariants = {
  "Stroke": [
    ["path", {"d":"M6 20V12M6 4V12M18 20V12M18 4V12M18 12H6","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M6 20V12M6 4V12M18 20V12M18 4V12M18 12H6","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M6 20V12M6 4V12M18 20V12M18 4V12M18 12H6","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M6 12H18","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M6 20V4M18 20V4","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M6 20V12M6 4V12M18 20V12M18 4V12M18 12H6","stroke":"currentColor","key":"s0"}],
  ],
};

export const Heading = createPikaIcon("heading", heading);
export default Heading;
