// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const headingH4: IconVariants = {
  "Stroke": [
    ["path", {"d":"M4 12H12M4 18V6M12 18V6M17 10L16.2392 13.8039C16.1155 14.4227 16.5888 15 17.2198 15H21M21 15V12M21 15V18","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M4 12H12M4 18V6M12 18V6M17 10L16.2392 13.8039C16.1155 14.4227 16.5888 15 17.2198 15H21M21 15V12M21 15V18","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M4 12H12M4 18V6M12 18V6M17 10L16.2392 13.8039C16.1155 14.4227 16.5888 15 17.2198 15H21M21 15V12M21 15V18","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M4 12H12M4 18V6M12 18V6","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M17.0003 10L16.2395 13.8039C16.1157 14.4227 16.589 15 17.2201 15H21.0003M21.0003 15V12M21.0003 15V18","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M4 12H12M4 18V6M12 18V6M17 10L16.2392 13.8039C16.1155 14.4227 16.5888 15 17.2198 15H21M21 15V12M21 15V18","stroke":"currentColor","key":"s0"}],
  ],
};

export const HeadingH4 = createPikaIcon("heading-h4", headingH4);
export default HeadingH4;
