// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const italic: IconVariants = {
  "Stroke": [
    ["path", {"d":"M13.5 5L10.5 19M13.5 5H17M13.5 5H10M10.5 19H14M10.5 19H7","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M13.5 5L10.5 19M13.5 5H17M13.5 5H10M10.5 19H14M10.5 19H7","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M13.5 5L10.5 19M13.5 5H17M13.5 5H10M10.5 19H14M10.5 19H7","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M13.5 5L10.5 19","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M14 19H7M17 5H10","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M13.5 5L10.5 19M13.5 5H17M13.5 5H10M10.5 19H14M10.5 19H7","stroke":"currentColor","key":"s0"}],
  ],
};

export const Italic = createPikaIcon("italic", italic);
export default Italic;
