// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const keyLeft: IconVariants = {
  "Stroke": [
    ["path", {"d":"M14 12C14 14.2091 15.7909 16 18 16C20.2091 16 22 14.2091 22 12C22 9.79086 20.2091 8 18 8C15.7909 8 14 9.79086 14 12ZM14 12H2V15M6 12V14","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M18 7C15.581 7 13.5633 8.71776 13.1 11H2C1.44772 11 1 11.4477 1 12V15C1 15.5523 1.44772 16 2 16C2.55228 16 3 15.5523 3 15V13H5V14C5 14.5523 5.44772 15 6 15C6.55228 15 7 14.5523 7 14V13H13.1C13.5633 15.2822 15.581 17 18 17C20.7614 17 23 14.7614 23 12C23 9.23858 20.7614 7 18 7Z","fill":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M22 12C22 14.2091 20.2091 16 18 16C15.7909 16 14 14.2091 14 12C14 9.79086 15.7909 8 18 8C20.2091 8 22 9.79086 22 12Z","fill":"currentColor","opacity":0.28,"key":"c0"}],
    ["path", {"d":"M14 12C14 14.2091 15.7909 16 18 16C20.2091 16 22 14.2091 22 12C22 9.79086 20.2091 8 18 8C15.7909 8 14 9.79086 14 12ZM14 12H2V15M6 12V14","stroke":"currentColor","key":"c1"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M6 12H2V15M6 12H14M6 12V14","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M22 12C22 14.2091 20.2091 16 18 16C15.7909 16 14 14.2091 14 12C14 9.79086 15.7909 8 18 8C20.2091 8 22 9.79086 22 12Z","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M6 12H2V15M6 12H14M6 12V14","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M18 7C15.2386 7 13 9.23858 13 12C13 14.7614 15.2386 17 18 17C20.7614 17 23 14.7614 23 12C23 9.23858 20.7614 7 18 7Z","fill":"currentColor","key":"d1"}],
  ],
};

export const KeyLeft = createPikaIcon("key-left", keyLeft);
export default KeyLeft;
