// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const linkHorizontalBroken: IconVariants = {
  "Stroke": [
    ["path", {"d":"M10.1213 4.12132L8 2M14.1213 4.12132L16.2426 2M10.1213 20L8 22.1213M14.1213 20L16.2426 22.1213M8 7H7C4.23858 7 2 9.23858 2 12C2 14.7614 4.23858 17 7 17H8M15 7H16C18.7614 7 21 9.23858 21 12C21 14.7614 18.7614 17 16 17H15","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M10.1213 4.12132L8 2M14.1213 4.12132L16.2426 2M10.1213 20L8 22.1213M14.1213 20L16.2426 22.1213M8 7H7C4.23858 7 2 9.23858 2 12C2 14.7614 4.23858 17 7 17H8M15 7H16C18.7614 7 21 9.23858 21 12C21 14.7614 18.7614 17 16 17H15","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M10.1213 4.12132L8 2M14.1213 4.12132L16.2426 2M10.1213 20L8 22.1213M14.1213 20L16.2426 22.1213M8 7H7C4.23858 7 2 9.23858 2 12C2 14.7614 4.23858 17 7 17H8M15 7H16C18.7614 7 21 9.23858 21 12C21 14.7614 18.7614 17 16 17H15","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M8 7H7C4.23858 7 2 9.23858 2 12C2 14.7614 4.23858 17 7 17H8M15 7H16C18.7614 7 21 9.23858 21 12C21 14.7614 18.7614 17 16 17H15","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M10.1213 4.12132L8 2M14.1213 4.12132L16.2426 2M10.1213 20L8 22.1213M14.1213 20L16.2426 22.1213","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M10.1213 4.12132L8 2M14.1213 4.12132L16.2426 2M10.1213 20L8 22.1213M14.1213 20L16.2426 22.1213M8 7H7C4.23858 7 2 9.23858 2 12C2 14.7614 4.23858 17 7 17H8M15 7H16C18.7614 7 21 9.23858 21 12C21 14.7614 18.7614 17 16 17H15","stroke":"currentColor","key":"s0"}],
  ],
};

export const LinkHorizontalBroken = createPikaIcon("link-horizontal-broken", linkHorizontalBroken);
export default LinkHorizontalBroken;
