// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const listCheck: IconVariants = {
  "Stroke": [
    ["path", {"d":"M4 12H10M4 18H10M4 6H20M13.5 14.9783L15.8412 17.317C16.9672 15.3481 18.5256 13.6604 20.3987 12.3813","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M4 12H10M4 18H10M4 6H20M13.5 14.9783L15.8412 17.317C16.9672 15.3481 18.5256 13.6604 20.3987 12.3813","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M4 12H10M4 18H10M4 6H20M13.5 14.9783L15.8412 17.317C16.9672 15.3481 18.5256 13.6604 20.3987 12.3813","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M4 12H10M4 18H10M4 6H20","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M13.5 14.9778L15.8412 17.3165C16.9672 15.3476 18.5256 13.6599 20.3987 12.3809","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M4 12H10M4 18H10M4 6H20M13.5 14.9783L15.8412 17.317C16.9672 15.3481 18.5256 13.6604 20.3987 12.3813","stroke":"currentColor","key":"s0"}],
  ],
};

export const ListCheck = createPikaIcon("list-check", listCheck);
export default ListCheck;
