// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const listShort: IconVariants = {
  "Stroke": [
    ["path", {"d":"M4 9H20M4 14H12","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M4 9H20M4 14H12","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M4 9H20M4 14H12","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M4 9H20","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M4 14H12","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M4 9H20M4 14H12","stroke":"currentColor","key":"s0"}],
  ],
};

export const ListShort = createPikaIcon("list-short", listShort);
export default ListShort;
