// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const mapPin02: IconVariants = {
  "Stroke": [
    ["path", {"d":"M12 13C14.7614 13 17 10.7614 17 8C17 5.23858 14.7614 3 12 3C9.23858 3 7 5.23858 7 8C7 10.7614 9.23858 13 12 13ZM12 13V21","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M12 2C8.68629 2 6 4.68629 6 8C6 10.973 8.16229 13.441 11 13.917V21C11 21.5523 11.4477 22 12 22C12.5523 22 13 21.5523 13 21V13.917C15.8377 13.441 18 10.973 18 8C18 4.68629 15.3137 2 12 2Z","fill":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M17 8C17 10.7614 14.7614 13 12 13C9.23858 13 7 10.7614 7 8C7 5.23858 9.23858 3 12 3C14.7614 3 17 5.23858 17 8Z","fill":"currentColor","opacity":0.28,"key":"c0"}],
    ["path", {"d":"M12 13C14.7614 13 17 10.7614 17 8C17 5.23858 14.7614 3 12 3C9.23858 3 7 5.23858 7 8C7 10.7614 9.23858 13 12 13ZM12 13V21","stroke":"currentColor","key":"c1"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M12 21V13","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M17 8C17 10.7614 14.7614 13 12 13C9.23858 13 7 10.7614 7 8C7 5.23858 9.23858 3 12 3C14.7614 3 17 5.23858 17 8Z","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M12 21V13","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M12 2C8.68629 2 6 4.68629 6 8C6 11.3137 8.68629 14 12 14C15.3137 14 18 11.3137 18 8C18 4.68629 15.3137 2 12 2Z","fill":"currentColor","key":"d1"}],
  ],
};

export const MapPin02 = createPikaIcon("map-pin-02", mapPin02);
export default MapPin02;
