// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const martiniGlass: IconVariants = {
  "Stroke": [
    ["path", {"d":"M12 13V21M12 13L6 7M12 13L18 7M12 21H17.5M12 21H7M6 7L3 4H21L18 7M6 7C9.99308 7.33276 14.0069 7.33276 18 7","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M3.00003 3C2.59557 3 2.23093 3.24364 2.07615 3.61732C1.92137 3.99099 2.00692 4.42111 2.29292 4.70711L11 13.4142V20H7.00003C6.44774 20 6.00003 20.4477 6.00003 21C6.00003 21.5523 6.44774 22 7.00003 22H17.5C18.0523 22 18.5 21.5523 18.5 21C18.5 20.4477 18.0523 20 17.5 20H13V13.4142L21.7071 4.70711C21.9931 4.42111 22.0787 3.99099 21.9239 3.61732C21.7691 3.24364 21.4045 3 21 3H3.00003ZM17.553 6.03285C13.8566 6.32181 10.1434 6.32181 6.44709 6.03285L5.41424 5H18.5858L17.553 6.03285Z","fill":"currentColor","fillRule":"evenodd","clipRule":"evenodd","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M6 7L12 13L18 7C14.0069 7.33276 9.99308 7.33276 6 7Z","fill":"currentColor","opacity":0.28,"key":"c0"}],
    ["path", {"d":"M12 13V21M12 13L6 7M12 13L18 7M12 21H17.5M12 21H7M6 7L3 4H21L18 7M6 7C9.99308 7.33276 14.0069 7.33276 18 7","stroke":"currentColor","key":"c1"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M12 13V21M12 21H17.5M12 21H7","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M6 7L12 13L18 7M6 7L3 4H21L18 7M6 7C9.99308 7.33276 14.0069 7.33276 18 7","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M12 13V21M12 21H17.5M12 21H7","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M3.00003 3C2.59557 3 2.23093 3.24364 2.07615 3.61732C1.92137 3.99099 2.00692 4.42111 2.29292 4.70711L11.2929 13.7071C11.6834 14.0976 12.3166 14.0976 12.7071 13.7071L21.7071 4.70711C21.9931 4.42111 22.0787 3.99099 21.9239 3.61732C21.7691 3.24364 21.4045 3 21 3H3.00003ZM6.44709 6.03285L5.41424 5H18.5858L17.553 6.03285C13.8566 6.32181 10.1434 6.32181 6.44709 6.03285Z","fill":"currentColor","fillRule":"evenodd","clipRule":"evenodd","key":"d1"}],
  ],
};

export const MartiniGlass = createPikaIcon("martini-glass", martiniGlass);
export default MartiniGlass;
