// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const math: IconVariants = {
  "Stroke": [
    ["path", {"d":"M17 11V7M17 7V3M17 7L13 7M17 7H21M3 21L6 18M6 18L9 15M6 18L3 15M6 18L9 21M3 7H9M14 16H21M14 20H21","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M17 11V7M17 7V3M17 7L13 7M17 7H21M3 21L6 18M6 18L9 15M6 18L3 15M6 18L9 21M3 7H9M14 16H21M14 20H21","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M17 11V7M17 7V3M17 7L13 7M17 7H21M3 21L6 18M6 18L9 15M6 18L3 15M6 18L9 21M3 7H9M14 16H21M14 20H21","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M17 11V7M17 7V3M17 7L13 7M17 7H21M3 21L6 18M6 18L9 15M6 18L3 15M6 18L9 21","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M3 7H9M14 16H21M14 20H21","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M17 11V7M17 7V3M17 7L13 7M17 7H21M3 21L6 18M6 18L9 15M6 18L3 15M6 18L9 21M3 7H9M14 16H21M14 20H21","stroke":"currentColor","key":"s0"}],
  ],
};

export const Math = createPikaIcon("math", math);
export default Math;
