// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const micOn: IconVariants = {
  "Stroke": [
    ["path", {"d":"M12 20C7.58172 20 4 16.4183 4 12M12 20C16.4183 20 20 16.4183 20 12M12 20V22M12 16C9.79086 16 8 14.2091 8 12V7C8 4.79086 9.79086 3 12 3C14.2091 3 16 4.79086 16 7V12C16 14.2091 14.2091 16 12 16Z","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M12 2C9.23858 2 7 4.23858 7 7V12C7 14.7614 9.23858 17 12 17C14.7614 17 17 14.7614 17 12V7C17 4.23858 14.7614 2 12 2Z","fill":"currentColor","key":"s0"}],
    ["path", {"d":"M5 12C5 11.4477 4.55228 11 4 11C3.44772 11 3 11.4477 3 12C3 16.6326 6.50005 20.4476 11 20.9451V22C11 22.5523 11.4477 23 12 23C12.5523 23 13 22.5523 13 22V20.9451C17.5 20.4476 21 16.6326 21 12C21 11.4477 20.5523 11 20 11C19.4477 11 19 11.4477 19 12C19 15.866 15.866 19 12 19C8.13401 19 5 15.866 5 12Z","fill":"currentColor","key":"s1"}],
  ],
  "Contrast": [
    ["path", {"d":"M8 7C8 4.79086 9.79086 3 12 3C14.2091 3 16 4.79086 16 7V12C16 14.2091 14.2091 16 12 16C9.79086 16 8 14.2091 8 12V7Z","fill":"currentColor","opacity":0.28,"key":"c0"}],
    ["path", {"d":"M12 20C7.58172 20 4 16.4183 4 12M12 20C16.4183 20 20 16.4183 20 12M12 20V22M16 7V12C16 14.2091 14.2091 16 12 16C9.79086 16 8 14.2091 8 12V7C8 4.79086 9.79086 3 12 3C14.2091 3 16 4.79086 16 7Z","stroke":"currentColor","key":"c1"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M12 20C7.58172 20 4 16.4183 4 12M12 20C16.4183 20 20 16.4183 20 12M12 20V22","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M8 7C8 4.79086 9.79086 3 12 3C14.2091 3 16 4.79086 16 7V12C16 14.2091 14.2091 16 12 16C9.79086 16 8 14.2091 8 12V7Z","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M12 20C7.58172 20 4 16.4183 4 12M12 20C16.4183 20 20 16.4183 20 12M12 20V22","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M12 2C9.23858 2 7 4.23858 7 7V12C7 14.7614 9.23858 17 12 17C14.7614 17 17 14.7614 17 12V7C17 4.23858 14.7614 2 12 2Z","fill":"currentColor","key":"d1"}],
  ],
};

export const MicOn = createPikaIcon("mic-on", micOn);
export default MicOn;
