// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const multipleCrossCancelDefault: IconVariants = {
  "Stroke": [
    ["path", {"d":"M6 18L12 12M12 12L18 6M12 12L6 6M12 12L18 18","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M6 18L12 12M12 12L18 6M12 12L6 6M12 12L18 18","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M6 18L12 12M12 12L18 6M12 12L6 6M12 12L18 18","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M6 18L18 6","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M6 6L18 18","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M6 18L12 12M12 12L18 6M12 12L6 6M12 12L18 18","stroke":"currentColor","key":"s0"}],
  ],
};

export const MultipleCrossCancelDefault = createPikaIcon("multiple-cross-cancel-default", multipleCrossCancelDefault);
export default MultipleCrossCancelDefault;
