// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const pauseBig: IconVariants = {
  "Stroke": [
    ["path", {"d":"M9 6V18M15 6V18","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M9 6V18M15 6V18","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M9 6V18M15 6V18","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M15 6V18","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M9 6V18","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M9 6V18M15 6V18","stroke":"currentColor","key":"s0"}],
  ],
};

export const PauseBig = createPikaIcon("pause-big", pauseBig);
export default PauseBig;
