// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const priorityBlocker: IconVariants = {
  "Stroke": [
    ["path", {"d":"M8.5001 15.5001L15.5001 8.5001M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12ZM16.2071 9.20711C16.5976 8.81658 16.5976 8.18342 16.2071 7.79289C15.8166 7.40237 15.1834 7.40237 14.7929 7.79289L7.79289 14.7929C7.40237 15.1834 7.40237 15.8166 7.79289 16.2071C8.18342 16.5976 8.81658 16.5976 9.20711 16.2071L16.2071 9.20711Z","fill":"currentColor","fillRule":"evenodd","clipRule":"evenodd","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z","fill":"currentColor","opacity":0.28,"key":"c0"}],
    ["path", {"d":"M8.5001 15.5001L15.5001 8.5001M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z","stroke":"currentColor","key":"c1"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M8.5 15.5L15.5 8.5","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2Z","fill":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M8.5 15.5L15.5 8.5","stroke":"currentColor","key":"d1"}],
  ],
};

export const PriorityBlocker = createPikaIcon("priority-blocker", priorityBlocker);
export default PriorityBlocker;
