// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const queue: IconVariants = {
  "Stroke": [
    ["path", {"d":"M3 15H21M3 20H21M6 10H18C19.6569 10 21 8.65685 21 7C21 5.34315 19.6569 4 18 4H6C4.34315 4 3 5.34315 3 7C3 8.65685 4.34315 10 6 10Z","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M6 3C3.79086 3 2 4.79086 2 7C2 9.20914 3.79086 11 6 11H18C20.2091 11 22 9.20914 22 7C22 4.79086 20.2091 3 18 3H6Z","fill":"currentColor","key":"s0"}],
    ["path", {"d":"M3 14C2.44772 14 2 14.4477 2 15C2 15.5523 2.44772 16 3 16H21C21.5523 16 22 15.5523 22 15C22 14.4477 21.5523 14 21 14H3Z","fill":"currentColor","key":"s1"}],
    ["path", {"d":"M3 19C2.44772 19 2 19.4477 2 20C2 20.5523 2.44772 21 3 21H21C21.5523 21 22 20.5523 22 20C22 19.4477 21.5523 19 21 19H3Z","fill":"currentColor","key":"s2"}],
  ],
  "Contrast": [
    ["path", {"d":"M3 7C3 5.34315 4.34315 4 6 4H18C19.6569 4 21 5.34315 21 7C21 8.65685 19.6569 10 18 10H6C4.34315 10 3 8.65685 3 7Z","fill":"currentColor","opacity":0.28,"key":"c0"}],
    ["path", {"d":"M3 15H21M3 20H21M6 10H18C19.6569 10 21 8.65685 21 7C21 5.34315 19.6569 4 18 4H6C4.34315 4 3 5.34315 3 7C3 8.65685 4.34315 10 6 10Z","stroke":"currentColor","key":"c1"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M3 15H21M3 20H21","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M3 7C3 5.34315 4.34315 4 6 4H18C19.6569 4 21 5.34315 21 7C21 8.65685 19.6569 10 18 10H6C4.34315 10 3 8.65685 3 7Z","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M3 15H21M3 20H21","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M6 3C3.79086 3 2 4.79086 2 7C2 9.20914 3.79086 11 6 11H18C20.2091 11 22 9.20914 22 7C22 4.79086 20.2091 3 18 3H6Z","fill":"currentColor","key":"d1"}],
  ],
};

export const Queue = createPikaIcon("queue", queue);
export default Queue;
