// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const strikeThrough: IconVariants = {
  "Stroke": [
    ["path", {"d":"M3 12L12 12C14.2712 12 17 12.4351 17 15.8679C17 20.9381 8.33063 21.3742 7.14564 17M12 12L21 12M7 8.13207C7 3.06192 15.6694 2.62579 16.8544 7","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M3 12L12 12C14.2712 12 17 12.4351 17 15.8679C17 20.9381 8.33063 21.3742 7.14564 17M12 12L21 12M7 8.13207C7 3.06192 15.6694 2.62579 16.8544 7","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M3 12L12 12C14.2712 12 17 12.4351 17 15.8679C17 20.9381 8.33063 21.3742 7.14564 17M12 12L21 12M7 8.13207C7 3.06192 15.6694 2.62579 16.8544 7","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M12 12C14.2712 12 17 12.4351 17 15.8679C17 20.9381 8.33063 21.3742 7.14564 17M7 8.13207C7 3.06192 15.6694 2.62579 16.8544 7","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M21 12H3","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M3 12L12 12C14.2712 12 17 12.4351 17 15.8679C17 20.9381 8.33063 21.3742 7.14564 17M12 12L21 12M7 8.13207C7 3.06192 15.6694 2.62579 16.8544 7","stroke":"currentColor","key":"s0"}],
  ],
};

export const StrikeThrough = createPikaIcon("strike-through", strikeThrough);
export default StrikeThrough;
