// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const text: IconVariants = {
  "Stroke": [
    ["path", {"d":"M12 20V5M5 5H19","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M12 20V5M5 5H19","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M12 20V5M5 5H19","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M12 20V5","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M5 5H19","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M12 20V5M5 5H19","stroke":"currentColor","key":"s0"}],
  ],
};

export const Text = createPikaIcon("text", text);
export default Text;
