// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const threeDotsMenuHorizontal: IconVariants = {
  "Stroke": [
    ["path", {"d":"M6 12C6 12.5523 5.55228 13 5 13C4.44772 13 4 12.5523 4 12C4 11.4477 4.44772 11 5 11C5.55228 11 6 11.4477 6 12Z","stroke":"currentColor","key":"s0"}],
    ["path", {"d":"M13 12C13 12.5523 12.5523 13 12 13C11.4477 13 11 12.5523 11 12C11 11.4477 11.4477 11 12 11C12.5523 11 13 11.4477 13 12Z","stroke":"currentColor","key":"s1"}],
    ["path", {"d":"M20 12C20 12.5523 19.5523 13 19 13C18.4477 13 18 12.5523 18 12C18 11.4477 18.4477 11 19 11C19.5523 11 20 11.4477 20 12Z","stroke":"currentColor","key":"s2"}],
  ],
  "Solid": [
    ["path", {"d":"M6 12C6 12.5523 5.55228 13 5 13C4.44772 13 4 12.5523 4 12C4 11.4477 4.44772 11 5 11C5.55228 11 6 11.4477 6 12Z","stroke":"currentColor","key":"s0"}],
    ["path", {"d":"M13 12C13 12.5523 12.5523 13 12 13C11.4477 13 11 12.5523 11 12C11 11.4477 11.4477 11 12 11C12.5523 11 13 11.4477 13 12Z","stroke":"currentColor","key":"s1"}],
    ["path", {"d":"M20 12C20 12.5523 19.5523 13 19 13C18.4477 13 18 12.5523 18 12C18 11.4477 18.4477 11 19 11C19.5523 11 20 11.4477 20 12Z","stroke":"currentColor","key":"s2"}],
  ],
  "Contrast": [
    ["path", {"d":"M6 12C6 12.5523 5.55228 13 5 13C4.44772 13 4 12.5523 4 12C4 11.4477 4.44772 11 5 11C5.55228 11 6 11.4477 6 12Z","stroke":"currentColor","key":"s0"}],
    ["path", {"d":"M13 12C13 12.5523 12.5523 13 12 13C11.4477 13 11 12.5523 11 12C11 11.4477 11.4477 11 12 11C12.5523 11 13 11.4477 13 12Z","stroke":"currentColor","key":"s1"}],
    ["path", {"d":"M20 12C20 12.5523 19.5523 13 19 13C18.4477 13 18 12.5523 18 12C18 11.4477 18.4477 11 19 11C19.5523 11 20 11.4477 20 12Z","stroke":"currentColor","key":"s2"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M6 12C6 12.5523 5.55228 13 5 13C4.44772 13 4 12.5523 4 12C4 11.4477 4.44772 11 5 11C5.55228 11 6 11.4477 6 12Z","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M20 12C20 12.5523 19.5523 13 19 13C18.4477 13 18 12.5523 18 12C18 11.4477 18.4477 11 19 11C19.5523 11 20 11.4477 20 12Z","stroke":"currentColor","opacity":0.28,"key":"d1"}],
    ["path", {"d":"M13 12C13 12.5523 12.5523 13 12 13C11.4477 13 11 12.5523 11 12C11 11.4477 11.4477 11 12 11C12.5523 11 13 11.4477 13 12Z","stroke":"currentColor","key":"d2"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M6 12C6 12.5523 5.55228 13 5 13C4.44772 13 4 12.5523 4 12C4 11.4477 4.44772 11 5 11C5.55228 11 6 11.4477 6 12Z","stroke":"currentColor","key":"s0"}],
    ["path", {"d":"M13 12C13 12.5523 12.5523 13 12 13C11.4477 13 11 12.5523 11 12C11 11.4477 11.4477 11 12 11C12.5523 11 13 11.4477 13 12Z","stroke":"currentColor","key":"s1"}],
    ["path", {"d":"M20 12C20 12.5523 19.5523 13 19 13C18.4477 13 18 12.5523 18 12C18 11.4477 18.4477 11 19 11C19.5523 11 20 11.4477 20 12Z","stroke":"currentColor","key":"s2"}],
  ],
};

export const ThreeDotsMenuHorizontal = createPikaIcon("three-dots-menu-horizontal", threeDotsMenuHorizontal);
export default ThreeDotsMenuHorizontal;
