// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const walletconnect: IconVariants = {
  "Stroke": [
    ["path", {"d":"M5.76864 8.84607C7.28028 7.10266 9.51137 6 12 6C14.4886 6 16.7197 7.10266 18.2314 8.84607M2 12.111L7 17.736L12 12.111L17 17.736L22 12.111","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M5.76864 8.84607C7.28028 7.10266 9.51137 6 12 6C14.4886 6 16.7197 7.10266 18.2314 8.84607M2 12.111L7 17.736L12 12.111L17 17.736L22 12.111","stroke":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M5.76864 8.84607C7.28028 7.10266 9.51137 6 12 6C14.4886 6 16.7197 7.10266 18.2314 8.84607M2 12.111L7 17.736L12 12.111L17 17.736L22 12.111","stroke":"currentColor","key":"s0"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M5.76868 8.84607C7.28031 7.10266 9.51141 6 12 6C14.4887 6 16.7198 7.10266 18.2314 8.84607","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M2 12.1113L7 17.7363L12 12.1113L17 17.7363L22 12.1113","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M5.76864 8.84607C7.28028 7.10266 9.51137 6 12 6C14.4886 6 16.7197 7.10266 18.2314 8.84607M2 12.111L7 17.736L12 12.111L17 17.736L22 12.111","stroke":"currentColor","key":"s0"}],
  ],
};

export const Walletconnect = createPikaIcon("walletconnect", walletconnect);
export default Walletconnect;
