// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
import { createPikaIcon } from "../createPikaIcon.js";
import type { IconVariants } from "../types.js";

const wineGlassEmpty: IconVariants = {
  "Stroke": [
    ["path", {"d":"M12 13C15.6 13 18 10.264 18 6.88889C18 5.15448 17.5131 3.42007 16.6983 2H7.30171C6.48685 3.42007 6 5.15448 6 6.88889C6 10.264 8.4 13 12 13ZM12 13V22M16 22L8 22","stroke":"currentColor","key":"s0"}],
  ],
  "Solid": [
    ["path", {"d":"M7.30171 1C6.94349 1 6.61264 1.19161 6.43436 1.5023C5.53485 3.0699 5 4.97535 5 6.88889C5 10.4502 7.36105 13.4678 11 13.9368V21H8C7.44772 21 7 21.4477 7 22C7 22.5523 7.44772 23 8 23H11.9986L12 23H16C16.5523 23 17 22.5523 17 22C17 21.4477 16.5523 21 16 21H13V13.9368C16.639 13.4678 19 10.4502 19 6.88889C19 4.97535 18.4651 3.0699 17.5656 1.5023C17.3874 1.19161 17.0565 1 16.6983 1H7.30171Z","fill":"currentColor","key":"s0"}],
  ],
  "Contrast": [
    ["path", {"d":"M12 13C15.6 13 18 10.264 18 6.88889C18 5.15448 17.5131 3.42007 16.6983 2H7.30171C6.48685 3.42007 6 5.15448 6 6.88889C6 10.264 8.4 13 12 13Z","fill":"currentColor","opacity":0.28,"key":"c0"}],
    ["path", {"d":"M12 13C15.6 13 18 10.264 18 6.88889C18 5.15448 17.5131 3.42007 16.6983 2H7.30171C6.48685 3.42007 6 5.15448 6 6.88889C6 10.264 8.4 13 12 13ZM12 13V22M16 22L8 22","stroke":"currentColor","key":"c1"}],
  ],
  "Duo Stroke": [
    ["path", {"d":"M12 13V22M8 22L12 22H16","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M12 13C15.6 13 18 10.264 18 6.88889C18 5.15448 17.5131 3.42007 16.6983 2H7.30171C6.48685 3.42007 6 5.15448 6 6.88889C6 10.264 8.4 13 12 13Z","stroke":"currentColor","key":"d1"}],
  ],
  "Duo Solid": [
    ["path", {"d":"M12 13V22M8 22L12 22H16","stroke":"currentColor","opacity":0.28,"key":"d0"}],
    ["path", {"d":"M7.30171 1C6.94349 1 6.61264 1.19161 6.43436 1.5023C5.53485 3.0699 5 4.97535 5 6.88889C5 10.7667 7.79948 14 12 14C16.2005 14 19 10.7667 19 6.88889C19 4.97535 18.4651 3.0699 17.5656 1.5023C17.3874 1.19161 17.0565 1 16.6983 1H7.30171Z","fill":"currentColor","key":"d1"}],
  ],
};

export const WineGlassEmpty = createPikaIcon("wine-glass-empty", wineGlassEmpty);
export default WineGlassEmpty;
