// Generated by Zero Schema Generator

import {
  table,
  string,
  boolean,
  number,
  json,
  enumeration,
  relationships,
  createSchema,
  type Row,
} from '@rocicorp/zero';

// Define enums

// @ts-ignore TS1294
export enum TicketCategory {
  USER_ONBOARDING = 'USER_ONBOARDING',
  BUG_WORKFLOW = 'BUG_WORKFLOW',
  BUG_WORKFLOW_EVAL = 'BUG_WORKFLOW_EVAL',
  BUG_WORKFLOW_EVAL_INNER_STEPS = 'BUG_WORKFLOW_EVAL_INNER_STEPS',
  BUG_WORKFLOW_EVAL_INNER_STEPS_EXPERIMENTAL = 'BUG_WORKFLOW_EVAL_INNER_STEPS_EXPERIMENTAL',
  FEATURE_IMPLEMENTATION = 'FEATURE_IMPLEMENTATION',
  FEATURE_PLANNING = 'FEATURE_PLANNING',
  XYNE_SPACES_FEATURE_IMPLEMENTATION = 'XYNE_SPACES_FEATURE_IMPLEMENTATION',
  FIDO_SERVER_WORKFLOW = 'FIDO_SERVER_WORKFLOW',
  CONNECTOR_MIGRATION = 'CONNECTOR_MIGRATION',
  CODER_WORKFLOW = 'CODER_WORKFLOW',
  QUERY_WORKFLOW = 'QUERY_WORKFLOW',
  QUERY = 'QUERY',
  ISSUE = 'ISSUE',
  REQUIREMENT_NEW = 'REQUIREMENT_NEW',
  REQUIREMENT_ENHANCEMENT = 'REQUIREMENT_ENHANCEMENT',
  FULL_PG_INTEGRATION = 'FULL_PG_INTEGRATION',
  INVESTIGATION_WORKFLOW = 'INVESTIGATION_WORKFLOW',
  GENIUS_INVESTIGATION_WORKFLOW = 'GENIUS_INVESTIGATION_WORKFLOW',
  STAGE_APPROVAL_WORKFLOW = 'STAGE_APPROVAL_WORKFLOW',
}

// @ts-ignore TS1294
export enum TicketStatus {
  NEW = 'NEW',
  IN_PROGRESS = 'IN_PROGRESS',
  WAIT_FOR_APPROVAL = 'WAIT_FOR_APPROVAL',
  REJECTED = 'REJECTED',
  RESOLVED = 'RESOLVED',
}

// @ts-ignore TS1294
export enum TicketStatusV2 {
  TODO = 'TODO',
  STARTED = 'STARTED',
  PAUSED = 'PAUSED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
}

// @ts-ignore TS1294
export enum TicketPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

// @ts-ignore TS1294
export enum TicketReferenceRelation {
  LINKED = 'LINKED',
  DUPLICATE_CONFIRMED = 'DUPLICATE_CONFIRMED',
  DUPLICATE_POSSIBLE = 'DUPLICATE_POSSIBLE',
}

// @ts-ignore TS1294
export enum UserResponsibility {
  MANAGER = 'MANAGER',
  TEAM_LEAD = 'TEAM_LEAD',
  MEMBER = 'MEMBER',
  PR_REVIEWER = 'PR_REVIEWER',
  QA = 'QA',
}

// @ts-ignore TS1294
export enum EntityType {
  MERCHANT = 'MERCHANT',
  GATEWAY = 'GATEWAY',
}

// @ts-ignore TS1294
export enum AttachmentEntityType {
  TICKET = 'TICKET',
  CHAT = 'CHAT',
  CANVAS = 'CANVAS',
}

// @ts-ignore TS1294
export enum TicketEnvironment {
  DEVELOPMENT = 'DEVELOPMENT',
  STAGING = 'STAGING',
  PRODUCTION = 'PRODUCTION',
}

// @ts-ignore TS1294
export enum ReportedBy {
  MERCHANT = 'MERCHANT',
  INTERNAL = 'INTERNAL',
}

// @ts-ignore TS1294
export enum ChannelScopeType {
  DEFAULT = 'DEFAULT',
  DM = 'DM',
  TICKET = 'TICKET',
  DOCUMENT = 'DOCUMENT',
  GROUP_DM = 'GROUP_DM',
}

// @ts-ignore TS1294
export enum ChannelRole {
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
}

// @ts-ignore TS1294
export enum ChannelVisibility {
  PUBLIC = 'PUBLIC',
  PRIVATE = 'PRIVATE',
}

// @ts-ignore TS1294
export enum MessageType {
  USER = 'USER',
  BOT = 'BOT',
  SYSTEM = 'SYSTEM',
  FORWARDED = 'FORWARDED',
}

// @ts-ignore TS1294
export enum OrgRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
  VIEWER = 'VIEWER',
}

// @ts-ignore TS1294
export enum ActivityType {
  TITLE = 'TITLE',
  DESCRIPTION = 'DESCRIPTION',
  STATUS = 'STATUS',
  ASSIGNED_TO = 'ASSIGNED_TO',
  PRIORITY = 'PRIORITY',
  ETA = 'ETA',
  METADATA = 'METADATA',
  CLOSED_AT = 'CLOSED_AT',
  CLOSED_BY = 'CLOSED_BY',
  REFERENCE_TICKET = 'REFERENCE_TICKET',
  STAGE_NAME = 'STAGE_NAME',
  TAGS = 'TAGS',
  ENTITY = 'ENTITY',
  SUBTICKET_CREATED = 'SUBTICKET_CREATED',
  BOARD = 'BOARD',
  PR = 'PR',
  USER_GROUP_ID = 'USER_GROUP_ID',
  PR_REVIEWER = 'PR_REVIEWER',
  QA = 'QA',
  STAGE_CHANGE_REQUEST = 'STAGE_CHANGE_REQUEST',
  STAGE_CHANGE_APPROVED = 'STAGE_CHANGE_APPROVED',
  STAGE_CHANGE_REJECTED = 'STAGE_CHANGE_REJECTED',
}

// @ts-ignore TS1294
export enum ActivityClassification {
  ACTIONABLE = 'ACTIONABLE',
  FYI = 'FYI',
  SKIP = 'SKIP',
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  ERROR = 'ERROR',
}

// @ts-ignore TS1294
export enum ActivityClassificationJobType {
  SINGLE = 'SINGLE',
  SPECIAL_MENTION_AUDIENCE = 'SPECIAL_MENTION_AUDIENCE',
}

// @ts-ignore TS1294
export enum CallType {
  AUDIO = 'AUDIO',
  VIDEO = 'VIDEO',
  HEADLESS = 'HEADLESS'
}

// @ts-ignore TS1294
export enum CallStatus {
  SCHEDULED = 'SCHEDULED',
  ACTIVE = 'ACTIVE',
  IN_PROGRESS = 'IN_PROGRESS',
  ENDED = 'ENDED',
  CANCELLED = 'CANCELLED',
}

// @ts-ignore TS1294
export enum InvitationResponse {
  INVITED = 'INVITED',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
}

// @ts-ignore TS1294
export enum ConversationParticipation {
  AUTHOR = 'AUTHOR',
  MENTIONED = 'MENTIONED',
}

// @ts-ignore TS1294
export enum AuthProvider {
  GOOGLE = 'GOOGLE',
  API_KEY = 'API_KEY',
}

// @ts-ignore TS1294
export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

// @ts-ignore TS1294
export enum UserType {
  USER = 'USER',
  BOT = 'BOT',
}

// @ts-ignore TS1294
export enum UserPresenceStatus {
  ONLINE = 'ONLINE',
  AWAY = 'AWAY',
  OFFLINE = 'OFFLINE',
}

// @ts-ignore TS1294
export enum AccessType {
  ADMIN = 'ADMIN',
  READ = 'READ',
  WRITE = 'WRITE',
}

// @ts-ignore TS1294
export enum SessionStatus {
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  REVOKED = 'REVOKED',
}

// @ts-ignore TS1294
export enum ACLAuditEventType {
  RESOURCE_CREATED = 'RESOURCE_CREATED',
  RESOURCE_UPDATED = 'RESOURCE_UPDATED',
  RESOURCE_DELETED = 'RESOURCE_DELETED',
  PERMISSION_GRANTED = 'PERMISSION_GRANTED',
  PERMISSION_REVOKED = 'PERMISSION_REVOKED',
  PERMISSION_UPDATED = 'PERMISSION_UPDATED',
  USER_GROUP_CREATED = 'USER_GROUP_CREATED',
  USER_GROUP_UPDATED = 'USER_GROUP_UPDATED',
  USER_GROUP_DELETED = 'USER_GROUP_DELETED',
}

// @ts-ignore TS1294
export enum ACLAuditTargetType {
  RESOURCE = 'RESOURCE',
  RESOURCE_ACCESS = 'RESOURCE_ACCESS',
  USER_GROUP = 'USER_GROUP',
}

// @ts-ignore TS1294
export enum PRStatus {
  OPEN = 'OPEN',
  DECLINED = 'DECLINED',
  MERGED = 'MERGED',
}

// @ts-ignore TS1294
export enum PRStatusEvent {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  MERGED = 'MERGED',
  DECLINED = 'DECLINED',
}

// @ts-ignore TS1294
export enum MessageDirection {
  INCOMING = 'INCOMING',
  OUTGOING = 'OUTGOING',
}

// @ts-ignore TS1294
export enum NotificationType {
  TICKET_STATUS_CHANGE = "TICKET_STATUS_CHANGE",
  TICKET_ASSIGNMENT = "TICKET_ASSIGNMENT",
  TICKET_REASSIGNMENT = "TICKET_REASSIGNMENT",
  MENTION = "MENTION",
  DIRECT_MESSAGE = "DIRECT_MESSAGE",
  WORKFLOW_COMPLETION = "WORKFLOW_COMPLETION",
  WORKFLOW_FAILURE = "WORKFLOW_FAILURE",
  THREAD_REPLY = "THREAD_REPLY",
}

// @ts-ignore TS1294
export enum NotificationStatus {
  UNREAD = 'UNREAD',
  READ = 'READ',
  DISMISSED = 'DISMISSED',
}

// @ts-ignore TS1294
export enum NotificationDeliveryMethod {
  BROWSER = "BROWSER",
  EMAIL = "EMAIL",
  SLACK = "SLACK",
  MOBILE = "MOBILE",
}

// @ts-ignore TS1294
export enum CanvasVisibility {
  PUBLIC = 'PUBLIC',
  PRIVATE = 'PRIVATE',
}

// @ts-ignore TS1294
export enum CanvasRole {
  OWNER = 'OWNER',
  EDITOR = 'EDITOR',
  VIEWER = 'VIEWER',
}

// @ts-ignore TS1294
export enum DocType {
  Canvas = 'Canvas',
  Quarto = 'Quarto',
}

// @ts-ignore TS1294
export enum BookmarkEntityType {
  MESSAGE = 'MESSAGE',
  CONVERSATION = 'CONVERSATION',
  TICKET = 'TICKET',
  CANVAS = 'CANVAS',
}

// @ts-ignore TS1294
export enum EmailType {
  DEFAULT = 'DEFAULT',
  REPLY = 'REPLY',
  REPLY_ALL = 'REPLY_ALL',
}

// @ts-ignore TS1294
export enum ChannelType {
  DEFAULT = 'DEFAULT',
  EMAIL = 'EMAIL',
}

// @ts-ignore TS1294
export enum ExternalEntityType {
  MESSAGE = 'MESSAGE',
  EMAIL = 'EMAIL',
}

// @ts-ignore TS1294
export enum FormFieldType {
  STRING = 'STRING',
  NUMBER = 'NUMBER',
  BOOLEAN = 'BOOLEAN',
  DATE = 'DATE',
  SINGLE_SELECT = 'SINGLE_SELECT',
  MULTI_SELECT = 'MULTI_SELECT',
  USER = 'USER',
}

// @ts-ignore TS1294
export enum FormContextType {
  BOARD = 'BOARD',
  RELEASE_CHANGE = 'RELEASE_CHANGE',
  STAGE = 'STAGE',
}

// @ts-ignore TS1294
export enum BoardType {
  DEFAULT = 'DEFAULT',
  RELEASE = 'RELEASE',
  
}

// @ts-ignore TS1294
export enum FormEntityType {
  TICKET = 'TICKET',
  SUB_TICKET = 'SUB_TICKET',
  RELEASE_MIGRATION_FORM = "RELEASE_MIGRATION_FORM",
  RELEASE_ENV_FORM = "RELEASE_ENV_FORM",
}

// @ts-ignore TS1294
export enum LookupType {
  TICKET_TYPE = 'TICKET_TYPE',
}

// Release Management Enums

// @ts-ignore TS1294
export enum ApplicationReleaseTicketStatus {
  NOT_TESTED = 'NOT_TESTED',
  TESTING = 'TESTING',
  PASSED = 'PASSED',
  FAILED = 'FAILED',
  EXCLUDED = 'EXCLUDED',
}

// @ts-ignore TS1294
export enum EnvChangeType {
  ADDED = 'ADDED',
  MODIFIED = 'MODIFIED',
  REMOVED = 'REMOVED',
}

// @ts-ignore TS1294
export enum ReleaseEventType {
  RELEASE = 'RELEASE',
  TICKET = 'TICKET',
  SUBTICKET = 'SUBTICKET',
  TESTING = 'TESTING',
  SYSTEM = 'SYSTEM',
  CANVAS = 'CANVAS',
}

// @ts-ignore TS1294
export enum TicketStageRequestStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

// Define tables

export const agentTable = table('agents')
  .columns({
    id: string(),
    userDefinedId: string(),
    modelId: string(),
    systemPrompt: string(),
    description: string().optional(),
    name: string(),
    version: number(),
    updatedAt: number(),
    createdAt: number(),
    temp: number().optional(),
    scope: string(),
    scopeURI: string().optional(),
  })
  .primaryKey('id');

export const modelTable = table('models')
  .columns({
    id: string(),
    userDefinedId: string(),
    name: string(),
    provider: string(),
    credentials: string(),
    createdAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');

export const toolTable = table('tools')
  .columns({
    id: string(),
    name: string(),
    description: string().optional(),
    status: string(),
    createdAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');

export const agentToolsMappingTable = table('agent_tools_mappings')
  .columns({
    id: string(),
    agentId: string(),
    toolId: string(),
    specialDescription: string().optional(),
    status: string(),
    createdAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');

export const ticketTable = table('tickets')
  .columns({
    id: string(),
    title: string(),
    description: string(),
    status: enumeration<TicketStatus>(),  // Deprecated - use statusV2
    statusV2: enumeration<TicketStatusV2>(),
    createdBy: string(),
    updatedBy: string(),
    assignedTo: string().optional(),
    createdAt: number(),
    updatedAt: number(),
    merchantId: string().optional(),
    conversationId: string(),
    channelId: string(),
    eta: number().optional(),
    priority: enumeration<TicketPriority>(),
    metadata: json().optional(),
    closedAt: number().optional(),
    closedBy: string().optional(),
    xyneId: string(),
    projectId: string(),
    userGroupId: string(),
    boardId: string(),
    stageName: string(),
    ticketType: string().optional(),
  })
  .primaryKey('id');

export const subTicketTable = table('sub_tickets')
  .columns({
    id: string(),
    title: string(),
    description: string().optional(),
    mappedTicketId: string().optional(),
    createdBy: string(),
    updatedBy: string(),
    conversationId: string().optional(),
    createdAt: number(),
    updatedAt: number(),
    stageProgression: string().optional(),
    assignedTo: string().optional(),
  })
  .primaryKey('id');

export const ticketSubTicketMappingTable = table('ticket_sub_ticket_mappings')
  .columns({
    id: string(),
    ticketId: string(),
    subTicketId: string(),
  })
  .primaryKey('id');

export const ticketAssignmentTable = table('ticket_assignments')
  .columns({
    id: string(),
    ticketId: string(),
    userId: string(),
    userResponsibility: string(),
    createdAt: number(),
    createdBy: string(),
  })
  .primaryKey('id');

export const ticketActivityTable = table('ticket_activities')
  .columns({
    id: string(),
    ticketId: string(),
    updatedBy: string(),
    timestamp: number(),
    activityType: enumeration<ActivityType>(),
    value: json(),
  })
  .primaryKey('id');

export const ticketEntityMappingTable = table('ticket_entity_mappings')
  .columns({
    id: string(),
    ticketId: string(),
    entityType: enumeration<EntityType>(),
    entityName: string(),
  })
  .primaryKey('id');

export const ticketTagTable = table('ticket_tags')
  .columns({
    id: string(),
    name: string(),
    ticketId: string(),
  })
  .primaryKey('id');

export const ticketReferenceMappingTable = table('ticket_reference_mappings')
  .columns({
    id: string(),
    sourceTicketId: string(),
    targetTicketId: string(),
    relationType: enumeration<TicketReferenceRelation>(),
    createdBy: string(),
    createdAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');

export const projectTable = table('projects')
  .columns({
    id: string(),
    name: string(),
    description: string().optional(),
    createdBy: string(),
    updatedBy: string().optional(),
    createdAt: number(),
    updatedAt: number().optional(),
  })
  .primaryKey('id');

export const boardTable = table('boards')
  .columns({
    id: string(),
    name: string(),
    boardType: enumeration<BoardType>(),
    projectId: string(),
    createdBy: string(),
    updatedBy: string().optional(),
    metadata: json().optional(),
    createdAt: number(),
    updatedAt: number().optional(),
  })
  .primaryKey('id');

export const stageTable = table('stages')
  .columns({
    id: string(),
    name: string(),
    eta: number(),
    boardId: string(),
    sequenceNumber: number(),
    createdBy: string(),
    updatedBy: string().optional(),
    createdAt: number(),
    updatedAt: number().optional(),
    defaultTicketStatus: enumeration<TicketStatus>().optional(),  // Deprecated - use defaultTicketStatusV2
    defaultTicketStatusV2: enumeration<TicketStatusV2>(),
  })
  .primaryKey('id');

export const stagePRStatusMappingTable = table('stage_pr_status_mappings')
  .columns({
    id: string(),
    stageId: string(),
    prStatus: enumeration<PRStatusEvent>(),
    createdAt: number(),
  })
  .primaryKey('id');

export const userGroupMappingTable = table('user_group_mappings')
  .columns({
    id: string(),
    userId: string(),
    userGroupId: string(),
    responsibility: enumeration<UserResponsibility>(),
    createdAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');

export const userAssignmentStateTable = table('user_assignment_states')
  .columns({
    id: string(),
    userId: string(),
    userGroupId: string(),
    onCall: boolean(),
    isActiveForAssignment: boolean(),
    createdAt: number(),
    updatedAt: number(),
    createdBy: string(),
  })
  .primaryKey('id');

export const boardComplexityScoreTable = table('board_complexity_scores')
  .columns({
    id: string(),
    userGroupId: string(),
    boardId: string(),
    weight: number(),
    usePercentage: boolean(),
    createdAt: number(),
    updatedAt: number(),
    createdBy: string(),
  })
  .primaryKey('id');

export const userWorkloadMappingTable = table('user_workload_mappings')
  .columns({
    id: string(),
    userId: string(),
    userGroupId: string(),
    boardId: string(),
    activeTasks: number(),
    totalTasks: number(),
    createdAt: number(),
    updatedAt: number(),
    createdBy: string(),
  })
  .primaryKey('id');

export const userExpertiseMappingTable = table('user_expertise_mappings')
  .columns({
    id: string(),
    userId: string(),
    userGroupId: string(),
    boardId: string(),
    hasExpertise: boolean(),
    percentage: number(),
    maxTickets: number(),
    createdAt: number(),
    updatedAt: number(),
    createdBy: string(),
  })
  .primaryKey('id');

export const workflowTable = table('workflows')
  .columns({
    id: string(),
    ticketId: string(),
    context: string().optional(),
    status: string(),
    workflowName: string().optional(),
    metadata: string().optional(),
    configuration: string().optional(),
    workflowType: string().optional(),
    scheduledAt: number().optional(),
    createdAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');

export const workflowExecutionTable = table('workflow_executions')
  .columns({
    id: string(),
    workflowId: string(),
    workflowType: string().optional(),
    status: string(),
    parentWorkflowExecutionId: string().optional(),
    sourceStepsId: string().optional(),
    stepInputOverrideData: string().optional(),
    tag: string(),
    createdAt: number(),
    updatedAt: number(),
    ignoreDuration: number(),
  })
  .primaryKey('id');

export const userGroupTable = table('user_groups')
  .columns({
    id: string(),
    name: string(),
    alias: string().optional(),
    description: string().optional(),
    metadata: json().optional(),
    createdAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');

export const userTable = table('users')
  .columns({
    id: string(),
    name: string(),
    email: string(),
    picture: string().optional(),
    authProvider: enumeration<AuthProvider>(),
    providerUserId: string(),
    status: enumeration<UserStatus>(),
    userType: enumeration<UserType>(),
    metadata: json().optional(),
    createdAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');

export const userPresenceTable = table('user_presence')
  .columns({
    id: string(),
    userId: string(),
    status: enumeration<UserPresenceStatus>(),
    lastActiveAt: number(),
    lastSeenAt: number(),
    isManual: boolean(),
    deviceInfo: string().optional(),
    statusEmoji: string().optional(), // Current status emoji 
    statusContent: string().optional(), // Current status text
    statusExpiryAt: number().optional(), // Status expiry timestamp
    assignmentUnavailableUntil: number().optional(), // When user will be available for ticket assignment again
    createdAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');

export const userProfileTable = table('user_profiles')
  .columns({
    id: string(),
    userId: string(),
    dob: number().optional(), // Date of birth (optional) - stored as timestamp
    phoneNumber: string().optional(), // Phone number (optional)
    displayName: string().optional(), // Display name (optional)
    team: string().optional(), // Team name/identifier (optional)
    pronunciation: string().optional(), // Name pronunciation guide (optional)
    manager: string().optional(), // Manager userId (optional)
    role: string().optional(), // User role (optional)
    joinedOn: number().optional(), // Date when user joined (optional for backfill) - stored as timestamp
    createdAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');

export const resourceTable = table('resources')
  .columns({
    id: string(),
    name: string(),
    description: string().optional(),
    createdAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');

export const resourceAccessTable = table('resource_access')
  .columns({
    id: string(),
    groupId: string().optional(),
    userId: string().optional(),
    resourceId: string(),
    accessType: enumeration<AccessType>(),
    createdAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');

export const pullRequestsTable = table('pull_requests')
  .columns({
    id: string(),
    prId: number(),
    workflowExecutionId: string().optional(),
    repoName: string(),
    sourceBranchName: string(),
    destinationBranchName: string(),
    date: number(),
    numberOfComments: number(),
    repositoryUrl: string(),
    prUrl: string(),
    updatedAt: number(),
    status: enumeration<PRStatus>(),
  })
  .primaryKey('id');

export const organizationTable = table('organizations')
  .columns({
    orgId: string(),
    name: string(),
    description: string().optional(),
    createdBy: string(),
    createdAt: number(),
    updatedAt: number(),
    metadata: json().optional(),
  })
  .primaryKey('orgId');

export const orgMemberTable = table('org_members')
  .columns({
    memberId: string(),
    orgId: string(),
    userId: string(),
    role: enumeration<OrgRole>(),
    joinedAt: number(),
    invitedBy: string().optional(),
  })
  .primaryKey('memberId');

export const channelTable = table('channels')
  .columns({
    id: string(),
    name: string(),
    description: string().optional(),
    type: enumeration<ChannelType>(),
    scopeType: enumeration<ChannelScopeType>(),
    visibility: enumeration<ChannelVisibility>(),
    createdAt: number(),
    updatedAt: number(),
    lastActivityAt: number(),
    createdBy: string(),
    metadata: json().optional(),
    projectId: string(),
    participantCount: number(),
    isMigrated: boolean().optional(),
  })
  .primaryKey('id');

export const channelParticipantTable = table('channel_participants')
  .columns({
    id: string(),
    channelId: string(),
    userId: string(),
    joinedAt: number(),
    role: enumeration<ChannelRole>(),

    // These columns are deprecated please do not use them, use channelUserStatusTable instead
    lastViewedAt: number(),
    lastViewedConversationId: string().optional(),
    isStarred: boolean(),
    isClosed: boolean(),
  })
  .primaryKey('id');

export const channelUserStatusTable = table('channel_user_status')
  .columns({
    id: string(),
    channelId: string(),
    userId: string(),
    lastViewedAt: number(),
    lastViewedConversationId: string().optional(),
    isStarred: boolean(),
    isClosed: boolean(),
    unreadCount: number(),
    selectedBoardId: string().optional(),
  })
  .primaryKey('id');

export const conversationTable = table("conversations")
  .columns({
    conversationId: string(),
    channelId: string(),
    createdBy: string(),
    initialMessageId: string(),
    parentMessageId: string().optional(),
    lastActivityAt: number(),
    replyCount: number(),
    pinned: boolean(),
    ticketId: string().optional(),
    metadata: json().optional(),
    createdAt: number(),
  })
  .primaryKey("conversationId");

export const conversationParticipantTable = table('conversation_participants')
  .columns({
    id: string(),
    conversationId: string(),
    userId: string(),
    participationType: enumeration<ConversationParticipation>(),
    joinedAt: number(),
  })
  .primaryKey('id');

export const messageTable = table('messages')
  .columns({
    messageId: string(),
    conversationId: string(),
    childConversationId: string().optional(),
    senderId: string(),
    content: string(),
    msgType: enumeration<MessageType>(),
    hasAttachment: boolean(),
    edited: boolean(),
    isDeleted: boolean(),
    showInChannel: boolean(),
    visibleTo: string().optional(),
    createdAt: number(),
    metadata: json().optional(),
    isSent: boolean(),
  })
  .primaryKey('messageId');

export const messageAttachmentTable = table('message_attachments')
  .columns({
    id: string(),
    entityType: enumeration<AttachmentEntityType>(),
    entityId: string(),
    storageProvider: string(),
    originalFilename: string(),
    mimetype: string(),
    size: number(),
    width: number().optional(),
    height: number().optional(),
    uploadedByUserId: string(),
    createdAt: number(),
    url: string(),
    createdBy: string(),
    metadata: json().optional(),
    conversationId: string(),
    thumbnailUrl: string().optional(),
  })
  .primaryKey('id');

export const reactionTable = table('reactions')
  .columns({
    reactionId: string(),
    messageId: string(),
    userId: string(),
    emojiName: string(),
    createdAt: number(),
  })
  .primaryKey('reactionId');

export const reactionCountTable = table('reaction_counts')
  .columns({
    countId: string(),
    messageId: string(),
    emojiName: string(),
    count: number(),
    updatedAt: number(),
  })
  .primaryKey('countId');

export const customEmojiTable = table('custom_emojis')
  .columns({
    id: string(),
    name: string(),
    url: string(),
    createdBy: string(),
    createdAt: number(),
  })
  .primaryKey('id');

export const activityTable = table('activities')
  .columns({
    id: string(),
    userId: string(),
    actorAction: string(),
    actionSource: string(), // @deprecated Use messageId, reactionId, or callId
    actionSourceId: string(), // @deprecated Use messageId, reactionId, or callId
    messageId: string().optional(),
    reactionId: string().optional(),
    callId: string().optional(),
    ticketId: string().optional(),
    channelId: string().optional(),
    actorId: string(),
    classification: enumeration<ActivityClassification>(),
    classificationConfidence: number().optional(),
    classificationJobType: enumeration<ActivityClassificationJobType>().optional(),
    isRead: boolean(),
    createdAt: number(),
  })
  .primaryKey('id');

export const notificationTable = table('notifications')
  .columns({
    id: string(),
    userId: string(),
    type: enumeration<NotificationType>(),
    title: string(),
    message: string(),
    status: enumeration<NotificationStatus>(),
    deliveryMethods: json<NotificationDeliveryMethod[]>(),
    metadata: json().optional(),
    relatedEntityType: string().optional(),
    relatedEntityId: string().optional(),
    actionUrl: string().optional(),
    expiresAt: number().optional(),
    readAt: number().optional(),
    dismissedAt: number().optional(),
    createdAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');

export const notificationPreferenceTable = table('notification_preferences')
  .columns({
    id: string(),
    userId: string(),
    notificationType: enumeration<NotificationType>(),
    browserEnabled: boolean(),
    emailEnabled: boolean(),
    slackEnabled: boolean(),
    createdAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');

export const callTable = table('calls')
  .columns({
    id: string(),
    externalId: string(),
    title: string().optional(),
    createdByUserId: string(),
    organizerId: string().optional(),
    channelId: string(),
    orgName: string().optional(),
    description: string().optional(),
    callType: enumeration<CallType>(),
    status: enumeration<CallStatus>(),
    roomLink: string().optional(),
    startsAt: number().optional(),
    endsAt: number().optional(),
    timezone: string(),
    isRecurring: boolean(),
    recurringSeriesId: string().optional(),
    recurrenceRule: string().optional(),
    instanceDate: number().optional(),
    recordingEnabled: boolean(),
    transcript: string().optional(),
    aiSummary: string().optional(),
    startedAt: number(),
    endedAt: number().optional(),
    lastActivityAt: number(),
    createdAt: number(),
    updatedAt: number(),
    metadata: json().optional(),
  })
  .primaryKey('id');

export const callParticipantTable = table('call_participants')
  .columns({
    id: string(),
    callId: string(),
    userId: string(),
    invitedBy: string(),
    invitedAt: number(),
    response: enumeration<InvitationResponse>().optional(),
    respondedAt: number().optional(),
    joinedAt: number().optional(),
    leftAt: number().optional(),
    metadata: json().optional(),
  })
  .primaryKey('id');

export const canvasTable = table('canvases')
  .columns({
    id: string(),
    title: string(),
    content: json(),
    channelId: string().optional(),
    createdBy: string(),
    viewAccessId: string().optional(),
    editAccessId: string().optional(),
    visibility: enumeration<CanvasVisibility>(),
    isTemplate: boolean(),
    isCollaborative: boolean(),
    lastEditedBy: string().optional(),
    lastEditedAt: number().optional(),
    createdAt: number(),
    updatedAt: number(),
    metadata: json().optional(),
    docType: enumeration<DocType>(),
    userRepo: string().optional(),
    repoId: string().optional(),
    branchName: string().optional(),
    entryFile: string().optional(),
    quartoDocumentType: string().optional(),
    gcsPath: string().optional(),
  })
  .primaryKey('id');

export const canvasParticipantTable = table('canvas_participants')
  .columns({
    id: string(),
    canvasId: string(),
    userId: string(),
    role: enumeration<CanvasRole>(),
    joinedAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');

export const bookmarkTable = table('bookmarks')
  .columns({
    id: string(),
    userId: string(),
    entityId: string(),
    entityType: enumeration<BookmarkEntityType>(),
    createdAt: number(),
    metadata: json().optional(),
  })
  .primaryKey('id');

export const repoTable = table('repos')
  .columns({
    id: string(),
    name: string(),                     // e.g., "xyne-spaces"
    url: string(),                      // SSH or HTTPS URL
    baseBranch: json<string[]>(),       // Base branches to checkout from: ["main", "develop"]
    prefix: string(),                   // Branch prefix: "feature"
    createdBy: string(),
  })
  .primaryKey('id');

export const emailTable = table('emails')
  .columns({
    id: string(),
    type: enumeration<EmailType>(),
    subject: string(),
    body: string(),
    to: json<string[]>(),
    from: string(),
    cc: json<string[]>().optional(),
    bcc: json<string[]>().optional(),
    conversationId: string(),
    externalThreadId: string(),
    externalMessageId: string(),
    createdAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');

export const emailDraftTable = table('email_drafts')
  .columns({
    id: string(),
    conversationId: string(),
    draftContent: string(),
    createdAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');

export const formTable = table('forms')
  .columns({
    id: string(),
    formName: string(),
    formDescription: string().optional(),
    entityType: enumeration<FormEntityType>(),
    contextType: enumeration<FormContextType>(),
    createdBy: string(),
    createdAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');

export const formContextMappingTable = table('forms_context_mapping')
  .columns({
    id: string(),
    formId: string(),
    contextId: string(),
    contextType: enumeration<FormContextType>(),
    entityType: enumeration<FormEntityType>(),
  })
  .primaryKey('id');

export const formFieldsTable = table('form_fields')
  .columns({
    id: string(),
    formId: string(),
    fieldName: string(),
    fieldType: enumeration<FormFieldType>(),
    fieldEnum: json().optional(),
    isOptional: boolean().optional(),
    createdAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');

export const formEntityValuesTable = table('form_entity_values')
  .columns({
    id: string(),
    entityId: string(),
    entityType: string(),
    fieldId: string(),
    contextId: string().optional(),
    fieldValue: string(),
    actualFieldValue: json().optional(),
    createdAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');

export const stageApproversTable = table('stage_approvers')
  .columns({
    id: string(),
    userId: string(),
    stageId: string(),
    createdAt: number(),
    updatedAt: number().optional(),
  })
  .primaryKey('id');

export const ticketStageRequestTable = table('ticket_stage_requests')
  .columns({
    id: string(),
    ticketId: string(),
    stageId: string(),
    formId: string().optional(),
    status: enumeration<TicketStageRequestStatus>(),
    submittedBy: string(),
    reviewedBy: string().optional(),
    updatedBy: string(),
    createdAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');

// publishedDocTable has been deprecated - Quarto docs are now stored in canvasTable with isQuartoDoc=true
export const dashboardTable = table('dashboards')
  .columns({
    id: string(),
    name: string(),
    description: string().optional(),
    createdBy: string(),
    createdAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');

export const queryTable = table('queries')
  .columns({
    id: string(),
    title: string(),
    queryJson: json(),
    entityType: enumeration<FormEntityType>(),
    createdBy: string(),
    createdAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');

// Lookup Values Table
export const lookupValueTable = table('lookup_values')
  .columns({
    id: string(),
    type: enumeration<LookupType>(),
    value: string(),
    createdAt: number(),
  })
  .primaryKey('id');

// Release Management Tables


export const applicationTable = table('applications')
  .columns({
    id: string(),
    name: string(),
    projectId: string(),
    boardId: string(),
    channelId: string().optional(),
    regex: string(),
    repoUrl: string(),
    deployedCommit: string().optional(),
    lastDeployedAt: number().optional(),
    ownerTeam: string(),
    createdAt: number(),
  })
  .primaryKey('id');

export const applicationReleaseTicketTable = table('application_release_tickets')
  .columns({
    id: string(),
    applicationReleaseId: string(),
    ticketId: string(),
    title: string(),
    status: enumeration<ApplicationReleaseTicketStatus>(),
    testedBy: string().optional(),
    testedAt: number().optional(),
    failureReason: string().optional(),
    createdAt: number(),
  })
  .primaryKey('id');


export const releaseEventTable = table('release_events')
  .columns({
    id: string(),
    releaseId: string(),
    applicationReleaseId: string().optional(),
    eventType: enumeration<ReleaseEventType>(),
    eventName: string(),
    userId: string().optional(),
    userName: string().optional(),
    channelId: string(),
    conversationId: string(),
    payload: json().optional(),
    createdAt: number(),
    message: string()
  })
  .primaryKey('id');


export const releaseChangeTable = table('release_changes')
  .columns({
    id: string(),
    releaseId: string(),
    applicationReleaseId: string().optional(),
    applicationId: string().optional(),
    approvedBy: string().optional(),
    approvedAt: number().optional(),
    createdAt: number(),
  })
  .primaryKey('id');

export const releaseChangeTypeTable = table('release_change_types')
  .columns({
    id: string(),
    applicationId: string(),
    changeType: string(),
  })
  .primaryKey('id');

export const dashboardQueryMappingTable = table('dashboard_queries_mapping')
  .columns({
    id: string(),
    dashboardId: string(),
    queryId: string(),
    createdAt: number(),
    updatedAt: number(),
  })
  .primaryKey('id');
// Define relationships

export const merchantTable = table('merchants')
  .columns({
    id: string(),
    mid: string(),
  })
  .primaryKey('id');

// Merchant table relationships
export const merchantTableRelationships = relationships(merchantTable, ({ many }) => ({
  tickets: many({
    sourceField: ['mid'],
    destField: ['merchantId'],
    destSchema: ticketTable,
  }),
}));

export const agentTableRelationships = relationships(agentTable, ({ one, many }) => ({
  model: one({
    sourceField: ['modelId'],
    destField: ['id'],
    destSchema: modelTable,
  }),
  agentToolsMappings: many({
    sourceField: ['id'],
    destField: ['agentId'],
    destSchema: agentToolsMappingTable,
  }),
}));

export const modelTableRelationships = relationships(modelTable, ({ many }) => ({
  agents: many({
    sourceField: ['id'],
    destField: ['modelId'],
    destSchema: agentTable,
  }),
}));

export const toolTableRelationships = relationships(toolTable, ({ many }) => ({
  agentToolsMappings: many({
    sourceField: ['id'],
    destField: ['toolId'],
    destSchema: agentToolsMappingTable,
  }),
}));

export const agentToolsMappingTableRelationships = relationships(
  agentToolsMappingTable,
  ({ one }) => ({
    agent: one({
      sourceField: ['agentId'],
      destField: ['id'],
      destSchema: agentTable,
    }),
    tool: one({
      sourceField: ['toolId'],
      destField: ['id'],
      destSchema: toolTable,
    }),
  }),
);

export const ticketTableRelationships = relationships(ticketTable, ({ one, many }) => ({
  createdByUser: one({
    sourceField: ['createdBy'],
    destField: ['id'],
    destSchema: userTable,
  }),
  updatedByUser: one({
    sourceField: ['updatedBy'],
    destField: ['id'],
    destSchema: userTable,
  }),
  assignedToUser: one({
    sourceField: ['assignedTo'],
    destField: ['id'],
    destSchema: userTable,
  }),
  closedByUser: one({
    sourceField: ['closedBy'],
    destField: ['id'],
    destSchema: userTable,
  }),
  conversation: one({
    sourceField: ['conversationId'],
    destField: ['conversationId'],
    destSchema: conversationTable,
  }),
  channel: one({
    sourceField: ['channelId'],
    destField: ['id'],
    destSchema: channelTable,
  }),
  project: one({
    sourceField: ['projectId'],
    destField: ['id'],
    destSchema: projectTable,
  }),
  board: one({
    sourceField: ['boardId'],
    destField: ['id'],
    destSchema: boardTable,
  }),
  merchant: one({
    sourceField: ['merchantId'],
    destField: ['mid'],
    destSchema: merchantTable,
  }),
  ticketTypeLookup: one({
    sourceField: ['ticketType'],
    destField: ['value'],
    destSchema: lookupValueTable,
  }),
  tags: many({
    sourceField: ['id'],
    destField: ['ticketId'],
    destSchema: ticketTagTable,
  }),
  referencesOut: many({
    sourceField: ['id'],
    destField: ['sourceTicketId'],
    destSchema: ticketReferenceMappingTable,
  }),
  referencesIn: many({
    sourceField: ['id'],
    destField: ['targetTicketId'],
    destSchema: ticketReferenceMappingTable,
  }),
  entity: many({
    sourceField: ['id'],
    destField: ['ticketId'],
    destSchema: ticketEntityMappingTable,
  }),
  activities: many({
    sourceField: ['id'],
    destField: ['ticketId'],
    destSchema: ticketActivityTable,
  }),
  ticketStageRequests: many({
    sourceField: ['id'],
    destField: ['ticketId'],
    destSchema: ticketStageRequestTable,
  }),
  subTicketMappings: many({
    sourceField: ['id'],
    destField: ['ticketId'],
    destSchema: ticketSubTicketMappingTable,
  }),
  workflows: many({
    sourceField: ['id'],
    destField: ['ticketId'],
    destSchema: workflowTable,
  }),
  formEntityValues: many({
    sourceField: ['id'],
    destField: ['entityId'],
    destSchema: formEntityValuesTable,
  }),
  assignments: many({
    sourceField: ['id'],
    destField: ['ticketId'],
    destSchema: ticketAssignmentTable,
  }),
}));

export const subTicketTableRelationships = relationships(subTicketTable, ({ one, many }) => ({
  createdByUser: one({
    sourceField: ['createdBy'],
    destField: ['id'],
    destSchema: userTable,
  }),
  updatedByUser: one({
    sourceField: ['updatedBy'],
    destField: ['id'],
    destSchema: userTable,
  }),
  assignedToUser: one({
    sourceField: ['assignedTo'],
    destField: ['id'],
    destSchema: userTable,
  }),
  conversation: one({
    sourceField: ['conversationId'],
    destField: ['conversationId'],
    destSchema: conversationTable,
  }),
  mappedTicket: one({
    sourceField: ['mappedTicketId'],
    destField: ['id'],
    destSchema: ticketTable,
  }),
  ticketMappings: many({
    sourceField: ['id'],
    destField: ['subTicketId'],
    destSchema: ticketSubTicketMappingTable,
  }),
}));

export const ticketSubTicketMappingTableRelationships = relationships(
  ticketSubTicketMappingTable,
  ({ one }) => ({
    ticket: one({
      sourceField: ['ticketId'],
      destField: ['id'],
      destSchema: ticketTable,
    }),
    subTicket: one({
      sourceField: ['subTicketId'],
      destField: ['id'],
      destSchema: subTicketTable,
    }),
  }),
);

export const ticketAssignmentTableRelationships = relationships(
  ticketAssignmentTable,
  ({ one }) => ({
    ticket: one({
      sourceField: ['ticketId'],
      destField: ['id'],
      destSchema: ticketTable,
    }),
  }),
);

export const ticketActivityTableRelationships = relationships(ticketActivityTable, ({ one }) => ({
  ticket: one({
    sourceField: ['ticketId'],
    destField: ['id'],
    destSchema: ticketTable,
  }),
  updatedByUser: one({
    sourceField: ['updatedBy'],
    destField: ['id'],
    destSchema: userTable,
  }),
}));

export const ticketEntityMappingTableRelationships = relationships(
  ticketEntityMappingTable,
  ({ one }) => ({
    ticket: one({
      sourceField: ['ticketId'],
      destField: ['id'],
      destSchema: ticketTable,
    }),
  }),
);

export const ticketTagTableRelationships = relationships(ticketTagTable, ({ one }) => ({
  ticket: one({
    sourceField: ['ticketId'],
    destField: ['id'],
    destSchema: ticketTable,
  }),
}));

export const ticketReferenceMappingTableRelationships = relationships(
  ticketReferenceMappingTable,
  ({ one }) => ({
    sourceTicket: one({
      sourceField: ['sourceTicketId'],
      destField: ['id'],
      destSchema: ticketTable,
    }),
    targetTicket: one({
      sourceField: ['targetTicketId'],
      destField: ['id'],
      destSchema: ticketTable,
    }),
  }),
);

export const projectTableRelationships = relationships(projectTable, ({ one, many }) => ({
  createdByUser: one({
    sourceField: ['createdBy'],
    destField: ['id'],
    destSchema: userTable,
  }),
  updatedByUser: one({
    sourceField: ['updatedBy'],
    destField: ['id'],
    destSchema: userTable,
  }),
  tickets: many({
    sourceField: ['id'],
    destField: ['projectId'],
    destSchema: ticketTable,
  }),
  boards: many({
    sourceField: ['id'],
    destField: ['projectId'],
    destSchema: boardTable,
  }),
  channels: many({
    sourceField: ['id'],
    destField: ['projectId'],
    destSchema: channelTable,
  }),
}));

export const boardTableRelationships = relationships(boardTable, ({ one, many }) => ({
  project: one({
    sourceField: ['projectId'],
    destField: ['id'],
    destSchema: projectTable,
  }),
  createdByUser: one({
    sourceField: ['createdBy'],
    destField: ['id'],
    destSchema: userTable,
  }),
  updatedByUser: one({
    sourceField: ['updatedBy'],
    destField: ['id'],
    destSchema: userTable,
  }),
  stages: many({
    sourceField: ['id'],
    destField: ['boardId'],
    destSchema: stageTable,
  }),
  tickets: many({
    sourceField: ['id'],
    destField: ['boardId'],
    destSchema: ticketTable,
  }),
  formContextMappings: many({
    sourceField: ['id'],
    destField: ['contextId'],
    destSchema: formContextMappingTable,
  }),
  applications: many({
    sourceField: ['id'],
    destField: ['boardId'],
    destSchema: applicationTable,
  }),
}));

export const stageTableRelationships = relationships(stageTable, ({ one, many }) => ({
  board: one({
    sourceField: ['boardId'],
    destField: ['id'],
    destSchema: boardTable,
  }),
  createdByUser: one({
    sourceField: ['createdBy'],
    destField: ['id'],
    destSchema: userTable,
  }),
  updatedByUser: one({
    sourceField: ['updatedBy'],
    destField: ['id'],
    destSchema: userTable,
  }),
  prStatusMappings: many({
    sourceField: ['id'],
    destField: ['stageId'],
    destSchema: stagePRStatusMappingTable,
  }),
  approvers: many({
    sourceField: ['id'],
    destField: ['stageId'],
    destSchema: stageApproversTable,
  }),
  formContextMappings: many({
    sourceField: ['id'],
      destField: ['contextId'],
      destSchema: formContextMappingTable,
    }),
}));

export const stagePRStatusMappingTableRelationships = relationships(
  stagePRStatusMappingTable,
  ({ one }) => ({
    stage: one({
      sourceField: ['stageId'],
      destField: ['id'],
      destSchema: stageTable,
    }),
  })
);

export const userGroupMappingTableRelationships = relationships(
  userGroupMappingTable,
  ({ one }) => ({
    user: one({
      sourceField: ['userId'],
      destField: ['id'],
      destSchema: userTable,
    }),
    userGroup: one({
      sourceField: ['userGroupId'],
      destField: ['id'],
      destSchema: userGroupTable,
    }),
  }),
);

export const userAssignmentStateTableRelationships = relationships(
  userAssignmentStateTable,
  ({ one }) => ({
    user: one({
      sourceField: ['userId'],
      destField: ['id'],
      destSchema: userTable,
    }),
    userGroup: one({
      sourceField: ['userGroupId'],
      destField: ['id'],
      destSchema: userGroupTable,
    }),
  }),
);

export const boardComplexityScoreTableRelationships = relationships(
  boardComplexityScoreTable,
  ({ one }) => ({
    userGroup: one({
      sourceField: ['userGroupId'],
      destField: ['id'],
      destSchema: userGroupTable,
    }),
    board: one({
      sourceField: ['boardId'],
      destField: ['id'],
      destSchema: boardTable,
    }),
  }),
);

export const userWorkloadMappingTableRelationships = relationships(
  userWorkloadMappingTable,
  ({ one }) => ({
    user: one({
      sourceField: ['userId'],
      destField: ['id'],
      destSchema: userTable,
    }),
    userGroup: one({
      sourceField: ['userGroupId'],
      destField: ['id'],
      destSchema: userGroupTable,
    }),
    board: one({
      sourceField: ['boardId'],
      destField: ['id'],
      destSchema: boardTable,
    }),
  }),
);

export const userExpertiseMappingTableRelationships = relationships(
  userExpertiseMappingTable,
  ({ one }) => ({
    user: one({
      sourceField: ['userId'],
      destField: ['id'],
      destSchema: userTable,
    }),
    userGroup: one({
      sourceField: ['userGroupId'],
      destField: ['id'],
      destSchema: userGroupTable,
    }),
    board: one({
      sourceField: ['boardId'],
      destField: ['id'],
      destSchema: boardTable,
    }),
  }),
);

export const workflowTableRelationships = relationships(workflowTable, ({ one, many }) => ({
  ticket: one({
    sourceField: ['ticketId'],
    destField: ['id'],
    destSchema: ticketTable,
  }),
  workflowExecutions: many({
    sourceField: ['id'],
    destField: ['workflowId'],
    destSchema: workflowExecutionTable,
  }),
}));

export const workflowExecutionTableRelationships = relationships(
  workflowExecutionTable,
  ({ one, many }) => ({
    workflow: one({
      sourceField: ['workflowId'],
      destField: ['id'],
      destSchema: workflowTable,
    }),
    parentWorkflowExecution: one({
      sourceField: ['parentWorkflowExecutionId'],
      destField: ['id'],
      destSchema: workflowExecutionTable,
    }),
    childWorkflowExecutions: many({
      sourceField: ['id'],
      destField: ['parentWorkflowExecutionId'],
      destSchema: workflowExecutionTable,
    }),
    pullRequests: many({
      sourceField: ['id'],
      destField: ['workflowExecutionId'],
      destSchema: pullRequestsTable,
    }),
  }),
);


export const userGroupTableRelationships = relationships(userGroupTable, ({ many }) => ({
  userGroupMappings: many({
    sourceField: ['id'],
    destField: ['userGroupId'],
    destSchema: userGroupMappingTable,
  }),
}));

export const userTableRelationships = relationships(userTable, ({ one, many }) => ({
  createdTickets: many({
    sourceField: ['id'],
    destField: ['createdBy'],
    destSchema: ticketTable,
  }),
  updatedTickets: many({
    sourceField: ['id'],
    destField: ['updatedBy'],
    destSchema: ticketTable,
  }),
  assignedTickets: many({
    sourceField: ['id'],
    destField: ['assignedTo'],
    destSchema: ticketTable,
  }),
  presenceStatus: one({
    sourceField: ['id'],
    destField: ['userId'],
    destSchema: userPresenceTable,
  }),
  userGroupMappings: many({
    sourceField: ['id'],
    destField: ['userId'],
    destSchema: userGroupMappingTable,
  }),
  channelParticipations: many({
    sourceField: ['id'],
    destField: ['userId'],
    destSchema: channelParticipantTable,
  }),
  sentMessages: many({
    sourceField: ['id'],
    destField: ['senderId'],
    destSchema: messageTable,
  }),
  createdConversations: many({
    sourceField: ['id'],
    destField: ['createdBy'],
    destSchema: conversationTable,
  }),
  createdChannels: many({
    sourceField: ['id'],
    destField: ['createdBy'],
    destSchema: channelTable,
  }),
  activities: many({
    sourceField: ['id'],
    destField: ['userId'],
    destSchema: activityTable,
  }),
}));

export const userPresenceTableRelationships = relationships(userPresenceTable, ({ one }) => ({
  user: one({
    sourceField: ['userId'],
    destField: ['id'],
    destSchema: userTable,
  }),
}));

export const resourceTableRelationships = relationships(resourceTable, ({ many }) => ({
  resourceAccess: many({
    sourceField: ['id'],
    destField: ['resourceId'],
    destSchema: resourceAccessTable,
  }),
}));

export const resourceAccessTableRelationships = relationships(resourceAccessTable, ({ one }) => ({
  userGroup: one({
    sourceField: ['groupId'],
    destField: ['id'],
    destSchema: userGroupTable,
  }),
  user: one({
    sourceField: ['userId'],
    destField: ['id'],
    destSchema: userTable,
  }),
  resource: one({
    sourceField: ['resourceId'],
    destField: ['id'],
    destSchema: resourceTable,
  }),
}));

// MANUAL RELATIONS WRITTEN BELOW

export const conversationTableRelationships = relationships(conversationTable, ({ one, many }) => ({
  channel: one({
    sourceField: ['channelId'],
    destField: ['id'],
    destSchema: channelTable,
  }),
  initialMessage: one({
    sourceField: ['initialMessageId'],
    destField: ['messageId'],
    destSchema: messageTable,
  }),
  parentMessage: one({
    sourceField: ['parentMessageId'],
    destField: ['messageId'],
    destSchema: messageTable,
  }),
  messages: many({
    sourceField: ['conversationId'],
    destField: ['conversationId'],
    destSchema: messageTable,
  }),
  createdByUser: one({
    sourceField: ['createdBy'],
    destField: ['id'],
    destSchema: userTable,
  }),
  participants: many({
    sourceField: ['conversationId'],
    destField: ['conversationId'],
    destSchema: conversationParticipantTable,
  }),
  emails: many({
    sourceField: ['conversationId'],
    destField: ['conversationId'],
    destSchema: emailTable,
  }),
  emailDrafts: many({
    sourceField: ['conversationId'],
    destField: ['conversationId'],
    destSchema: emailDraftTable,
  }),
  ticket: one({
    sourceField: ['ticketId'],
    destField: ['id'],
    destSchema: ticketTable,
  }),
}));

export const conversationParticipantTableRelationships = relationships(
  conversationParticipantTable,
  ({ one }) => ({
    conversation: one({
      sourceField: ['conversationId'],
      destField: ['conversationId'],
      destSchema: conversationTable,
    }),
    user: one({
      sourceField: ['userId'],
      destField: ['id'],
      destSchema: userTable,
    }),
  })
);

export const channelTableRelationships = relationships(channelTable, ({ one, many }) => ({
  conversations: many({
    sourceField: ['id'],
    destField: ['channelId'],
    destSchema: conversationTable,
  }),
  participants: many({
    sourceField: ['id'],
    destField: ['channelId'],
    destSchema: channelParticipantTable,
  }),
  participantsStatus: many({
    sourceField: ['id'],
    destField: ['channelId'],
    destSchema: channelUserStatusTable,
  }),
  createdByUser: one({
    sourceField: ['createdBy'],
    destField: ['id'],
    destSchema: userTable,
  }),
  project: one({
    sourceField: ['projectId'],
    destField: ['id'],
    destSchema: projectTable,
  }),
  calls: many({
    sourceField: ['id'],
    destField: ['channelId'],
    destSchema: callTable,
  }),
  tickets: many({
    sourceField: ['id'],
    destField: ['channelId'],
    destSchema: ticketTable,
  }),
}));


export const attachementTableRelationShips = relationships(messageAttachmentTable, ({ one }) => ({
  conversation: one({
    sourceField: ["conversationId"],
    destField: ["conversationId"],
    destSchema: conversationTable
  })
}))

export const messageTableRelationships = relationships(messageTable, ({ one, many }) => ({
  conversation: one({
    sourceField: ['conversationId'],
    destField: ['conversationId'],
    destSchema: conversationTable,
  }),
  childConversation: one({
    sourceField: ['childConversationId'],
    destField: ['conversationId'],
    destSchema: conversationTable,
  }),
  sender: one({
    sourceField: ['senderId'],
    destField: ['id'],
    destSchema: userTable,
  }),
  attachments: many({
    sourceField: ['messageId'],
    destField: ['entityId'],
    destSchema: messageAttachmentTable,
  }),
  reactions: many({
    sourceField: ['messageId'],
    destField: ['messageId'],
    destSchema: reactionTable,
  }),
  reactionCounts: many({
    sourceField: ['messageId'],
    destField: ['messageId'],
    destSchema: reactionCountTable,
  }),
}));

export const customEmojiTableRelationships = relationships(customEmojiTable, ({ one }) => ({
  creator: one({
    sourceField: ['createdBy'],
    destField: ['id'],
    destSchema: userTable,
  }),
}));

export const channelParticipantTableRelationships = relationships(
  channelParticipantTable,
  ({ one }) => ({
    channel: one({
      sourceField: ['channelId'],
      destField: ['id'],
      destSchema: channelTable,
    }),
    user: one({
      sourceField: ['userId'],
      destField: ['id'],
      destSchema: userTable,
    }),
    lastViewedConversation: one({
      sourceField: ['lastViewedConversationId'],
      destField: ['conversationId'],
      destSchema: conversationTable,
    }),
  }),
);

export const channelUserStatusTableRelationships = relationships(
  channelUserStatusTable,
  ({ one }) => ({
    channel: one({
      sourceField: ['channelId'],
      destField: ['id'],
      destSchema: channelTable,
    }),
    user: one({
      sourceField: ['userId'],
      destField: ['id'],
      destSchema: userTable,
    }),
  }),
);

export const reactionTableRelationships = relationships(reactionTable, ({ one }) => ({
  message: one({
    sourceField: ['messageId'],
    destField: ['messageId'],
    destSchema: messageTable,
  }),
  user: one({
    sourceField: ['userId'],
    destField: ['id'],
    destSchema: userTable,
  }),
}));

export const reactionCountTableRelationships = relationships(reactionCountTable, ({ one }) => ({
  message: one({
    sourceField: ['messageId'],
    destField: ['messageId'],
    destSchema: messageTable,
  }),
}));

export const activityTableRelationships = relationships(activityTable, ({ one }) => ({
  user: one({
    sourceField: ['userId'],
    destField: ['id'],
    destSchema: userTable,
  }),
  channel: one({
    sourceField: ['channelId'],
    destField: ['id'],
    destSchema: channelTable,
  }),
  message: one({
    sourceField: ['messageId'],
    destField: ['messageId'],
    destSchema: messageTable,
  }),
  reaction: one({
    sourceField: ['reactionId'],
    destField: ['reactionId'],
    destSchema: reactionTable,
  }),
  call: one({
    sourceField: ['callId'],
    destField: ['id'],
    destSchema: callTable,
  }),
  ticket: one({
    sourceField: ['ticketId'],
    destField: ['id'],
    destSchema: ticketTable,
  }),
  actor: one({
    sourceField: ['actorId'],
    destField: ['id'],
    destSchema: userTable,
  }),
}));

export const callTableRelationships = relationships(callTable, ({ one, many }) => ({
  createdByUser: one({
    sourceField: ['createdByUserId'],
    destField: ['id'],
    destSchema: userTable,
  }),
  channel: one({
    sourceField: ['channelId'],
    destField: ['id'],
    destSchema: channelTable,
  }),
  participants: many({
    sourceField: ['id'],
    destField: ['callId'],
    destSchema: callParticipantTable,
  }),
}));

export const callParticipantTableRelationships = relationships(callParticipantTable, ({ one }) => ({
  call: one({
    sourceField: ['callId'],
    destField: ['id'],
    destSchema: callTable,
  }),
  user: one({
    sourceField: ['userId'],
    destField: ['id'],
    destSchema: userTable,
  }),
  inviter: one({
    sourceField: ['invitedBy'],
    destField: ['id'],
    destSchema: userTable,
  }),
}));

export const canvasTableRelationships = relationships(canvasTable, ({ one, many }) => ({
  participants: many({
    sourceField: ['id'],
    destField: ['canvasId'],
    destSchema: canvasParticipantTable,
  }),
  channel: one({
    sourceField: ['channelId'],
    destField: ['id'],
    destSchema: channelTable,
  }),
}));

export const canvasParticipantTableRelationships = relationships(canvasParticipantTable, ({ one }) => ({
  canvas: one({
    sourceField: ['canvasId'],
    destField: ['id'],
    destSchema: canvasTable,
  }),
  user: one({
    sourceField: ['userId'],
    destField: ['id'],
    destSchema: userTable,
  })
}));

export const pullRequestsTableRelationships = relationships(pullRequestsTable, ({ one }) => ({
  workflowExecution: one({
    sourceField: ['workflowExecutionId'],
    destField: ['id'],
    destSchema: workflowExecutionTable,
  }),
}));

export const organizationTableRelationships = relationships(organizationTable, ({ one, many }) => ({
  members: many({
    sourceField: ['orgId'],
    destField: ['orgId'],
    destSchema: orgMemberTable,
  }),
  createdByUser: one({
    sourceField: ['createdBy'],
    destField: ['id'],
    destSchema: userTable,
  }),
}));

export const orgMemberTableRelationships = relationships(orgMemberTable, ({ one }) => ({
  organization: one({
    sourceField: ['orgId'],
    destField: ['orgId'],
    destSchema: organizationTable,
  }),
  user: one({
    sourceField: ['userId'],
    destField: ['id'],
    destSchema: userTable,
  }),
}));

export const bookmarkTableRelationships = relationships(bookmarkTable, ({ one }) => ({
  user: one({
    sourceField: ['userId'],
    destField: ['id'],
    destSchema: userTable,
  }),
}));

export const emailTableRelationships = relationships(emailTable, ({ one }) => ({
  conversation: one({
    sourceField: ['conversationId'],
    destField: ['conversationId'],
    destSchema: conversationTable,
  }),
}));

export const emailDraftTableRelationships = relationships(emailDraftTable, ({ one }) => ({
  conversation: one({
    sourceField: ['conversationId'],
    destField: ['conversationId'],
    destSchema: conversationTable,
  }),
}));

export const formTableRelationships = relationships(formTable, ({ one, many }) => ({
  createdByUser: one({
    sourceField: ['createdBy'],
    destField: ['id'],
    destSchema: userTable,
  }),
  formFields: many({
    sourceField: ['id'],
    destField: ['formId'],
    destSchema: formFieldsTable,
  }),
  formContextMappings: many({
    sourceField: ['id'],
    destField: ['formId'],
    destSchema: formContextMappingTable,
  }),
}));

export const formContextMappingTableRelationships = relationships(formContextMappingTable, ({ one, many }) => ({
  form: one({
    sourceField: ['formId'],
    destField: ['id'],
    destSchema: formTable,
  }),
  formFields: many({
    sourceField: ['formId'],
    destField: ['formId'],
    destSchema: formFieldsTable,
  }),
  stage: one({
    sourceField: ['contextId'],
    destField: ['id'],
    destSchema: stageTable,
  }),
}));

export const formFieldsTableRelationships = relationships(formFieldsTable, ({ one, many }) => ({
  form: one({
    sourceField: ['formId'],
    destField: ['id'],
    destSchema: formTable,
  }),
  formEntityValues: many({
    sourceField: ['id'],
    destField: ['fieldId'],
    destSchema: formEntityValuesTable,
  }),
}));

export const formEntityValuesTableRelationships = relationships(formEntityValuesTable, ({ one }) => ({
  formField: one({
    sourceField: ['fieldId'],
    destField: ['id'],
    destSchema: formFieldsTable,
  }),
}));

export const ticketStageRequestTableRelationships = relationships(ticketStageRequestTable, ({ one }) => ({
  form: one({
    sourceField: ['formId'],
    destField: ['id'],
    destSchema: formTable,
  }),
}));

export const dashboardTableRelationships = relationships(dashboardTable, ({ many }) => ({
  queryMappings: many({
    sourceField: ['id'],
    destField: ['dashboardId'],
    destSchema: dashboardQueryMappingTable,
  }),
}));

export const queryTableRelationships = relationships(queryTable, ({ many }) => ({
  dashboardMappings: many({
    sourceField: ['id'],
    destField: ['queryId'],
    destSchema: dashboardQueryMappingTable,
  }),
}));

export const dashboardQueryMappingTableRelationships = relationships(dashboardQueryMappingTable, ({ one }) => ({
  dashboard: one({
    sourceField: ['dashboardId'],
    destField: ['id'],
    destSchema: dashboardTable,
  }),
  query: one({
    sourceField: ['queryId'],
    destField: ['id'],
    destSchema: queryTable,
  }),
}));

export const lookupValueTableRelationships = relationships(lookupValueTable, ({ many }) => ({
  tickets: many({
    sourceField: ['value'],
    destField: ['ticketType'],
    destSchema: ticketTable,
  }),
}));

// Release Management Relationships
export const applicationTableRelationships = relationships(applicationTable, ({ one }) => ({
  project: one({
    sourceField: ['projectId'],
    destField: ['id'],
    destSchema: projectTable,
  }),
  board: one({
    sourceField: ['boardId'],
    destField: ['id'],
    destSchema: boardTable,
  }),
}));

export const applicationReleaseTicketTableRelationships = relationships(applicationReleaseTicketTable, ({ one }) => ({
  subTicket: one({
    sourceField: ['applicationReleaseId'],
    destField: ['id'],
    destSchema: subTicketTable,
  }),
}));


export const releaseEventTableRelationships = relationships(releaseEventTable, ({ one }) => ({
  release: one({
    sourceField: ['releaseId'],
    destField: ['id'],
    destSchema: ticketTable,
  }),
  applicationRelease: one({
    sourceField: ['applicationReleaseId'],
    destField: ['id'],
    destSchema: subTicketTable,
  }),
}));




// Define schema

export const schema = createSchema({
  enableLegacyMutators: false,
  enableLegacyQueries: false,
  tables: [
    agentTable,
    modelTable,
    toolTable,
    agentToolsMappingTable,
    ticketTable,
    subTicketTable,
    ticketSubTicketMappingTable,
    ticketAssignmentTable,
    ticketActivityTable,
    ticketEntityMappingTable,
    ticketTagTable,
    ticketReferenceMappingTable,
    projectTable,
    boardTable,
    stageTable,
    stagePRStatusMappingTable,
    userGroupMappingTable,
    userAssignmentStateTable,
    boardComplexityScoreTable,
    userWorkloadMappingTable,
    userExpertiseMappingTable,
    workflowTable,
    workflowExecutionTable,
    userGroupTable,
    userTable,
    userPresenceTable,
    userProfileTable,
    resourceTable,
    resourceAccessTable,
    pullRequestsTable,
    organizationTable,
    orgMemberTable,
    channelTable,
    channelParticipantTable,
    channelUserStatusTable,
    conversationTable,
    conversationParticipantTable,
    messageTable,
    messageAttachmentTable,
    reactionTable,
    reactionCountTable,
    customEmojiTable,
    activityTable,
    notificationTable,
    notificationPreferenceTable,
    callTable,
    callParticipantTable,
    canvasTable,
    canvasParticipantTable,
    bookmarkTable,
    repoTable,
    emailTable,
    emailDraftTable,
    formTable,
    formContextMappingTable,
    formFieldsTable,
    formEntityValuesTable,
    stageApproversTable,
    ticketStageRequestTable,
    dashboardTable,
    queryTable,
    dashboardQueryMappingTable,
    merchantTable,
    lookupValueTable,
    // Release Management
    applicationTable,
    applicationReleaseTicketTable,
    releaseEventTable,
  ],
  relationships: [
    agentTableRelationships,
    modelTableRelationships,
    toolTableRelationships,
    agentToolsMappingTableRelationships,
    ticketTableRelationships,
    subTicketTableRelationships,
    ticketSubTicketMappingTableRelationships,
    ticketAssignmentTableRelationships,
    ticketActivityTableRelationships,
    ticketEntityMappingTableRelationships,
    ticketTagTableRelationships,
    ticketReferenceMappingTableRelationships,
    projectTableRelationships,
    attachementTableRelationShips,
    boardTableRelationships,
    stageTableRelationships,
    stagePRStatusMappingTableRelationships,
    userGroupMappingTableRelationships,
    userAssignmentStateTableRelationships,
    boardComplexityScoreTableRelationships,
    userWorkloadMappingTableRelationships,
    userExpertiseMappingTableRelationships,
    workflowTableRelationships,
    workflowExecutionTableRelationships,
    userGroupTableRelationships,
    userTableRelationships,
    userPresenceTableRelationships,
    resourceTableRelationships,
    resourceAccessTableRelationships,
    conversationTableRelationships,
    conversationParticipantTableRelationships,
    channelTableRelationships,
    messageTableRelationships,
    channelParticipantTableRelationships,
    channelUserStatusTableRelationships,
    reactionTableRelationships,
    activityTableRelationships,
    callTableRelationships,
    callParticipantTableRelationships,
    canvasTableRelationships,
    canvasParticipantTableRelationships,
    pullRequestsTableRelationships,
    organizationTableRelationships,
    orgMemberTableRelationships,
    reactionCountTableRelationships,
    customEmojiTableRelationships,
    bookmarkTableRelationships,
    emailTableRelationships,
    emailDraftTableRelationships,
    formTableRelationships,
    formContextMappingTableRelationships,
    formFieldsTableRelationships,
    formEntityValuesTableRelationships,
    ticketStageRequestTableRelationships,
    dashboardTableRelationships,
    queryTableRelationships,
    dashboardQueryMappingTableRelationships,
    merchantTableRelationships,
    lookupValueTableRelationships,
    // Release Management
    applicationTableRelationships,
    applicationReleaseTicketTableRelationships,
    releaseEventTableRelationships,
  ],
});

// Define types
export type Schema = typeof schema;
export type Agent = Row<typeof schema.tables.agents>;
export type Model = Row<typeof schema.tables.models>;
export type Tool = Row<typeof schema.tables.tools>;
export type AgentToolsMapping = Row<typeof schema.tables.agent_tools_mappings>;
export type Ticket = Row<typeof schema.tables.tickets>;
export type SubTicket = Row<typeof schema.tables.sub_tickets>;
export type TicketSubTicketMapping = Row<typeof schema.tables.ticket_sub_ticket_mappings>;
export type TicketActivity = Row<typeof schema.tables.ticket_activities>;
export type TicketEntityMapping = Row<typeof schema.tables.ticket_entity_mappings>;
export type TicketTag = Row<typeof schema.tables.ticket_tags>;
export type TicketAssignment = Row<typeof schema.tables.ticket_assignments>;
export type TicketReferenceMapping = Row<typeof schema.tables.ticket_reference_mappings>;
export type Project = Row<typeof schema.tables.projects>;
export type Board = Row<typeof schema.tables.boards>;
export type Stage = Row<typeof schema.tables.stages>;
export type StagePRStatusMapping = Row<typeof schema.tables.stage_pr_status_mappings>;
export type Workflow = Row<typeof schema.tables.workflows>;
export type WorkflowExecution = Row<typeof schema.tables.workflow_executions>;
export type UserGroup = Row<typeof schema.tables.user_groups>;
export type User = Row<typeof schema.tables.users>;
export type UserGroupMapping = Row<typeof schema.tables.user_group_mappings>;
export type UserAssignmentState = Row<typeof schema.tables.user_assignment_states>;
export type BoardComplexityScore = Row<typeof schema.tables.board_complexity_scores>;
export type UserWorkloadMapping = Row<typeof schema.tables.user_workload_mappings>;
export type UserExpertiseMapping = Row<typeof schema.tables.user_expertise_mappings>;
export type UserPresence = Row<typeof schema.tables.user_presence>;
export type Resource = Row<typeof schema.tables.resources>;
export type ResourceAccess = Row<typeof schema.tables.resource_access>;
export type PullRequests = Row<typeof schema.tables.pull_requests>;
export type Organization = Row<typeof schema.tables.organizations>;
export type OrgMember = Row<typeof schema.tables.org_members>;
export type Channel = Row<typeof schema.tables.channels>;
export type ChannelParticipant = Row<typeof schema.tables.channel_participants>;
export type ChannelUserStatus = Row<typeof schema.tables.channel_user_status>;
export type Conversation = Row<typeof schema.tables.conversations>;
export type Message = Row<typeof schema.tables.messages>;
export type MessageAttachment = Row<typeof schema.tables.message_attachments>;
export type Reaction = Row<typeof schema.tables.reactions>;
export type ReactionCount = Row<typeof schema.tables.reaction_counts>;
export type CustomEmoji = Row<typeof schema.tables.custom_emojis>;
export type Activity = Row<typeof schema.tables.activities>;
export type Notification = Row<typeof schema.tables.notifications>;
export type NotificationPreference = Row<typeof schema.tables.notification_preferences>;
export type Call = Row<typeof schema.tables.calls>;
export type CallParticipant = Row<typeof schema.tables.call_participants>;
export type ConversationParticipant = Row<typeof schema.tables.conversation_participants>;
export type Canvas = Row<typeof schema.tables.canvases>;
export type CanvasParticipant = Row<typeof schema.tables.canvas_participants>;
export type Bookmark = Row<typeof schema.tables.bookmarks>;
export type Email = Row<typeof schema.tables.emails>;
export type Repo = Row<typeof schema.tables.repos>;
export type EmailDraft = Row<typeof schema.tables.email_drafts>;
export type Form = Row<typeof schema.tables.forms>;
export type FormContextMapping = Row<typeof schema.tables.forms_context_mapping>;
export type FormFields = Row<typeof schema.tables.form_fields>;
export type FormEntityValues = Row<typeof schema.tables.form_entity_values>;
export type StageApprovers = Row<typeof schema.tables.stage_approvers>;
export type TicketStageRequest = Row<typeof schema.tables.ticket_stage_requests>;
export type Dashboard = Row<typeof schema.tables.dashboards>;
export type Query = Row<typeof schema.tables.queries>;
export type DashboardQueryMapping = Row<typeof schema.tables.dashboard_queries_mapping>;
export type Merchant = Row<typeof schema.tables.merchants>;
export type LookupValue = Row<typeof schema.tables.lookup_values>;

// Release Management Types
export type Application = Row<typeof schema.tables.applications>;
export type ApplicationReleaseTicket = Row<typeof schema.tables.application_release_tickets>;
export type ReleaseEvent = Row<typeof schema.tables.release_events>;

export type Context = {
  userID: string;
}

declare module '@rocicorp/zero' {
  interface DefaultTypes {
    context: Context;
    schema: Schema;
  }
}
