name: self-hosted-direct-test

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on:
      group: Default
      labels:  github-builds-runners
    steps:
      - run: echo "hello from self-hosted runner"
