import type { DeleteID, InsertValue, Transaction, UpdateValue } from '@rocicorp/zero';
import { RoomRecapStatus, Schema } from '@xyne/shared';
import { BaseACL } from '../core/base-acl';
import { MutationACLError, TableSchema } from '../core/types';
import { zql } from '../../queries';
import { getRoomInWorkspace, isRoomManager } from './room-acl-helpers';

export class RoomRecapsACL extends BaseACL<'room_recaps'> {
  async canInsert(
    _args: InsertValue<TableSchema<'room_recaps'>>,
    _tx: Transaction<Schema>
  ): Promise<void> {
    throw new MutationACLError(
      'Room recap insert failed: recaps are generated by curation, not written directly',
      'room_recaps'
    );
  }

  async canUpdate(
    args: UpdateValue<TableSchema<'room_recaps'>>,
    tx: Transaction<Schema>
  ): Promise<void> {
    const recap = await tx.run(zql.room_recaps.where('id', '=', args.id).one());
    if (!recap) {
      throw new MutationACLError('Room recap update failed: recap does not exist', 'room_recaps');
    }
    const room = await getRoomInWorkspace(recap.roomId, this.ctx, tx, 'room_recaps');
    if (!(await isRoomManager(room, this.ctx, tx))) {
      throw new MutationACLError(
        'Room recap update failed: only the room owner can modify a recap',
        'room_recaps'
      );
    }
    // citations is written by curation only - it backs the rendered citation links, so a
    // client must never be able to point them somewhere else.
    if (
      (args.roomId !== undefined && args.roomId !== recap.roomId) ||
      (args.type !== undefined && args.type !== recap.type) ||
      args.citations !== undefined
    ) {
      throw new MutationACLError(
        'Room recap update failed: only the body or approval fields can be changed',
        'room_recaps'
      );
    }

    const bodyChanged = args.body !== undefined && args.body !== recap.body;
    const approvalFieldsTouched =
      args.status !== undefined || args.approvedBy !== undefined || args.approvedAt !== undefined;

    if (bodyChanged) {
      if (recap.status !== RoomRecapStatus.PENDING) {
        throw new MutationACLError(
          'Room recap update failed: the body can only be edited while the recap is pending',
          'room_recaps'
        );
      }
      if (approvalFieldsTouched) {
        throw new MutationACLError(
          'Room recap update failed: editing the body and approving must be separate updates',
          'room_recaps'
        );
      }
      return;
    }

    if (args.status !== undefined && args.status !== RoomRecapStatus.APPROVED) {
      throw new MutationACLError(
        'Room recap update failed: a recap can only be moved to APPROVED',
        'room_recaps'
      );
    }
    if (args.approvedBy !== undefined && args.approvedBy !== this.ctx.userID) {
      throw new MutationACLError(
        'Room recap update failed: approvedBy must be the authenticated user',
        'room_recaps'
      );
    }
  }

  async canDelete(
    args: DeleteID<TableSchema<'room_recaps'>>,
    tx: Transaction<Schema>
  ): Promise<void> {
    const recap = await tx.run(zql.room_recaps.where('id', '=', args.id).one());
    if (!recap) {
      throw new MutationACLError('Room recap delete failed: recap does not exist', 'room_recaps');
    }
    const room = await getRoomInWorkspace(recap.roomId, this.ctx, tx, 'room_recaps');
    if (!(await isRoomManager(room, this.ctx, tx))) {
      throw new MutationACLError(
        'Room recap delete failed: only the room owner can delete a recap',
        'room_recaps'
      );
    }
  }
}
