import { GOOGLE_PLAY_REVIEWS_SOURCE_TYPE } from '@xyne/shared';

export const SOCIAL_MEDIA_SOURCE_TYPES = {
  GOOGLE_PLAY: GOOGLE_PLAY_REVIEWS_SOURCE_TYPE,
} as const;

export const SOCIAL_MEDIA_INTERACTION_TYPES = {
  REVIEW: 'REVIEW',
  REPLY: 'REPLY',
} as const;
